### ISSUE TITLE
recursion depth: sns.clustermap(auc_mtx, figsize=(8,8))

### ISSUE THREAD

**Issue by dschrein** [aertslab/pySCENIC#10]
sorry to keep bombarding you!

```
>>> sns.clustermap(auc_mtx, figsize=(8,8))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 2651, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/usr/local/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 2651, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/usr/local/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 2651, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  [Previous line repeated 993 more times]
  File "/usr/local/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 2618, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/usr/local/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 2530, in _dendrogram_calculate_info
    leaf_label_func, i, labels)
  File "/usr/local/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 2403, in _append_singleton_leaf_node
    ivl.append(str(int(i)))
RecursionError: maximum recursion depth exceeded while getting the str of an object
>>> auc_mtx.shape
(11750, 253)
```

**Comment by bramvds** [comment]
Dear,

This is an issue outside the scope of pyscenic: please have a look at:
1. https://github.com/mwaskom/seaborn/issues/1152
2. https://github.com/scipy/scipy/issues/7271

It maybe helpful to first inspect the auc_mtx dataframe, e.g. display it with the simple heatmap function also available in the seaboard package.

Kr,
Bram

**Comment by dschrein** [comment]
thanks a lot. could this be related to the fact that my auc_mtx is composed completely of 0.0? (and would you know what that might signify?)  should i be subsetting?
```
>>> ex_matrix.shape
(11750, 14742)
```
