### ISSUE TITLE
NameError: free variable 'module_chunksize' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by dschrein** [aertslab/pySCENIC#11]
i realize this is getting ridiculous. prior to the upgrade i did not see this issue in prune2df. module_chunksize has a default defined in the function, so not surprisingly it doesn't matter if I provide it as an argument.

```
>>> with ProgressBar():
...   df = prune2df(dbs, modules, MOTIF_ANNOTATIONS_FNAME, module_chunksize=100)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/site-packages/pyscenic/prune.py", line 387, in prune2df
    num_workers, module_chunksize)
  File "/usr/local/lib/python3.6/site-packages/pyscenic/prune.py", line 293, in _distributed_calc
    return create_graph().compute(get=get, num_workers=num_workers if num_workers else cpu_count())
  File "/usr/local/lib/python3.6/site-packages/pyscenic/prune.py", line 287, in create_graph
    for db in delayed_or_future_dbs
  File "/usr/local/lib/python3.6/site-packages/dask/dataframe/io/io.py", line 489, in from_delayed
    for df in dfs]
  File "/usr/local/lib/python3.6/site-packages/dask/dataframe/io/io.py", line 486, in <listcomp>
    dfs = [delayed(df)
  File "/usr/local/lib/python3.6/site-packages/pyscenic/prune.py", line 288, in <genexpr>
    for gs_chunk in chunked_iter(modules, module_chunksize)))
NameError: free variable 'module_chunksize' referenced before assignment in enclosing scope
```

**Comment by bramvds** [comment]
Apologies. I'm actively working on pySCENIC. Please check release 0.8.4 .

**Comment by dschrein** [comment]
being part of the testing is the least i can do!

**Comment by dschrein** [comment]
version 0.8.4 resolves my issue and now i can see the heatmap. 

for further data exploration, do you recommend loading auc_mtx into R?

**Comment by bramvds** [comment]
Entirely depends on your language preference ...
