### ISSUE TITLE
error in pyscenic aucell : 'numpy.ndarray' object has no attribute 'split'

### ISSUE THREAD

**Issue by Sophia409** [aertslab/pySCENIC#112]
@cflerin  @s-aibar @bramvds   Hi, I finished grn and ctx ,but failed in running aucell. Though this command gave an error, it output a loom file to path to pySCENIC output. How can I solve this problem?
```
!pyscenic aucell \
    {f_loom_path_unfilt} \
    reg.csv \
    --output {f_pyscenic_output} \
    --num_workers 16
```
```
/public-supool/home/yhzhang/miniconda3/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2019-12-08 13:34:08,417 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2019-12-08 13:34:08,490 - pyscenic.cli.pyscenic - INFO - Loading gene signatures.

2019-12-08 13:34:09,334 - pyscenic.cli.pyscenic - INFO - Calculating cellular enrichment.

2019-12-08 13:34:13,076 - pyscenic.cli.pyscenic - INFO - Writing results to file.
Traceback (most recent call last):
  File "/public-supool/home/yhzhang/miniconda3/bin/pyscenic", line 10, in <module>
    sys.exit(main())
  File "/public-supool/home/yhzhang/miniconda3/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 408, in main
    args.func(args)
  File "/public-supool/home/yhzhang/miniconda3/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 200, in aucell_command
    append_auc_mtx(args.output.name, auc_mtx, signatures, args.num_workers)
  File "/public-supool/home/yhzhang/miniconda3/lib/python3.7/site-packages/pyscenic/cli/utils.py", line 276, in append_auc_mtx
    ds.ca[ATTRIBUTE_NAME_REGULONS_AUC] = create_structure_array(auc_mtx)
  File "/public-supool/home/yhzhang/miniconda3/lib/python3.7/site-packages/loompy/attribute_manager.py", line 129, in __setitem__
    return self.__setattr__(name, val)
  File "/public-supool/home/yhzhang/miniconda3/lib/python3.7/site-packages/loompy/attribute_manager.py", line 149, in __setattr__
    values = loompy.normalize_attr_values(val, compare_loom_spec_version(self.ds._file, "3.0.0") >= 0)
  File "/public-supool/home/yhzhang/miniconda3/lib/python3.7/site-packages/loompy/utils.py", line 27, in compare_loom_spec_version
    vf = int("".join(get_loom_spec_version(f).split(".")))
AttributeError: 'numpy.ndarray' object has no attribute 'split'
```

**Comment by acjmmartin** [comment]
@Sophia409  How did you solve this issue?

**Comment by cflerin** [comment]
Related to #105

**Comment by lidong123-lang** [comment]
How did you solve this issue?

**Comment by Xiujia-Yang** [comment]
Editing the built-in script `/path/to/loompy/utils.py` by replacing the line 27 with the following code,
`vf = int("".join(get_loom_spec_version(f)[0].split(".")))` help me solve this issue.

**Comment by Jintram** [comment]
I also raised this issue on the loompy github, https://github.com/linnarsson-lab/loompy/issues/185
