### ISSUE TITLE
grnboost error

### ISSUE THREAD

**Issue by ltosti** [aertslab/pySCENIC#131]
Hi there @cflerin @bramvds ,

I tried to run pyscenic grn and got the following error:

```  import pandas.util.testing as tm
  import pandas.util.testing as tm
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pyscenic/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/pyscenic/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 408, in main
    args.func(args)
  File "/home/user/miniconda3/envs/pyscenic/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 67, in find_adjacencies_command
    network = method(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client, seed=args.seed)
  File "/home/user/miniconda3/envs/pyscenic/lib/python3.7/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/home/user/miniconda3/envs/pyscenic/lib/python3.7/site-packages/arboreto/algo.py", line 115, in diy
    expression_matrix, gene_names, tf_names = _prepare_input(expression_data, gene_names, tf_names)
  File "/home/user/miniconda3/envs/pyscenic/lib/python3.7/site-packages/arboreto/algo.py", line 214, in _prepare_input
    expression_matrix = expression_data.as_matrix()
  File "/home/user/miniconda3/envs/pyscenic/lib/python3.7/site-packages/pandas/core/generic.py", line 5273, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'
```

Any idea of what is causing this?

Thanks!

**Comment by cflerin** [comment]
What version of Pandas are you using? Can you show the command you're running?

**Comment by ltosti** [comment]
I was using 1.0.1; I downgraded to 0.25.3 and it is now working. Thank you!
