### ISSUE TITLE
pySCENIC cli not working with --no_prune

### ISSUE THREAD

**Issue by klprint** [aertslab/pySCENIC#14]
Hi!
I would like to run the CLI with the option --no_prune, but this does not work because of some error.

I use the following command:

```bash
pyscenic ctx \
           -o SCENIC_out/grnboost_out_no_pruning.csv \
           --annotations_fname database/motifs-v9-nr.mgi-m0.001-o0.0.tbl \
           --num_workers 40 \
           --min_genes 5 \
           --expression_mtx_fname data/exp_transposed.tsv \
           --no_pruning \
           SCENIC_out/grnboost_out.csv \
           database/mm9-tss-centered-10kb-7species.mc9nr.feather
```

When I run this, I get the following output:

```text
2018-05-30 14:48:40,413 - pyscenic.cli.pyscenic - INFO - Creating modules.
Traceback (most recent call last):
  File "/home/hd/hd_hd/hd_lg367/.local/bin/pyscenic", line 11, in <module>
    sys.exit(main())
  File "/home/hd/hd_hd/hd_lg367/.local/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 334, in main
    args.func(args)
  File "/home/hd/hd_hd/hd_lg367/.local/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 129, in prune_targets_command
    modules = _df2modules(args)
  File "/home/hd/hd_hd/hd_lg367/.local/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 70, in _df2modules
    min_genes=args.min_genes)
  File "/home/hd/hd_hd/hd_lg367/.local/lib/python3.6/site-packages/pyscenic/utils.py", line 262, in modules_from_adjacencies
    rho_threshold=rho_threshold, mask_dropouts=rho_mask_dropouts)
  File "/home/hd/hd_hd/hd_lg367/.local/lib/python3.6/site-packages/pyscenic/utils.py", line 129, in add_correlation
    col_idx_pairs = _create_idx_pairs(adjacencies, ex_mtx)
  File "/home/hd/hd_hd/hd_lg367/.local/lib/python3.6/site-packages/pyscenic/utils.py", line 70, in _create_idx_pairs
    genes = set(adjacencies.TF).union(set(adjacencies.target))
  File "/opt/bwhpc/common/devel/python_intel/3.6_2018.0.022/intelpython3/lib/python3.6/site-packages/pandas/core/generic.py", line 3081, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'TF'
```

I also tried to rename the grnboost_out.csv to grnboost_out.tsv which still generates the aforementioned error.

The input looks as follows:

data/exp_transposed.tsv:
```bash
$ awk -F "\t" 'BEGIN{OFS=FS}{print $1,$2,$3,$4,$5}' data/exp_transposed.tsv | head
	4933401J01Rik	Gm26206	Xkr4	Gm18956
AAACCTGAGATCCTGT	0	0	1	0
AAACCTGAGCCAGGAT	0	0	0	0
AAACCTGCAAACGTGG	0	0	0	0
AAACGGGAGCGGCTTC	0	0	0	0
AAACGGGAGTCATCCA	0	0	0	0
AAACGGGAGTGCAAGC	0	0	0	0
AAACGGGAGTGGAGAA	0	0	0	0
AAACGGGCAATGTAAG	0	0	0	0
AAACGGGCAGTCAGCC	0	0	0	0
```

```bash
$ head SCENIC_out/grnboost_out.csv
TF	target	importance
Runx1t1	March3	90.00993732947946
Gadd45a	Tmcc2	88.48153749855663
Gadd45a	Specc1	88.28239385246135
Hdac10	Mettl7a3	83.80642644798267
Sub1	Gm2986	82.81329853390594
Sox6	Hbb-bt	78.98218688124797
Myef2	Slc24a5	77.44812698969015
Pbx3	C79798	75.75068014227527
Gadd45a	March3	74.6984648345887
```

It would be great, if you could elevate on the usage of the CLI with a step-by-step tutorial, just starting with the UMI count table, the TF file (each row one TF), the RcisTarget database and the TF annotation file, nothing else.
And also showing what to input if one does not want to prune the data.

All the best!
Kevin

**Comment by bramvds** [comment]
Hi Kevin,

The CLI infers the format of the input files based on its extension: i.e. a file with the extension TSV should be tab delimited while a CSV file should be delimited using commas. This explains your error message.

I'll try to make some time in the future to provide a more elaborate tutorial on how to use the CLI.

Kr,
Bram

**Comment by wangjiawen2013** [comment]
Dear bramvds,
I find that the outuput of pyscenic CLI is a bit different from that of "adjancencies = grnboost2(expression_data=ex_matrix, tf_names=tf_names, verbose=True)", is that resonable ?

**Comment by wangjiawen2013** [comment]
@bramvds 
I find that pyscenic CLI output is a little different from that of "adjancencies = grnboost2(expression_data=ex_matrix, tf_names=tf_names, verbose=True)" , is that reasonable ?
