### ISSUE TITLE
error with grn in pyscenic: dependencies version incompatibility?

### ISSUE THREAD

**Issue by KabitaBaral1** [aertslab/pySCENIC#155]
Hi,

I am running pyscenic using Jupyter Notebook following the following code:
https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI.ipynb

However, when I run grn, I come across errors which I think has to do with versions incompatibility
I used pyscenic = 0.10.0
dask = 1.0.0
distributed = 1.21.6
msgpack = 0.5.6
tornado = 5.0.0
pandas = 0.25.3

I get the following error which keeps on running:
/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/config.py:63: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config.update(yaml.load(text) or {})

2020-04-10 15:47:16,860 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2020-04-10 15:47:23,395 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/config.py:63: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config.update(yaml.load(text) or {})
/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 420, in main
    args.func(args)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 69, in find_adjacencies_command
    client, shutdown_callback = _prepare_client(args.client_or_address, num_workers=args.num_workers)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/pyscenic/prune.py", line 64, in _prepare_client
    client = Client(local_cluster)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/client.py", line 556, in __init__
    dask.set_options(get=self.get)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/dask/context.py", line 18, in set_options
    raise TypeError("The dask.set_options function has been deprecated.\n"
TypeError: The dask.set_options function has been deprecated.
Please use dask.config.set instead

  Before: with dask.set_options(foo='bar'):
              ...
  After:  with dask.config.set(foo='bar'):
              ...
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x1915e5128>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x1915e5128>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x11e401470>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x11e401470>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x19120a240>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x19120a240>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x19159ec88>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x19159ec88>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x19159eda0>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x19159eda0>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x191583e80>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x191583e80>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x1915e5240>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x1915e5240>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x1915bd390>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x1915bd390>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x11e6522e8>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x11e6522e8>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x1915b0da0>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x1915b0da0>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x1915cae48>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x1915cae48>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x11e5f2a90>: ConnectionRefusedError: [Errno 61] Connection refused',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 324, in connect
    convert_stream_closed_error(self, e)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x11e5f2a90>: ConnectionRefusedError: [Errno 61] Connection refused
Future exception was never retrieved
future: <Future finished exception=StreamClosedError('Stream is closed',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed
Future exception was never retrieved
future: <Future finished exception=StreamClosedError('Stream is closed',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed
Future exception was never retrieved
future: <Future finished exception=StreamClosedError('Stream is closed',)>
Traceback (most recent call last):
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/kabitabaral/anaconda3/envs/scanpy_04/lib/python3.6/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

Is this version incompatibility?

Thank you

**Comment by cflerin** [comment]
It's definitely a Dask issue, probably with the package version. Are you sure that those are the actual package versions that you have installed? 

I would recommend [looking here](https://pyscenic.readthedocs.io/en/latest/faq.html#i-am-having-problems-with-dask) for an alternative script to run the GRN step that will be more stable.

**Comment by KabitaBaral1** [comment]
Hi @cflerin I got it to work.

Thank you
