### ISSUE TITLE
[BUG]lp.create  OSError: Unable to create file

### ISSUE THREAD

**Issue by luying616** [aertslab/pySCENIC#192]
**Describe the bug**

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```python
lp.create("PBMC10k_filtered.loom",adata.X.transpose(),row_attrs, col_attrs)
```

2. Error encountered:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/Data01/luying/app/miniconda3/lib/python3.7/site-packages/loompy/loompy.py", line 1057, in create
    with new(filename, file_attrs=file_attrs) as ds:
  File "/share/Data01/luying/app/miniconda3/lib/python3.7/site-packages/loompy/loompy.py", line 983, in new
    f = h5py.File(name=filename, mode='w')
  File "/share/Data01/luying/app/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/share/Data01/luying/app/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 37, error message = 'No locks available')
```

**Expected behavior**

```- pySCENIC version: 0.10.3 
- Installation method: Pip
- Run environment: CLI
- OS: Centos
- conda versions: 4.8.3
```

**Comment by ghuls** [comment]
See: https://github.com/h5py/h5py/issues/1101

The following seems to help for some people:
```bash
export HDF5_USE_FILE_LOCKING='FALSE'
```

Else try to write to another filesystem. It looks like the filesystem on `/share` does not support file locking.

**Comment by cflerin** [comment]
Closing since I think this has been addressed.
