### ISSUE TITLE
error when running pySCENIC

### ISSUE THREAD

**Issue by WRui** [aertslab/pySCENIC#2]
hi, i meet the fallowing error when i run pySCENIC grnboost with command line and i have no ideal how to solve it .  I need you help, thank you (expression_matrix, gene as rows and samples as columns)
code : pyscenic grnboost expression_matrix.txt human_TF.txt -o test --num_workers 40 -t 

2018-03-20 15:36:45,094 - pyscenic.scenic - INFO - Loading datasets.
2018-03-20 15:37:23,391 - pyscenic.scenic - INFO - Calculating co-expression modules.
Traceback (most recent call last):
  File "/datb1/wangrui/software/anaconda3/bin/pyscenic", line 11, in <module>
    sys.exit(scenic())
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/pyscenic/scenic.py", line 354, in scenic
    args.func(args)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/pyscenic/scenic.py", line 138, in find_adjacencies_command
    network = grnboost2(expression_data=ex_matrix, tf_names=tf_names, verbose=True, client_or_address=args.client_or_address)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/arboretum/algo.py", line 39, in grnboost2
    limit=limit, seed=seed, verbose=verbose)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/arboretum/algo.py", line 105, in diy
    client, shutdown_callback = _prepare_client(client_or_address)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/arboretum/algo.py", line 151, in _prepare_client
    local_cluster = LocalCluster(diagnostics_port=None)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/distributed/deploy/local.py", line 97, in __init__
    services=services)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/distributed/scheduler.py", line 392, in __init__
    **kwargs)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/distributed/node.py", line 37, in __init__
    deserialize=deserialize, io_loop=self.io_loop)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/distributed/core.py", line 122, in __init__
    pc = PeriodicCallback(self._measure_tick, config.get('tick-time', 20))
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/distributed/utils.py", line 1185, in PeriodicCallback
    return tornado.ioloop.PeriodicCallback(callback, callback_time, io_loop)
  File "/datb1/wangrui/software/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 995, in __init__
    if callback_time <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by bramvds** [comment]
Are you sure the expression matrix contains only numerical values?

**Comment by WRui** [comment]
hi, I also try the test matrix (GSE60361) but got the same error, too.  I wonder whether you have any ideals about it ?
Thanks you
Best wishes


fish_cat_wr@sina.cn
 
From: Bram Van de Sande
Date: 2018-03-20 17:31
To: aertslab/pySCENIC
CC: fish_cat; Author
Subject: Re: [aertslab/pySCENIC] error when running pySCENIC (#2)
Are you sure the expression matrix contains only numerical values?

**Comment by tmoerman** [comment]
Probably this is the problem: "(expression_matrix, gene as rows and samples as columns)"
GRNBoost expects samples as rows and genes as columns.

**Comment by WRui** [comment]
Thanks for you reply. Actually, I have seted the '-T' parameters when running the pySCENIC and also have tried to convert the matrix first and then runned the pySCENIC but all meet the same error above.
