### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper

### ISSUE THREAD

**Issue by JohnWang1997** [aertslab/pySCENIC#234]
**Describe the bug**
I tried this command and it runs normally, but an error is reported when outputting the result.

**TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper**

(scenic) root@ecs-88e2:/mnt/data/project/scenic# arboreto_with_multiprocessing.py pbmc10k_filtered_scenic.loom allTFs_hg38.txt --num_workers 16
/mnt/data/anaconda/anaconda3/envs/scenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Loaded expression matrix of 10280 cells and 20292 genes in 2.7222707271575928 seconds...
Loaded 1797 TFs...
/mnt/data/anaconda/anaconda3/envs/scenic/lib/python3.6/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
starting grnboost2 using 16 processes...
100%|███████████████████████████████████████████████████████████████████████████| 20292/20292 [1:44:23<00:00,  3.24it/s]
Done in 6271.0489637851715 seconds.
Traceback (most recent call last):
  File "/mnt/data/anaconda/anaconda3/envs/scenic/bin/arboreto_with_multiprocessing.py", line 130, in <module>
    extension = PurePath(args.output).suffixes
  File "/mnt/data/anaconda/anaconda3/envs/scenic/lib/python3.6/pathlib.py", line 624, in __new__
    return cls._from_parts(args)
  File "/mnt/data/anaconda/anaconda3/envs/scenic/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/mnt/data/anaconda/anaconda3/envs/scenic/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper

**Please complete the following information:**
- pySCENIC version: [0.10.4]
- Installation method: [Conda]
- Run environment: [Jupyter notebook]
- OS: [Ubuntu]
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
name: scenic
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - abseil-cpp=20200225.2=he1b5a44_2
  - arrow-cpp=0.16.0=py36h646bcbe_4
  - aws-c-common=0.4.59=h36c2ea0_1
  - aws-c-event-stream=0.1.6=had2084c_6
  - aws-checksums=0.1.10=h4e93380_0
  - aws-sdk-cpp=1.8.70=h57dc084_1
  - boost-cpp=1.72.0=h8e57a91_0
  - brotli=1.0.9=he1b5a44_3
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py36h5fab9bb_0
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.4.0=h49b9bf7_3
  - grpc-cpp=1.28.1=h8e748ff_2
  - icu=64.2=he1b5a44_1
  - krb5=1.17.2=h926e7f8_0
  - ld_impl_linux-64=2.35.1=hed1e6ac_0
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h72c5cf5_0
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libgomp=9.3.0=h5dbcf3e_17
  - liblapack=3.9.0=3_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libprotobuf=3.11.4=h8b12597_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - lz4-c=1.9.2=he1b5a44_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.19.4=py36h8732dcd_1
  - openssl=1.1.1h=h516909a_0
  - parquet-cpp=1.5.1=1
  - pip=20.3.1=pyhd8ed1ab_0
  - python=3.6.11=hffdb5ce_3_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.4=pyhd8ed1ab_0
  - re2=2020.11.01=h58526e2_0
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py36h9880bd3_2
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.34.0=h74cdb3f_0
  - thrift-cpp=0.13.0=h62aa4f2_2
  - tk=8.6.10=hed695b0_1
  - wheel=0.36.1=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - arboreto==0.1.5
    - attrs==20.3.0
    - boltons==20.2.1
    - cached-property==1.5.2
    - click==7.1.2
    - cloudpickle==1.6.0
    - cytoolz==0.11.0
    - dask==1.0.0
    - decorator==4.4.2
    - dill==0.3.3
    - distributed==1.28.1
    - frozendict==1.2
    - h5py==3.1.0
    - heapdict==1.0.1
    - interlap==0.2.7
    - joblib==0.17.0
    - llvmlite==0.35.0
    - loompy==3.0.6
    - msgpack==1.0.0
    - multiprocessing-on-dill==3.5.0a4
    - networkx==2.5
    - numba==0.52.0
    - numpy-groupies==0.9.13
    - pandas==0.25.3
    - psutil==5.7.3
    - pyarrow==0.16.0
    - pyscenic==0.10.4
    - pyyaml==5.3.1
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - sortedcontainers==2.3.0
    - tblib==1.7.0
    - threadpoolctl==2.1.0
    - toolz==0.11.1
    - tornado==6.1
    - tqdm==4.54.1
    - umap-learn==0.4.6
    - zict==2.0.0
prefix: /mnt/data/anaconda/anaconda3/envs/scenic
...
```

**Comment by JohnWang1997** [comment]
The problem has been solved, and the error was reported because the output path and file name were not specified. The following commands can run normally without error:

**arboreto_with_multiprocessing.py pbmc10k_filtered_scenic.loom allTFs_hg38.txt --num_workers 24 --method grnboost2 --output adj.tsv --seed 777**
