### ISSUE TITLE
ValueError: tuple is not allowed for map key[BUG]

### ISSUE THREAD

**Issue by onmyojiyys** [aertslab/pySCENIC#248]
ValueError: tuple is not allowed for map key

1. Command run when the error occurred:
```python
pyscenic grn
```

2. Error encountered:
```pytb
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2021-01-29 13:39:54,627 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-01-29 13:40:00,514 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
distributed.core - ERROR - tuple is not allowed for map key
Traceback (most recent call last):
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/core.py", line 347, in handle_comm
    msg = yield comm.read()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/comm/tcp.py", line 218, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/comm/utils.py", line 85, in from_frames
    res = _from_frames()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/comm/utils.py", line 71, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Traceback (most recent call last):
  File "/Public/Software/conda_env/pyscenic/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 470, in main
    args.func(args)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 74, in find_adjacencies_command
    network = method(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client, seed=args.seed)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/arboreto/algo.py", line 128, in diy
    seed=seed)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/arboreto/core.py", line 403, in create_graph
    future_tf_matrix = client.scatter(tf_matrix, broadcast=True)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/client.py", line 2071, in scatter
    hash=hash,
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/client.py", line 753, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/utils.py", line 331, in sync
    six.reraise(*error[0])
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/utils.py", line 316, in f
    result[0] = yield future
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/client.py", line 1916, in _scatter
    timeout=timeout,
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/core.py", line 739, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/core.py", line 533, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/comm/tcp.py", line 218, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/comm/utils.py", line 85, in from_frames
    res = _from_frames()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/comm/utils.py", line 71, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

```

**Expected behavior**

**Please complete the following information:**
- pySCENIC version: [0.10.4]
- Installation method: [Pip]
- OS: [Centuos]

```
arboreto==0.1.5
attrs==20.3.0
boltons==20.2.1
cached-property==1.5.2
certifi==2020.12.5
click==7.1.2
cloudpickle==1.6.0
cytoolz==0.11.0
dask==1.0.0
decorator==4.4.2
dill==0.3.3
distributed==1.28.1
frozendict==1.2
h5py==3.1.0
HeapDict==1.0.1
interlap==0.2.7
joblib==1.0.0
llvmlite==0.35.0
loompy==3.0.6
msgpack==1.0.2
multiprocessing-on-dill==3.5.0a4
networkx==2.5
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1590117745635/work
numpy==1.19.5
numpy-groupies==0.9.13
pandas==0.25.3
psutil==5.8.0
pyarrow==0.16.0
pynndescent==0.5.1
pyscenic @ file:///Public/Software/conda_env/pySCENIC/pySCENIC
python-dateutil==2.8.1
pytz==2020.5
PyYAML==5.4.1
scikit-learn==0.24.1
scipy==1.5.4
six==1.15.0
sortedcontainers==2.3.0
tblib==1.7.0
threadpoolctl==2.1.0
toolz==0.11.1
tornado==6.1
tqdm==4.56.0
umap-learn==0.5.0
zict==2.0.0
```

**Comment by cflerin** [comment]
This should be fixed in the new release (pySCENIC `0.11.0`, Arboreto `0.1.6`), can you try updating to the latest version (preferably a fresh install to update all other packages).
