### ISSUE TITLE
cannot install new version of Pyscenic in conda via pip or by cloning repo [error]

### ISSUE THREAD

**Issue by deevdevil88** [aertslab/pySCENIC#256]
**Describe the bug**
I am trying to update my current conda env to the latest pyscenic version and it keeps erroring . the error i get is this 

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```
/ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/bin/pip install pyscenic
```

2. Error encountered:

```python
Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8270fr7m
       cwd: /tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/setup.py", line 413, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "/tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/setup.py", line 148, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  ERROR: Command errored out with exit status 1:
   command: /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/setup.py", line 413, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "/tmp/pip-install-_r8rqjs8/numba_fbb78b7b810e4ecaa01896a797db3a31/setup.py", line 148, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed cleaning build dir for numba
  Building wheel for multidict (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/bin/python3.7 /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpbryodnvg
       cwd: /tmp/pip-install-_r8rqjs8/multidict_ac66db86a17341e6817746104dba3af3
  Complete output (43 lines):
  *********************
  * Accelerated build *
  *********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/multidict
  copying multidict/_multidict_py.py -> build/lib.linux-x86_64-3.7/multidict
  copying multidict/_abc.py -> build/lib.linux-x86_64-3.7/multidict
  copying multidict/_multidict_base.py -> build/lib.linux-x86_64-3.7/multidict
  copying multidict/__init__.py -> build/lib.linux-x86_64-3.7/multidict
  copying multidict/_compat.py -> build/lib.linux-x86_64-3.7/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  copying multidict/__init__.pyi -> build/lib.linux-x86_64-3.7/multidict
  copying multidict/_multidict.c -> build/lib.linux-x86_64-3.7/multidict
  copying multidict/py.typed -> build/lib.linux-x86_64-3.7/multidict
  creating build/lib.linux-x86_64-3.7/multidict/_multilib
  copying multidict/_multilib/defs.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
  copying multidict/_multilib/dict.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
  copying multidict/_multilib/istr.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
  copying multidict/_multilib/iter.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
  copying multidict/_multilib/pair_list.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
  copying multidict/_multilib/views.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
  running build_ext
  building 'multidict._multidict' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/multidict
  gcc -pthread -B /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/include/python3.7m -c multidict/_multidict.c -o build/temp.linux-x86_64-3.7/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for multidict
  Building wheel for yarl (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/bin/python3.7 /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp9bs0mpfl
       cwd: /tmp/pip-install-_r8rqjs8/yarl_02fb3e0e7eca430aa798dddd8e8c9a7d
  Complete output (38 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_py.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_url.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/__init__.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting.py -> build/lib.linux-x86_64-3.7/yarl
  running egg_info
  writing yarl.egg-info/PKG-INFO
  writing dependency_links to yarl.egg-info/dependency_links.txt
  writing requirements to yarl.egg-info/requires.txt
  writing top-level names to yarl.egg-info/top_level.txt
  reading manifest file 'yarl.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no previously-included files found matching 'yarl/*.html'
  warning: no previously-included files found matching 'yarl/*.so'
  warning: no previously-included files found matching 'yarl/*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'yarl.egg-info/SOURCES.txt'
  copying yarl/__init__.pyi -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.c -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.pyi -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.pyx -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/py.typed -> build/lib.linux-x86_64-3.7/yarl
  running build_ext
  building 'yarl._quoting_c' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/yarl
  gcc -pthread -B /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/include/python3.7m -c yarl/_quoting_c.c -o build/temp.linux-x86_64-3.7/yarl/_quoting_c.o
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for yarl
  Building wheel for cytoolz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_r8rqjs8/cytoolz_e584f25ca6134cccb752a5bdb340a64a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_r8rqjs8/cytoolz_e584f25ca6134cccb752a5bdb340a64a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-osthmfkm
       cwd: /tmp/pip-install-_r8rqjs8/cytoolz_e584f25ca6134cccb752a5bdb340a64a/
  Complete output (54 lines):
  ALERT: Cython not installed.  Building without Cython.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/utils_test.py -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/_version.py -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.7/cytoolz
  creating build/lib.linux-x86_64-3.7/cytoolz/curried
  copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.7/cytoolz/curried
  copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.7/cytoolz/curried
  copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.7/cytoolz/curried
  copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.7/cytoolz
  copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.7/cytoolz
  creating build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.7/cytoolz/tests
  running build_ext
  building 'cytoolz.dicttoolz' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/cytoolz
  gcc -pthread -B /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2/include/python3.7m -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.7/cytoolz/dicttoolz.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
Successfully built pyscenic
Failed to build numba multidict yarl cytoolz
ERROR: Could not build wheels for multidict, yarl which use PEP 517 and cannot be installed directly:
...
```

**Expected behavior**

**Please complete the following information:**
- pySCENIC version: [0.11.0, use `pyscenic -h` at the command line]
- Installation method: [e.g. Conda]
- Run environment: [HPC]
- OS: [e.g. linux]
- package list:

```
packages in environment at /ifs/devel/devika/conda/conda_1_install/envs/pyscenic_2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
python                    3.7.9           hffdb5ce_0_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

Thanks 
Devika

**Comment by deevdevil88** [comment]
I think i got it to work, i had to install the relevant versions for multidict ,yar and cytoolz manually via conda install and then pip install pyscenic worked.

**Comment by cflerin** [comment]
Thanks for pointing this out. The docs should be updated to include the conda instructions.
