### ISSUE TITLE
[BUG] Process `filter` terminated with an error exit status in pySCENIC v0.11.0 nextflow

### ISSUE THREAD

**Issue by dioncst** [aertslab/pySCENIC#260]
**Describe the bug**
 Process `filter` terminated with an error exit status

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```python
nextflow run aertslab/SCENICprotocol -profile docker
```

2. Error encountered:

```pytb
Feb-14 11:22:17.059 [main] DEBUG nextflow.cli.Launcher - $> nextflow run aertslab/SCENICprotocol -profile docker
Feb-14 11:22:17.155 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.10.0
Feb-14 11:22:17.714 [main] DEBUG nextflow.scm.AssetManager - Git config: /root/.nextflow/assets/aertslab/SCENICprotocol/.git/config; branch: master; remote: origin; url: https://github.com/aertslab/SCENICprotocol.git
Feb-14 11:22:17.726 [main] DEBUG nextflow.scm.AssetManager - Git config: /root/.nextflow/assets/aertslab/SCENICprotocol/.git/config; branch: master; remote: origin; url: https://github.com/aertslab/SCENICprotocol.git
Feb-14 11:22:17.801 [main] INFO  nextflow.cli.CmdRun - Launching `aertslab/SCENICprotocol` [naughty_kare] - revision: 37e555c112 [master]
Feb-14 11:22:19.464 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /root/.nextflow/assets/aertslab/SCENICprotocol/nextflow.config
Feb-14 11:22:19.464 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /root/.nextflow/assets/aertslab/SCENICprotocol/nextflow.config
Feb-14 11:22:19.470 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `docker`
Feb-14 11:22:19.537 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [standard, test, singularity, docker]
Feb-14 11:22:19.574 [main] DEBUG nextflow.Session - Session uuid: ac45dcda-f49a-47e0-99d6-e8a0e966f06e
Feb-14 11:22:19.575 [main] DEBUG nextflow.Session - Run name: naughty_kare
Feb-14 11:22:19.575 [main] DEBUG nextflow.Session - Executor pool size: 12
Feb-14 11:22:19.596 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 20.10.0 build 5430
  Created: 01-11-2020 15:14 UTC (23:14 CDT)
  System: Linux 5.4.0-58-generic
  Runtime: Groovy 3.0.5 on OpenJDK 64-Bit Server VM 14.0.2+12-Ubuntu-120.04
  Encoding: UTF-8 (UTF-8)
  Process: 16026@SCENIC [172.31.0.82]
  CPUs: 12 - Mem: 92.8 GB (81.5 GB) - Swap: 0 (0)
Feb-14 11:22:19.609 [main] DEBUG nextflow.Session - Work-dir: /root/Mouse/work [ext2/ext3]
Feb-14 11:22:19.640 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Feb-14 11:22:19.642 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Feb-14 11:22:19.743 [main] DEBUG nextflow.Session - Session start invoked
Feb-14 11:22:20.095 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Feb-14 11:22:20.103 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: filter, cluster, visualizeAUC, preprocess, GRNinference, visualize, integrateOutput, cisTarget, AUCell, pca
Feb-14 11:22:20.225 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.225 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.229 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Feb-14 11:22:20.233 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=12; memory=92.8 GB; capacity=12; pollInterval=100ms; dumpInterval=5m
Feb-14 11:22:20.311 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.311 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.315 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.315 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.318 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.319 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.322 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.322 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.327 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.327 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.332 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.332 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.337 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.337 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.343 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.343 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.347 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Feb-14 11:22:20.347 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Feb-14 11:22:20.355 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Feb-14 11:22:20.356 [main] DEBUG nextflow.Session - Session await
Feb-14 11:22:20.513 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Feb-14 11:22:20.517 [Task submitter] INFO  nextflow.Session - [97/af473a] Submitted process > filter
Feb-14 11:22:24.220 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: filter; status: COMPLETED; exit: 1; error: -; workDir: /root/Mouse/work/97/af473a12243b582602d7d7fecd99f3]
Feb-14 11:22:24.241 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'filter'

Caused by:
  Process `filter` terminated with an error exit status (1)

Command executed:

  filtering-basic.py         --loom_input Mtestes.loom         --loom_filtered filtered.loom         --thr_min_genes 200         --thr_min_cells 3         --thr_n_genes 9000         --thr_pct_mito 0.20

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: If you miss a compact list, please try `print_header`!
  Traceback (most recent call last):
    File "/opt/venv/lib/python3.7/site-packages/sinfo/main.py", line 195, in sinfo
      mod_version = _find_version(mod.__version__)
  AttributeError: module 'importlib_metadata' has no attribute '__version__'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/root/.nextflow/assets/aertslab/SCENICprotocol/bin/filtering-basic.py", line 87, in <module>
      initialFiltering( args )
    File "/root/.nextflow/assets/aertslab/SCENICprotocol/bin/filtering-basic.py", line 28, in initialFiltering
      sc.logging.print_versions()
    File "/opt/venv/lib/python3.7/site-packages/scanpy/logging.py", line 161, in print_versions
      sinfo(dependencies=True)
    File "/opt/venv/lib/python3.7/site-packages/sinfo/main.py", line 198, in sinfo
      mod_version = _find_version(mod.version)
    File "/opt/venv/lib/python3.7/site-packages/sinfo/main.py", line 42, in _find_version
      return mod_version_attr()
  TypeError: version() missing 1 required positional argument: 'distribution_name'

Work dir:
  /root/Mouse/work/97/af473a12243b582602d7d7fecd99f3

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Feb-14 11:22:24.249 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `filter` terminated with an error exit status (1)
Feb-14 11:22:24.252 [main] DEBUG nextflow.Session - Session await > all process finished
Feb-14 11:22:24.253 [Actor Thread 5] DEBUG nextflow.file.SortFileCollector - FileCollector temp dir not removed: null
Feb-14 11:22:24.253 [Actor Thread 8] DEBUG nextflow.file.SortFileCollector - FileCollector temp dir not removed: null
Feb-14 11:22:24.265 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-14 11:22:24.273 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=3.7s; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Feb-14 11:22:24.458 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Feb-14 11:22:24.462 [main] DEBUG nextflow.util.SpuriousDeps - AWS S3 uploader shutdown
Feb-14 11:22:24.466 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

```

**Expected behavior**
This procedure is fine when using pySCENIC version 0.10.4 (docker)

**Please complete the following information:**
- pySCENIC version: 0.11.0
- Installation method: Docker
- Run environment: Nextflow
- OS: ubuntu 20.04

```
...
```

**Comment by cflerin** [comment]
Hi @dioncst ,

Copying part of my answer to #258 that addresses this:

The pySCENIC `0.11.0` container has the newest Scanpy installed, while the default container for SCENICprotocol pipeline (`0.9.18`) has an older version, which I guess is what is causing this error.

One possibie workaround is to use the newer Nextflow pipeline: [VSN Pipelines](https://github.com/vib-singlecell-nf/vsn-pipelines), which has a number of workflows for single cell. The one most equivalent to the SCENICprotocol would be `single_sample_scenic` (you can find a tutorial for this one [here](https://vsn-pipelines-examples.readthedocs.io/en/latest/PBMC10k.html)).

If you really want to use the SCENICprotocol pipeline, it will need to be updated to handle the latest Scanpy version.
