### ISSUE TITLE
OverflowError: cannot serialize a bytes object larger than 4 GiB during AUCell calculation[BUG]

### ISSUE THREAD

**Issue by Ijoanito** [aertslab/pySCENIC#261]
**Describe the bug**
Hi, I kept having this error: 'OverflowError: cannot serialize a bytes object larger than 4 GiB' when I run CLI pyscenic AUCell.
If I used "--num_workers 1", I got this error instead: "ValueError: Index contains duplicate entries, cannot reshape"
Do you have any suggestion how to fixed this error?

**Steps to reproduce the behavior**
1. Command run when the error occurred:
**This is how I run for the GRN and CTX step:**
pyscenic grn combineData_filt.loom /mnt/volume1/crcData/Epithelial/New_norm/SCENIC/cisTarget_databases/allTFs_hg38.txt -o adj_combFile.csv --num_workers 32
pyscenic ctx adj_combFile.csv /mnt/volume1/crcData/Epithelial/New_norm/SCENIC/cisTarget_databases/hg19-500bp-upstream-7species.mc9nr.feather --annotations_fname /mnt/volume1/crcData/Epithelial/New_norm/SCENIC/cisTarget_databases/motifs-v9-nr.hgnc-m0.001-o0.0.tbl --expression_mtx_fname combineData_filt.loom --output reg_combFile_500bp.csv --num_workers 32

For the AUCell, This is the 2 way I run it:
pyscenic aucell adj_combFile.csv reg_combFile_500bp.csv --output pyscenic_output_CombObj_500bp.loom --num_workers 32
or
pyscenic aucell adj_combFile.csv reg_combFile_500bp.csv --output pyscenic_output_CombObj_500bp.loom --num_workers 1

2. Error encountered:
**For pyscenic aucell adj_combFile.csv reg_combFile_500bp.csv --output pyscenic_output_CombObj_500bp.loom --num_workers 32, this is the error message:**
2021-02-14 03:36:32,093 - pyscenic.cli.pyscenic - INFO - Writing results to file.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 470, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 237, in aucell_command
    append_auc_mtx(args.output.name, auc_mtx, signatures, args.seed, args.num_workers)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/cli/utils.py", line 278, in append_auc_mtx
    _, auc_thresholds = binarize(auc_mtx, seed=seed, num_workers=num_workers)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/binarization.py", line 79, in binarize
    thresholds = derive_thresholds(auc_mtx)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/binarization.py", line 77, in derive_thresholds
    thrs = p.starmap( derive_threshold,  [ (auc_mtx, c, seed) for c in auc_mtx.columns ] )
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
OverflowError: cannot serialize a bytes object larger than 4 GiB

**For pyscenic aucell adj_combFile.csv reg_combFile_500bp.csv --output pyscenic_output_CombObj_500bp.loom --num_workers 1 this is the error message:**
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 470, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 230, in aucell_command
    num_workers=args.num_workers)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/aucell.py", line 157, in aucell
    return aucell4r(create_rankings(exp_mtx, seed), signatures, auc_threshold, noweights, normalize, num_workers)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pyscenic/aucell.py", line 102, in aucell4r
    auc_threshold=auc_threshold) for module in tqdm(signatures)]).unstack("Regulon")
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 6393, in unstack
    return unstack(self, level, fill_value)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 412, in unstack
    return _unstack_frame(obj, level, fill_value=fill_value)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 442, in _unstack_frame
    constructor=obj._constructor,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 142, in __init__
    self._make_selectors()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 180, in _make_selectors
    raise ValueError("Index contains duplicate entries, " "cannot reshape")
ValueError: Index contains duplicate entries, cannot reshape

**Expected behavior**
Previously, I have successfully run pyscenic using smaller datasets (~9k genes x 18k cells), currently I am running using ~11K genes x 45K cells and I am stuck with this error. 

**Please complete the following information:**
- pySCENIC version: 0.10.4
- Installation method: pip
- Run environment: CLI
- OS: Ubuntu
- Package versions: 
[environment.txt](https://github.com/aertslab/pySCENIC/files/5977014/environment.txt)

**Comment by Ijoanito** [comment]
I finally found my stupid mistake. So sorry for the trouble.

**Comment by Sayyam-Shah** [comment]
Hi @Ijoanito,

Sorry, I'm experiencing the same error. How did you fix the below error?

Traceback (most recent call last):
  File "/cluster/home/t114108uhn/.local/bin/arboreto_with_multiprocessing.py", line 198, in <module>
    main()
  File "/cluster/home/t114108uhn/.local/bin/arboreto_with_multiprocessing.py", line 184, in main
    total=len(gene_names),
  File "/cluster/home/t114108uhn/.local/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/cluster/tools/software/centos7/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/cluster/tools/software/centos7/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/cluster/tools/software/centos7/python/3.7.2/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/cluster/tools/software/centos7/python/3.7.2/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes

**Comment by 13952196139** [comment]
> I finally found my stupid mistake. So sorry for the trouble.

Hi, I met the same problem with OverflowError: cannot serialize a bytes object larger than 4 GiB recently, could you pleasetell me how did you solve this issue?

**Comment by terry676L** [comment]
Hi, I met the same problem with OverflowError: cannot serialize a bytes object larger than 4 GiB recently, could you pleasetell me how did you solve this issue?
