### ISSUE TITLE
[BUG]tornado.util.TimeoutError: Worker failed to start

### ISSUE THREAD

**Issue by onmyojiyys** [aertslab/pySCENIC#268]
Hi
I am trying to run pyscenic，the error occured. please any advice how we can troubleshoot this?

File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start

1. Command run when the error occurred:
```python
pyscenic grn GSE60361.genes_x_cells.tsv.gz tf --output adjacencies.tsv --num_workers 20 -t
```

2. Error encountered:
```pytb
2021-02-20 17:11:01,033 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-02-20 17:11:11,129 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
distributed.nanny - WARNING - Worker process 8448 was killed by unknown signal
Traceback (most recent call last):
  File "/Public/Software/conda_env/pyscenic/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 470, in main
    args.func(args)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 71, in find_adjacencies_command
    client, shutdown_callback = _prepare_client(args.client_or_address, num_workers=args.num_workers)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/pyscenic/prune.py", line 63, in _prepare_client
    threads_per_worker=1)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/deploy/local.py", line 218, in __init__
    self.start(ip=ip, n_workers=n_workers)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/deploy/local.py", line 256, in start
    self.sync(self._start, **kwargs)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/deploy/local.py", line 249, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/utils.py", line 331, in sync
    six.reraise(*error[0])
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/utils.py", line 316, in f
    result[0] = yield future
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/deploy/local.py", line 284, in _start
    yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/Public/Software/conda_env/pyscenic/lib/python3.6/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-5, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-2, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-20, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-13, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-14, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-4, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-8, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-12, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-15, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-6, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-10, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-16, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-7, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-9, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-11, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-17, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-18, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-19, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-3, started daemon)>
distributed.nanny - WARNING - Worker process 8474 was killed by unknown signal
distributed.nanny - WARNING - Worker process 8461 was killed by unknown signal
distributed.nanny - WARNING - Worker process 8465 was killed by unknown signal
distributed.nanny - WARNING - Worker process 8482 was killed by unknown signal
distributed.nanny - WARNING - Worker process 8485 was killed by unknown signal
```

**Expected behavior**

**Please complete the following information:**
- pySCENIC version: [0.10.0]
- Installation method: [Pip]
- Run environment: [CLI]
- OS: [e.g. Ubuntu]

```
arboreto==0.1.5
attrs==20.3.0
boltons==20.2.1
cached-property==1.5.2
certifi==2020.12.5
click==7.1.2
cloudpickle==1.6.0
colormath==3.0.0
cycler==0.10.0
cytoolz==0.11.0
dask==1.0.0
decorator==4.4.2
dill==0.3.3
distributed==1.28.1
frozendict==1.2
h5py==3.1.0
HeapDict==1.0.1
interlap==0.2.7
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1612898609989/work
kiwisolver==1.3.1
llvmlite==0.35.0
loompy==3.0.6
matplotlib==3.3.4
msgpack==1.0.2
multiprocessing-on-dill==3.5.0a4
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1598210780226/work
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1590117745635/work
numpy==1.19.5
numpy-groupies==0.9.13
pandas==0.25.3
Pillow==8.1.0
psutil==5.8.0
pyarrow==0.16.0
pynndescent==0.5.1
pyparsing==2.4.7
pyscenic @ file:///Public/Software/conda_env/pySCENIC/pySCENIC
python-dateutil==2.8.1
pytz==2020.5
PyYAML==5.4.1
scikit-learn==0.19.1
scipy==1.5.4
seaborn==0.11.1
six==1.15.0
sortedcontainers==2.3.0
spectra==0.0.11
tblib==1.7.0
threadpoolctl @ file:///tmp/tmp79xdzxkt/threadpoolctl-2.1.0-py3-none-any.whl
toolz==0.11.1
tornado==6.0.3
tqdm==4.56.0
umap-learn==0.5.0
zict==2.0.0
```

**Comment by cflerin** [comment]
Hi @onmyojiyys ,

This should be resolved in the latest version `0.11.0`, can you update and try again? There are a number of package updates so it may be best to start from a fresh conda or venv install.
