### ISSUE TITLE
Installation of pyscenic latest versions

### ISSUE THREAD

**Issue by saeedfc** [aertslab/pySCENIC#270]
**Describe the bug**
Cannot install pyscenic==11.0 or pyscenic in conda environment. I made a fresh environemnt to install new version (11.0).
Outside of conda environment also, this is not being possible. I previously had succesfully installed pyscenic 10.4 within a conda environment and have been using without issues.
**Steps to reproduce the behavior**
1. Command run when the error occurred:
```
$ conda activate pyscenic_11.0
(pyscenic_11.0) $ pip install pyscenic==11.0
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pyscenic==11.0 (from versions: 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5)
ERROR: No matching distribution found for pyscenic==11.0
WARNING: You are using pip version 20.2.4; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
(pyscenic_11.0)$ pip install pyscenic
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting pyscenic
  Using cached pyscenic-0.6.5.tar.gz (3.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o9VP2E/pyscenic/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o9VP2E/pyscenic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ugYpgu
         cwd: /tmp/pip-install-o9VP2E/pyscenic/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o9VP2E/pyscenic/setup.py", line 80, in <module>
        install_requires=read_requirements('requirements.txt'),
      File "/tmp/pip-install-o9VP2E/pyscenic/setup.py", line 49, in read_requirements
        with open(fname, 'r', encoding='utf-8') as file:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
```
Now without conda it's still pyscenic 10.0 version if i don't specify the version. Otherwise, it cannot identify 11.0

```
(base) $ pip install pyscenic==11.0
ERROR: Could not find a version that satisfies the requirement pyscenic==11.0
ERROR: No matching distribution found for pyscenic==11.0
(base) $ pip install pyscenic
Requirement already satisfied: pyscenic in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (0.10.0)
Requirement already satisfied: interlap in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (0.2.6)
Requirement already satisfied: scipy in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (1.5.2)
Requirement already satisfied: pandas>=0.20.1 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (1.1.3)
Requirement already satisfied: distributed<2.0.0,>=1.21.6 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (1.28.1)
Requirement already satisfied: umap-learn in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (0.3.10)
Requirement already satisfied: pyyaml in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (5.3.1)
Requirement already satisfied: dask==1.0.0 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (1.0.0)
Requirement already satisfied: attrs in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (20.3.0)
Requirement already satisfied: frozendict in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (1.2)
Requirement already satisfied: tqdm in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (4.51.0)
Requirement already satisfied: numba in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (0.45.1)
Requirement already satisfied: setuptools in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (53.0.0)
Requirement already satisfied: cloudpickle in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (1.6.0)
Requirement already satisfied: numpy in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (1.19.4)
Requirement already satisfied: arboreto in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (0.1.5)
Requirement already satisfied: boltons in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (19.2.0)
Requirement already satisfied: multiprocessing-on-dill in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (3.5.0a4)
Requirement already satisfied: loompy in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (3.0.6)
Requirement already satisfied: pyarrow>=0.11.1 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (0.15.0)
Requirement already satisfied: cytoolz in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (0.11.0)
Requirement already satisfied: networkx in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (2.5)
Requirement already satisfied: llvmlite in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pyscenic) (0.29.0)
Requirement already satisfied: msgpack in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (1.0.0)
Requirement already satisfied: toolz>=0.7.4 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (0.11.1)
Requirement already satisfied: psutil>=5.0 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (5.7.2)
Requirement already satisfied: click>=6.6 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (7.0)
Requirement already satisfied: tblib in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (1.7.0)
Requirement already satisfied: six in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (1.15.0)
Requirement already satisfied: zict>=0.1.3 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (2.0.0)
Requirement already satisfied: tornado>=5 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (6.1)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from distributed<2.0.0,>=1.21.6->pyscenic) (2.2.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pandas>=0.20.1->pyscenic) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from pandas>=0.20.1->pyscenic) (2020.4)
Requirement already satisfied: heapdict in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from zict>=0.1.3->distributed<2.0.0,>=1.21.6->pyscenic) (1.0.1)
Requirement already satisfied: scikit-learn in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from arboreto->pyscenic) (0.23.2)
Requirement already satisfied: numpy-groupies in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from loompy->pyscenic) (0+unknown)
Requirement already satisfied: h5py in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from loompy->pyscenic) (2.10.0)
Requirement already satisfied: dill in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from multiprocessing-on-dill->pyscenic) (0.3.1.1)
Requirement already satisfied: decorator>=4.3.0 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from networkx->pyscenic) (4.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from scikit-learn->arboreto->pyscenic) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages (from scikit-learn->arboreto->pyscenic)
python
```

**Expected behavior**
Install pyscenic 11.0 within the conda environment
**Please complete the following information:**
- pySCENIC version: [e.g. 0.10.0, use `pyscenic -h` at the command line]
- Installation method: Pip
- Run environment: CLI
- OS: Ubuntu
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
$pip freeze
adjustText==0.7.3
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
aniso8601==8.0.0
anndata==0.6.22.post1
annoy==1.16.3
aplus==0.11.0
appdirs==1.4.4
arboreto==0.1.5
argh==0.26.2
argon2-cffi @ file:///tmp/build/80754af9/argon2-cffi_1596828452693/work
asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
astroid @ file:///tmp/build/80754af9/astroid_1592495881661/work
astropy==4.0.2
async-generator==1.10
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1596578164842/work
Babel @ file:///tmp/build/80754af9/babel_1605108370292/work
backcall==0.2.0
backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1605305165209/work
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1601924105527/work
bibble==0.0.2
biopython==1.78
bitarray @ file:///tmp/build/80754af9/bitarray_1605065136653/work
bkcharts==0.2
bleach @ file:///tmp/build/80754af9/bleach_1600439572647/work
bokeh @ file:///tmp/build/80754af9/bokeh_1603297847301/work
boltons==19.2.0
boto==2.49.0
boto3 @ file:///tmp/build/80754af9/boto3_1606144295993/work
botocore @ file:///tmp/build/80754af9/botocore_1605995380962/work
Bottleneck==1.3.2
bqplot==0.12.3
branca==0.3.1
brotlipy==0.7.0
cachetools @ file:///tmp/build/80754af9/cachetools_1596822027882/work
cellxgene==0.14.1
certifi==2020.11.8
cffi==1.14.0
chardet @ file:///tmp/build/80754af9/chardet_1605303159953/work
Click==7.0
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
clyent==1.2.2
cmake==3.17.2
colorama @ file:///tmp/build/80754af9/colorama_1603211150991/work
conda==4.9.2
conda-build==3.18.8
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1603018138503/work
conda-verify==3.4.2
contextlib2==0.6.0.post1
cryptography @ file:///tmp/build/80754af9/cryptography_1605544449973/work
cycler==0.10.0
Cython @ file:///tmp/build/80754af9/cython_1605457613176/work
cytoolz==0.11.0
dask==1.0.0
decorator==4.4.2
defusedxml==0.6.0
Deprecated==1.2.10
diff-match-patch @ file:///tmp/build/80754af9/diff-match-patch_1594828741838/work
dill==0.3.1.1
distlib==0.3.1
distributed==1.28.1
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
fastobo==0.7.2
filelock==3.0.12
flake8 @ file:///tmp/build/80754af9/flake8_1601911421857/work
Flask==1.1.2
Flask-Caching==1.8.0
Flask-Compress==1.4.0
Flask-Cors==3.0.8
Flask-RESTful==0.3.8
flatbuffers==1.11
frozendict==1.2
fsspec @ file:///tmp/build/80754af9/fsspec_1602684995936/work
future==0.18.2
get-version==2.1
gevent @ file:///tmp/build/80754af9/gevent_1601397565838/work
glob2==0.7
gmpy2==2.0.8
graphtools==1.5.2
greenlet @ file:///tmp/build/80754af9/greenlet_1600873995270/work
h5py==2.10.0
HeapDict==1.0.1
html5lib @ file:///tmp/build/80754af9/html5lib_1593446221756/work
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imageio @ file:///tmp/build/80754af9/imageio_1594161405741/work
imagesize==1.2.0
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
iniconfig @ file:///tmp/build/80754af9/iniconfig_1602780191262/work
interlap==0.2.6
intervaltree @ file:///tmp/build/80754af9/intervaltree_1598376443606/work
ipydatawidgets==4.0.1
ipykernel @ file:///tmp/build/80754af9/ipykernel_1596206598566/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipyleaflet==0.12.2
ipympl @ file:///tmp/build/80754af9/ipympl_1600379468785/work
ipyscales==0.4.0
ipython @ file:///tmp/build/80754af9/ipython_1604101195213/work
ipython-genutils==0.2.0
ipyvolume==0.5.2
ipyvue==1.1.0
ipyvuetify==1.1.1
ipywebrtc==0.5.0
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1601490159889/work
isort @ file:///tmp/build/80754af9/isort_1602603989581/work
itsdangerous==1.1.0
jdcal==1.4.1
jedi @ file:///tmp/build/80754af9/jedi_1592841891421/work
jeepney @ file:///tmp/build/80754af9/jeepney_1606148855031/work
Jinja2==2.11.2
jmespath @ file:///tmp/build/80754af9/jmespath_1594304593830/work
joblib @ file:///tmp/build/80754af9/joblib_1601912903842/work
json5==0.9.5
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1601311786391/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1598884538475/work
jupyter-core @ file:///tmp/build/80754af9/jupyter_core_1606148959479/work
jupyterlab==2.2.6
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///tmp/build/80754af9/jupyterlab_server_1594164409481/work
keyring @ file:///tmp/build/80754af9/keyring_1601490840626/work
kiwisolver @ file:///tmp/build/80754af9/kiwisolver_1604014532738/work
latexcodec==2.0.1
lazy-object-proxy==1.4.3
legacy-api-wrap==1.2
leidenalg==0.7.0
libarchive-c==2.9
llvmlite==0.29.0
locket==0.2.0
loom-viewer==0.32.4
loompy==3.0.6
louvain==0.6.1
lxml==4.5.1
magic-impute==2.0.3
MarkupSafe @ file:///tmp/build/80754af9/markupsafe_1594371495811/work
matplotlib==3.1.3
mccabe==0.6.1
mistune @ file:///tmp/build/80754af9/mistune_1594373098390/work
mkl-fft==1.2.0
mkl-random==1.1.0
mkl-service==2.3.0
mock==4.0.2
more-itertools @ file:///tmp/build/80754af9/more-itertools_1605111547926/work
mpmath==1.1.0
msgpack==1.0.0
MulticoreTSNE==0.1
multipledispatch==0.6.0
multiprocessing-on-dill==3.5.0a4
mypy-extensions==0.4.3
natsort==7.0.1
navigator-updater==0.2.1
nbclient @ file:///tmp/build/80754af9/nbclient_1602783176460/work
nbconvert @ file:///tmp/build/80754af9/nbconvert_1601914821128/work
nbformat @ file:///tmp/build/80754af9/nbformat_1602783287752/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1606153767164/work
networkx @ file:///tmp/build/80754af9/networkx_1598376031484/work
nltk @ file:///tmp/build/80754af9/nltk_1592496090529/work
nose @ file:///tmp/build/80754af9/nose_1594377616924/work
notebook @ file:///tmp/build/80754af9/notebook_1601501580008/work
numba==0.45.1
numexpr==2.7.1
numpy==1.19.4
numpy-groupies==0+unknown
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
olefile==0.46
openpyxl @ file:///tmp/build/80754af9/openpyxl_1598113097404/work
packaging==20.4
pandas @ file:///tmp/build/80754af9/pandas_1602088128026/work
pandocfilters @ file:///tmp/build/80754af9/pandocfilters_1605120451932/work
parso==0.7.0
partd==1.1.0
path @ file:///tmp/build/80754af9/path_1596907209691/work
pathlib2 @ file:///tmp/build/80754af9/pathlib2_1594380969706/work
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1594384075987/work
Pillow @ file:///tmp/build/80754af9/pillow_1603822253009/work
pkginfo==1.6.1
plotly==2.7.0
pluggy==0.13.1
ply==3.11
progressbar2==3.37.1
prometheus-client==0.8.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
psutil @ file:///tmp/build/80754af9/psutil_1598370249042/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1605560620615/work/dist/ptyprocess-0.6.0-py2.py3-none-any.whl
py @ file:///tmp/build/80754af9/py_1593446248552/work
pyarrow==0.15.0
pybtex==0.22.2
pycairo==1.19.1
pycodestyle==2.6.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycrypto==2.6.1
pycurl==7.43.0.5
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1598885001695/work
pyflakes==2.2.0
Pygments @ file:///tmp/build/80754af9/pygments_1604103097372/work
PyGSP==0.5.1
pylint @ file:///tmp/build/80754af9/pylint_1598624038450/work
pyodbc===4.0.0-unsupported
PyOpenGL==3.1.1a1
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1605545627475/work
pyparsing==2.4.7
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1600141707582/work
pysam==0.15.3
pyscenic==0.10.0
PySocks @ file:///tmp/build/80754af9/pysocks_1594394576006/work
pytest==0.0.0
pytest-runner==5.2
python-dateutil==2.8.1
python-igraph==0.8.0
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///tmp/build/80754af9/python-language-server_1600454544709/work
python-utils==2.4.0
pythreejs==2.1.1
pytz @ file:///tmp/build/80754af9/pytz_1606604771399/work
PyWavelets @ file:///tmp/build/80754af9/pywavelets_1601658308664/work
pyxdg @ file:///tmp/build/80754af9/pyxdg_1603822279816/work
PyYAML==5.3.1
pyzmq==19.0.2
QDarkStyle==2.8.1
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1602272867890/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1600870028330/work
QtPy==1.9.0
regex @ file:///tmp/build/80754af9/regex_1602786662515/work
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
retrying==1.3.3
rope @ file:///tmp/build/80754af9/rope_1602264064449/work
Rtree==0.9.4
ruamel-yaml==0.15.87
s3fs==0.4.2
s3transfer @ file:///tmp/build/80754af9/s3transfer_1594420368108/work
scanpy==1.6.0
scikit-image==0.17.2
scikit-learn @ file:///tmp/build/80754af9/scikit-learn_1598376882706/work
scipy @ file:///tmp/build/80754af9/scipy_1597686620742/work
scprep==1.0.5.post2
scrublet==0.2.1
scvelo==0.2.2
seaborn @ file:///tmp/build/80754af9/seaborn_1600553570093/work
SecretStorage @ file:///tmp/build/80754af9/secretstorage_1594419219833/work
Send2Trash==1.5.0
setuptools-scm==3.5.0
simplegeneric==0.8.1
sinfo==0.3.1
singledispatch @ file:///tmp/build/80754af9/singledispatch_1602523705405/work
six @ file:///tmp/build/80754af9/six_1605205313296/work
snowballstemmer==2.0.0
sortedcollections==1.2.1
sortedcontainers==2.2.2
soupsieve==2.0.1
Sphinx @ file:///tmp/build/80754af9/sphinx_1597428793432/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport @ file:///tmp/build/80754af9/sphinxcontrib-websupport_1597081412696/work
spyder @ file:///tmp/build/80754af9/spyder_1599056984254/work
spyder-kernels @ file:///tmp/build/80754af9/spyder-kernels_1599056754119/work
SQLAlchemy @ file:///tmp/build/80754af9/sqlalchemy_1603810416853/work
statsmodels @ file:///tmp/build/80754af9/statsmodels_1602280183240/work
stdlib-list==0.7.0
sympy @ file:///tmp/build/80754af9/sympy_1605119531870/work
tables==3.6.1
tabulate==0.8.7
tasklogger==1.0.0
tblib @ file:///tmp/build/80754af9/tblib_1597928476713/work
terminado==0.9.1
testpath==0.4.4
texttable==1.6.2
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
tifffile==2020.10.1
toml @ file:///tmp/build/80754af9/toml_1592853716807/work
toolz @ file:///tmp/build/80754af9/toolz_1601054250827/work
tornado @ file:///tmp/build/80754af9/tornado_1606942283357/work
tqdm @ file:///tmp/build/80754af9/tqdm_1605303662894/work
traitlets==4.3.3
traittypes==0.2.1
typed-ast==1.4.1
typing==3.7.4.3
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1598376058250/work
ujson @ file:///tmp/build/80754af9/ujson_1602523313803/work
umap-learn==0.3.10
unicodecsv==0.14.1
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
vaex-astro==0.6.1
vaex-core==1.5.0
vaex-distributed==0.3.0
vaex-hdf5==0.5.2
vaex-jupyter==0.4.1
vaex-server==0.2.1
vaex-ui==0.3.0
vaex-viz==0.3.8
-e git+https://github.com/velocyto-team/velocyto.py.git@0963dd2df0ac802c36404e0f434ba97f07edfe4b#egg=velocyto
virtualenv==20.0.29
watchdog @ file:///tmp/build/80754af9/watchdog_1593447306189/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.11.2
wurlitzer @ file:///tmp/build/80754af9/wurlitzer_1594751868473/work
xarray @ file:///tmp/build/80754af9/xarray_1600709862930/work
xlrd==1.2.0
XlsxWriter @ file:///tmp/build/80754af9/xlsxwriter_1602692860603/work
xlwt==1.3.0
xmltodict==0.12.0
yapf @ file:///tmp/build/80754af9/yapf_1593528177422/work
zict==2.0.0
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work
zope.event==4.5.0
zope.interface @ file:///tmp/build/80754af9/zope.interface_1602002440259/work

```

**Comment by cflerin** [comment]
Hi @saeedfc ,

First, it's required to use python 3 (3.6 or 3.7 recommended) and it looks like you are using python 2.

Second, you have the package version wrong, the latest release is `0.11.0` so `pip install pyscenic==0.11.0`. You could also see [this guide](https://github.com/aertslab/SCENICprotocol/blob/master/docs/installation.md#conda) for a step-by-step install in Conda.
