### ISSUE TITLE
[BUG] AUCell step fails despite using LOOM v3 file

### ISSUE THREAD

**Issue by c5creative** [aertslab/pySCENIC#271]
**Describe the bug**
AUCell step of pySCENIC 0.10.4 fails due to `AttributeError: 'numpy.ndarray' object has no attribute 'split'` error, despite using V3 loom file.

I posted a comment in https://github.com/aertslab/pySCENIC/issues/105 and *then* realized it was closed. Sorry! Also relevant: https://github.com/aertslab/pySCENIC/issues/112 

**Steps to reproduce the behavior**

1. We use the official 0.10.4 Docker image to create a Singularity container, and use that for running pySCENIC at CLI
2. The loom file was created via loompy 3.0.6, in a Conda env that we setup for this project - this is the file we use as input to the GRN step of pySCENIC:

The loom file looks like a v3 file, so could there be another issue not addressed by #105 (comment)?

```python
loom = lp.connect( f_loom_path_unfilt, mode='r+', validate=False )
loom.attrs.keys()
# ['CreationDate', 'LOOM_SPEC_VERSION']
loom.attrs.LOOM_SPEC_VERSION
# 3.0.0
```

3. Error encountered:

```pytb
2021-02-25 09:03:34,334 - pyscenic.cli.pyscenic - INFO - Writing results to file.
Traceback (most recent call last):
  File "/opt/venv/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 470, in main
    args.func(args)
  File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 237, in aucell_command
    append_auc_mtx(args.output.name, auc_mtx, signatures, args.seed, args.num_workers)
  File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/utils.py", line 312, in append_auc_mtx
    ds.ca[ATTRIBUTE_NAME_REGULONS_AUC] = create_structure_array(auc_mtx)
  File "/opt/venv/lib/python3.7/site-packages/loompy/attribute_manager.py", line 129, in __setitem__
    return self.__setattr__(name, val)
  File "/opt/venv/lib/python3.7/site-packages/loompy/attribute_manager.py", line 149, in __setattr__
    values = loompy.normalize_attr_values(val, compare_loom_spec_version(self.ds._file, "3.0.0") >= 0)
  File "/opt/venv/lib/python3.7/site-packages/loompy/utils.py", line 27, in compare_loom_spec_version
    vf = int("".join(get_loom_spec_version(f).split(".")))
AttributeError: 'numpy.ndarray' object has no attribute 'split'
```

**Expected behavior**

**Please complete the following information:**
- pySCENIC version: 0.10.4
- Installation method: singularity
- Run environment: HPC script
- OS: CentOS7
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
aiohttp==3.7.3
anndata==0.7.5
arboreto==0.1.6
async-timeout==3.0.1
attrs==20.3.0
backcall==0.2.0
bokeh==2.2.3
boltons==20.2.1
cached-property==1.5.2
certifi==2020.6.20
cffi==1.14.5
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
cmake==3.18.4.post1
cycler==0.10.0
cytoolz==0.11.0
dask==2021.2.0
decorator==4.4.2
dill==0.3.3
distributed==2021.2.0
frozendict==1.2
fsspec==0.8.5
get-version==2.1
h5py==3.1.0
HeapDict==1.0.1
idna==2.10
importlib-metadata==3.4.0
interlap==0.2.7
ipykernel==5.4.3
ipython==7.20.0
ipython-genutils==0.2.0
jedi==0.18.0
Jinja2==2.11.3
joblib==1.0.1
jupyter-client==6.1.11
jupyter-core==4.7.1
kiwisolver==1.3.1
legacy-api-wrap==1.2
llvmlite==0.35.0
locket==0.2.1
loompy==3.0.6
louvain==0.7.0
MarkupSafe==1.1.1
matplotlib==3.3.4
msgpack==1.0.2
MulticoreTSNE==0.1
multidict==5.1.0
multiprocessing-on-dill==3.5.0a4
natsort==7.1.1
networkx==2.5
numba==0.52.0
numexpr==2.7.2
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1612952999509/work
numpy-groupies==0.9.13
packaging==20.9
pandas==1.2.2
parso==0.8.1
partd==1.1.0
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
prompt-toolkit==3.0.16
psutil==5.8.0
ptyprocess==0.7.0
pyarrow==0.16.0
pycparser==2.20
Pygments==2.8.0
pynndescent==0.5.2
pyparsing==2.4.7
pyscenic==0.11.0
python-dateutil==2.8.1
python-igraph==0.8.3
pytz==2021.1
PyYAML==5.4.1
pyzmq==22.0.3
requests==2.25.1
scanpy==1.7.0
scikit-learn==0.24.1
scipy==1.6.0
seaborn==0.11.1
sinfo==0.3.1
six==1.15.0
sortedcontainers==2.3.0
statsmodels==0.12.2
stdlib-list==0.8.0
tables==3.6.1
tblib==1.7.0
texttable==1.6.3
threadpoolctl==2.1.0
toolz @ file:///tmp/build/80754af9/toolz_1601054250827/work
tornado==6.1
tqdm==4.56.2
traitlets==5.0.5
typing-extensions==3.7.4.3
umap-learn==0.5.1
urllib3==1.26.3
wcwidth==0.2.5
yarl==1.6.3
zict==2.0.0
zipp==3.4.0
```

**Comment by c5creative** [comment]
Issue resolved, we think. Looks like there was some new caching system that wasn't updating... sigh.

**Comment by lidong123-lang** [comment]
Can you tell me how you solved it?

**Comment by owenwilkins** [comment]
I would also be interested to know how you solved this @c5creative, currently experiencing the same issue using the most recent version of pyscenic and loom v3 files

**Comment by 0106WeiWeiDeng** [comment]
Now there is the same issue! loompy and pyscenic are installed by pip.
