### ISSUE TITLE
error about pyscenic grnboost

### ISSUE THREAD

**Issue by xiexiaowei** [aertslab/pySCENIC#30]
Hi,
When I ran "pyscenic -h", it showed that I have successfully installed this software.
But when I ran "pyscenic grnboost", I met the errors as belows:

2018-12-04 13:46:44,213 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
2018-12-04 13:46:46,673 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
Traceback (most recent call last):
  File "/public/home/xiexiaowei/.local/bin/pyscenic", line 11, in <module>
    sys.exit(main())
  File "/public/home/xiexiaowei/.local/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 356, in main
    args.func(args)
  File "/public/home/xiexiaowei/.local/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 119, in find_adjacencies_command
    client, shutdown_callback = _prepare_client(args.client_or_address, num_workers=args.num_workers)
  File "/public/home/xiexiaowei/.local/lib/python3.6/site-packages/pyscenic/prune.py", line 64, in _prepare_client
    client = Client(local_cluster)
  File "/public/home/bioinfo/software/anaconda3/lib/python3.6/site-packages/distributed/client.py", line 556, in __init__
    dask.set_options(get=self.get)
  File "/public/home/xiexiaowei/.local/lib/python3.6/site-packages/dask/context.py", line 18, in set_options
    raise TypeError("The dask.set_options function has been deprecated.\n"
TypeError: The dask.set_options function has been deprecated.
Please use dask.config.set instead

  Before: with dask.set_options(foo='bar'):
              ...
  After:  with dask.config.set(foo='bar'):

So, what happened and how to solve this problem?
Thanks very much!
xiaowei,

**Comment by cflerin** [comment]
Closing this since the recent updates have hopefully fixed this
