### ISSUE TITLE
Error while running sc.pp.neighbors

### ISSUE THREAD

**Issue by yurasong** [aertslab/pySCENIC#306]
Hello,

I am trying to run pySCENIC on my local, however, when I am running sc.pp.neighbors, it returns those error messages.

>>> sc.pp.neighbors(adata, n_neighbors=15, n_pcs=30)
computing neighbors
    using 'X_pca' with n_pcs = 30
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/audrey/.local/lib/python3.6/site-packages/scanpy/neighbors/__init__.py", line 122, in neighbors
    random_state=random_state,
  File "/home/audrey/.local/lib/python3.6/site-packages/scanpy/neighbors/__init__.py", line 744, in compute_neighbors
    self.n_neighbors,
  File "/home/audrey/.local/lib/python3.6/site-packages/scanpy/neighbors/__init__.py", line 347, in _compute_connectivities_umap
    from umap.umap_ import fuzzy_simplicial_set
  File "/home/audrey/.local/lib/python3.6/site-packages/umap/umap_.py", line 51, in <module>
    from umap.spectral import spectral_layout
  File "/home/audrey/.local/lib/python3.6/site-packages/umap/spectral.py", line 4, in <module>
    import numba.targets
ModuleNotFoundError: No module named 'numba.targets'

Here is the information of modules which I imported on python
> scanpy==1.5.0 anndata==0.7.6 numpy==1.19.5 scipy==1.5.4 pandas==1.1.5 scikit-learn==0.24.1 statsmodels==0.11.1 python-igraph==0.8.2 louvain==0.6.0

Also, this is the information of my local computer
> Ubuntu 18.04
> Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
> [GCC 8.4.0] on linux

Thanks in advance,

Best,

**Comment by c5creative** [comment]
Tip: Using Docker version of pySCENIC is a solution for avoiding dependency headaches.

However, have you tried `conda install numba` (if using conda) or `pip install numba'? The `ModuleNotFoundError: No module named 'numba.targets'` looks like numba isn't installed... try to install it, and then open a console and test that it's installed. If it is and you're still getting that error, have a look at the Docker approach. We gave up on "building" pySCENIC from its parts.

**Comment by yurasong** [comment]
Hi, I re-installed numba and it works! Thanks :D
