### ISSUE TITLE
Problems with export2loom

### ISSUE THREAD

**Issue by mdurante1** [aertslab/pySCENIC#32]
Hi,

I have followed the tutorial that you provided for export2loom (https://github.com/aertslab/pySCENIC/blob/master/notebooks/pySCENIC%20-%20Create%20loom%20file.ipynb) but I am still having some issues getting this to work. I have made sure all of my names (i.e. gene symbols, cell annotations, sample IDs, ...) are simple strings. Can you provide any insight into what is going wrong? It would be very helpful if you could make the resources available from the Zeisel et al dataset that you use in the notebook so I can test out my installation on directly compare to my input files. Thank you!

Best,
Michael

```
/nethome/mdurante/.local/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "exportloom.py", line 31, in <module>
    export2loom(exp_mtx, regulons, annotations, LOOM_FILE)
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/pyscenic/export.py", line 75, in export2loom
    columns=['0']).replace(cell_annotations).replace(name2idx)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3798, in replace
    method=method)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5802, in replace
    limit=limit, regex=regex)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3798, in replace
    method=method)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5851, in replace
    regex=regex)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 3739, in replace_list
    masks = [comp(s) for i, s in enumerate(src_list)]
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 3739, in <listcomp>
    masks = [comp(s) for i, s in enumerate(src_list)]
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 3737, in comp
    return _maybe_compare(values, getattr(s, 'asm8', s), operator.eq)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 5165, in _maybe_compare
    b=type_names[1]))
TypeError: Cannot compare types 'ndarray(dtype=float64)' and 'str'
```

**Comment by bramvds** [comment]
Dear Michael,

Best on the error message I can infer that the dictionary you provide as an input for the cell_annotations parameter to export2loom is of incorrect type. It should be a ```Mapping[str, str]``` while in your case there is at least one entry that maps to float64. I advice you to run the following code on you dictionary:

```
cell_annotations_incorrect  = {'id1': 65.0, 'id2': 'type2'}
cell_annotations_correct = { k: str(v) for k,v in cell_annotations_incorrect.items() }
```

Hope this helps.

Kindest regards,
Bram

**Comment by mdurante1** [comment]
Hi Bram,

Thank you for your prompt response. I ran the code on the dictionary and re-ran the export2loom() function and it is providing the same error. Do you have any other thoughts on what could be causing this? I have provided the first three entries in the dictionary before and after I run your code.

Best regards,
Michael

```
>>> glance(annotations)
{'ACTTGTTGTGTGTGCC-outs_UMM062': 'outs_UMM062', 'CCCATACGTCTGCGGT-outs_UMM065': 'outs_UMM065', 'GGGCATCTCTTAACCT-outs_UMM062': 'outs_UMM062'}
>>> annotations_correct = { k: str(v) for k,v in annotations.items() }
>>> glance(annotations_correct)
{'ACTTGTTGTGTGTGCC-outs_UMM062': 'outs_UMM062', 'CCCATACGTCTGCGGT-outs_UMM065': 'outs_UMM065', 'GGGCATCTCTTAACCT-outs_UMM062': 'outs_UMM062'}
```

**Comment by bramvds** [comment]
Dear Michael,

I updated the example notebook with the following functions to check the validity of the expression matrix and the cell annotation mapping:

```
def is_valid_exp_matrix(mtx):
    return (all(isinstance(idx, str) for idx in mtx.index) 
            and all(isinstance(idx, str) for idx in mtx.columns)
            and (mtx.index.nlevels == 1)
            and (mtx.columns.nlevels == 1))

def is_valid_annotation_mapping(m):
    return (all(isinstance(k, str) for k in m.keys()) 
            and all(isinstance(v, str) for v in m.values()))
```

Kindest regards,
Bram

**Comment by mdurante1** [comment]
Hi Bram,

I have checked the validity of the expression matrix and the cell annotation mapping using your functions but I still receive the error when running the export2loom function. I'm not sure what else could be wrong.

Best,
Michael

```
>>> is_valid_exp_matrix(exp_mtx)
True
>>> is_valid_annotation_mapping(annotations_correct)
True
>>> export2loom(exp_mtx, regulons, annotations_correct, LOOM_FILE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/pyscenic/export.py", line 75, in export2loom
    columns=['0']).replace(cell_annotations).replace(name2idx)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3798, in replace
    method=method)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5802, in replace
    limit=limit, regex=regex)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3798, in replace
    method=method)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5851, in replace
    regex=regex)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 3739, in replace_list
    masks = [comp(s) for i, s in enumerate(src_list)]
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 3739, in <listcomp>
    masks = [comp(s) for i, s in enumerate(src_list)]
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 3737, in comp
    return _maybe_compare(values, getattr(s, 'asm8', s), operator.eq)
  File "/nethome/mdurante/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 5165, in _maybe_compare
    b=type_names[1]))
TypeError: Cannot compare types 'ndarray(dtype=float64)' and 'str'
```

**Comment by bramvds** [comment]
Dear Michael,

I just made sure that the example notebook is self-contained: it uses datasets also available in this repo.

Hope this will help solve your problem,
Bram

**Comment by mdurante1** [comment]
Hi Bram,

Thank you for providing this additional information.

I believe I have overcome this original error but now am encountering another error with h5py.

```
>>> export2loom(exp_mtx, regulons, annotations_correct, LOOM_FILE,compress=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/pyscenic/export.py", line 161, in export2loom
    file_attrs=general_attrs)
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/loompy/loompy.py", line 838, in create
    ds.ca[key] = vals
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/loompy/attribute_manager.py", line 111, in __setitem__
    return self.__setattr__(name, val)
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/loompy/attribute_manager.py", line 135, in __setattr__
    self.ds._file[a + name] = values  # TODO: for 2D arrays, use block compression along columns/rows
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 301, in __setitem__
    ds = self.create_dataset(None, data=obj, dtype=base.guess_dtype(obj))
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 116, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/nethome/mdurante/miniconda3/envs/py36/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1611, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1655, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1568, in h5py.h5t._c_compound
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1688, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```
