### ISSUE TITLE
The bug showing into the pyscenic

### ISSUE THREAD

**Issue by honghh2018** [aertslab/pySCENIC#327]
Hi Developer,
      In my case, i found the error displaying below.
      It seem like that the  zero occurred in the divide. Why the data that i run would be prompt this error ?
how can i recorrect this issue?
Hope hearing from you the appropriate advices.
Best
Hanhuihong

    /home/jupyter20200827/lib/python3.7/site-packages/pyscenic/diptest.py:30: RuntimeWarning: divide by zero encountered in true_divide
divide by zero encountered in true_divide
  slopes = (work_cdf[1:] - work_cdf[0]) / distances
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/binarization.py", line 52, in derive_threshold
    if not isbimodal(data, method):
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/binarization.py", line 43, in isbimodal
    _, pval, _ = diptst(np.msort(data))
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/diptest.py", line 53, in diptst
    d, (_, idxs, left, _, right, _) = dip_fn(dat, is_hist)
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/diptest.py", line 115, in dip_fn
    xl = left_touchpoints[d_left == left_diffs][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/nas1/Data/PipeLine/Other/PyScenic/bin/FindTfRegulon.py", line 116, in <module>
    binary_mtx, auc_thresholds = binarize(auc_mtx, num_workers = 15)
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/binarization.py", line 79, in binarize
    thresholds = derive_thresholds(auc_mtx)
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/binarization.py", line 77, in derive_thresholds
    thrs = p.starmap( derive_threshold,  [ (auc_mtx, c, seed) for c in auc_mtx.columns ] )
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/binarization.py", line 52, in derive_threshold
    if not isbimodal(data, method):
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/binarization.py", line 43, in isbimodal
    _, pval, _ = diptst(np.msort(data))
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/diptest.py", line 53, in diptst
    d, (_, idxs, left, _, right, _) = dip_fn(dat, is_hist)
  File "/home/sy/miniconda3/envs/jupyter20200827/lib/python3.7/site-packages/pyscenic/diptest.py", line 115, in dip_fn
    xl = left_touchpoints[d_left == left_diffs][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by honghh2018** [comment]
Can anyone hear from this issue?

**Comment by honghh2018** [comment]
Hi @All
I try the another data can be run pass, but this data can not be work. 
How can i preprocess this data before i running the pyscenic?
Any advices would  be appreciated.
Best

**Comment by cflerin** [comment]
It's hard to help since you haven't included the version, package info, or command that you're running. Do you have empty columns or rows in your matrix?

**Comment by cflerin** [comment]
> I found the failure reason myself. I try to filter all zero line in matrix by rowSums, consequently, it can work well.

Good. It's essential to remove rows/columns with all zero entries.
