### ISSUE TITLE
Error in modules_from_adjancies

### ISSUE THREAD

**Issue by rb56** [aertslab/pySCENIC#329]
Hi, I'm trying to run 
modules = list(modules_from_adjacencies(adj, exp_mtx_qc))
 and have an error on the output. I don't think I understand very well on where the error might be.
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

2021-09-27 11:18:54,356 - pyscenic.cli.pyscenic - INFO - Creating modules.

2021-09-27 11:18:56,275 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-09-27 11:21:09,101 - pyscenic.utils - INFO - Calculating Pearson correlations.
Traceback (most recent call last):
  File "/Users/rithika/miniconda3/envs/arb/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/Users/rithika/miniconda3/envs/arb/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 675, in main
    args.func(args)
  File "/Users/rithika/miniconda3/envs/arb/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 201, in prune_targets_command
    modules = adjacencies2modules(args)
  File "/Users/rithika/miniconda3/envs/arb/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 139, in adjacencies2modules
    keep_only_activating=(args.all_modules != "yes"),
  File "/Users/rithika/miniconda3/envs/arb/lib/python3.7/site-packages/pyscenic/utils.py", line 298, in modules_from_adjacencies
    ), f"Found {len(unique_adj_genes)} genes present in the network (adjacencies) output, but missing from the expression matrix. Is this a different gene expression matrix?"
AssertionError: Found 2920 genes present in the network (adjacencies) output, but missing from the expression matrix. Is this a different gene expression matrix?

**Comment by cflerin** [comment]
Hi @rb56 ,

I think this error is pretty clear:
```
AssertionError: Found 2920 genes present in the network (adjacencies) output, but missing from the expression matrix. Is this a different gene expression matrix?
```
It seems that you generated the network from a different gene expression matrix than the one you are currently using for this command. This will cause weird errors downstream so we implemented this check. So you need to use the same expression matrix for this step, or else re-run the network inference.
