### ISSUE TITLE
[BUG] pyscenic grn crashes with: Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.

### ISSUE THREAD

**Issue by mcsimenc** [aertslab/pySCENIC#335]
**Describe the bug**
Hi, looking forward to working with pySCENIC. I have encountered an error with the GRNBoost step that I don't understand.

I am working with a loom file exported from a R Seurat object, and it loads into SCope properly.

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```
pyscenic grn \
         --num_workers 20 \
         --output pySCENIC_GRNBoost2.adjacency.tsv \
         --method grnboost2 \
         --cell_id_attribute Celltype \
         Seurat.loom \
         TF.list \
         >pyscenic.grn.out \
         2>pyscenic.grn.err
```

2. Error encountered:

stderr output contains many lines like this:
```
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 4.88 GB -- Worker memory limit: 6.75 GB
```

As it crashes, it outputs these lines:
```
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
Traceback (most recent call last):
  File "/home/msimenc/software/anaconda3/envs/scenic/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 675, in main
    args.func(args)
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 100, in find_adjacencies_command
    expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client, seed=args.seed
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/arboreto/algo.py", line 135, in diy
    .compute(graph, sync=True) \
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/distributed/client.py", line 2859, in compute
    result = self.gather(futures)
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/distributed/client.py", line 1969, in gather
    asynchronous=asynchronous,
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/distributed/client.py", line 838, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/distributed/utils.py", line 351, in sync
    raise exc.with_traceback(tb)
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/distributed/utils.py", line 334, in f
    result[0] = yield future
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/msimenc/software/anaconda3/envs/scenic/lib/python3.6/site-packages/distributed/client.py", line 1828, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ("('infer_partial_network-from-delayed-8fd9e9052d4dc719ed276f193855ceda', 12799)", <Worker 'tcp://127.0.0.1:58658', name: 6, memory: 0, processing: 25387>)

```

Any ideas what went wrong? Thanks

**Please complete the following information:**
- pySCENIC version: 0.11.2
- Installation method: conda
- Run environment: linux script
- OS: CentOS 7
- Package versions:
```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aiohttp                   3.7.4.post0              pypi_0    pypi
alsa-lib                  1.2.3                h516909a_0    conda-forge
anndata                   0.7.6                    pypi_0    pypi
arboreto                  0.1.6                    pypi_0    pypi
arpack                    3.7.0                hdefa2d7_2    conda-forge
async-timeout             3.0.1                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
blosc                     1.21.0               h9c3ff4c_0    conda-forge
bokeh                     2.3.3                    pypi_0    pypi
boltons                   21.0.0                   pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.2               h7f98852_0    conda-forge
ca-certificates           2021.7.5             h06a4308_1
cached-property           1.5.2                    pypi_0    pypi
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
cffi                      1.14.6           py36hd8eec40_1    conda-forge
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.6                    pypi_0    pypi
click                     8.0.1                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
contextvars               2.4                      pypi_0    pypi
ctxcore                   0.1.1                    pypi_0    pypi
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py36h7b6447c_0    anaconda
dask                      2021.3.0                 pypi_0    pypi
dbus                      1.13.18              hb2f20db_0
decorator                 4.4.2                    pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
distributed               2021.3.0                 pypi_0    pypi
expat                     2.4.1                h9c3ff4c_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
frozendict                2.0.6                    pypi_0    pypi
fsspec                    2021.9.0                 pypi_0    pypi
get-version               2.1                      pypi_0    pypi
gettext                   0.21.0               hf68c758_0
glib                      2.68.4               h9c3ff4c_1    conda-forge
glib-tools                2.68.4               h9c3ff4c_1    conda-forge
glpk                      4.65              h9202a9a_1004    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gst-plugins-base          1.18.5               hf529b03_0    conda-forge
gstreamer                 1.18.5               h76c114f_0    conda-forge
h5py                      3.1.0                    pypi_0    pypi
hdf5                      1.12.1          nompi_h2750804_100    conda-forge
heapdict                  1.0.1                    pypi_0    pypi
icu                       68.1                 h58526e2_0    conda-forge
idna                      3.2                      pypi_0    pypi
idna-ssl                  1.1.0                    pypi_0    pypi
immutables                0.16                     pypi_0    pypi
importlib-metadata        4.8.1                    pypi_0    pypi
interlap                  0.2.7                    pypi_0    pypi
jbig                      2.1               h7f98852_2003    conda-forge
jinja2                    3.0.1                    pypi_0    pypi
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py36h2531618_0
krb5                      1.19.2               hcc1bbae_2    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
legacy-api-wrap           1.2                      pypi_0    pypi
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.79.1               h2574ce0_1    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20210714         h7f8727e_0
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.4.2                h9c3ff4c_4    conda-forge
libgcc-ng                 11.2.0               h1d223b6_9    conda-forge
libgfortran-ng            11.2.0               h69a702a_9    conda-forge
libgfortran5              11.2.0               h5c6108e_9    conda-forge
libglib                   2.68.4               h174f98d_1    conda-forge
libgomp                   11.2.0               h1d223b6_9    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libogg                    1.3.5                h27cfd23_1
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.3                 hd57d9b9_0    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0               he4da1e4_9    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxcb                    1.14                 h7b6447c_0
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
llvmlite                  0.36.0           py36h612dafd_4
locket                    0.2.1                    pypi_0    pypi
loompy                    3.0.6                    pypi_0    pypi
louvain                   0.7.0            py36hf105032_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.3.4            py36h06a4308_0
matplotlib-base           3.3.4            py36hd391965_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mock                      4.0.3            py36h5fab9bb_1    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
msgpack                   1.0.2                    pypi_0    pypi
multicore-tsne            0.1_d4ff4aab     py36h706143c_1    conda-forge
multidict                 5.1.0                    pypi_0    pypi
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
mysql-common              8.0.25               ha770c72_2    conda-forge
mysql-libs                8.0.25               hfa10184_2    conda-forge
natsort                   7.1.1                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5.1                    pypi_0    pypi
nspr                      4.30                 h9c3ff4c_0    conda-forge
nss                       3.69                 hb5efdd6_0    conda-forge
numba                     0.53.1           py36h1328434_1    conda-forge
numexpr                   2.7.3            py36h0cdc3f0_0    conda-forge
numpy                     1.19.5           py36hfc0c790_2    conda-forge
numpy-groupies            0.9.14                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.0                     pypi_0    pypi
pandas                    1.1.5            py36h284efc9_0    conda-forge
partd                     1.2.0                    pypi_0    pypi
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    8.3.2            py36h676a545_0    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
psutil                    5.8.0                    pypi_0    pypi
pyarrow                   0.16.0                   pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pynndescent               0.5.4                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py36h5fab9bb_7    conda-forge
pyqt-impl                 5.12.3           py36h7ec31b9_7    conda-forge
pyqt5-sip                 4.19.18          py36hc4f0c31_7    conda-forge
pyqtchart                 5.12             py36h7ec31b9_7    conda-forge
pyqtwebengine             5.12.1           py36h7ec31b9_7    conda-forge
pyscenic                  0.11.2                   pypi_0    pypi
pytables                  3.6.1            py36he0b5dfd_4    conda-forge
python                    3.6.13          hb7a2778_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-igraph             0.9.6            py36h644ed5e_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
qt                        5.12.9               hda022c4_4    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
scanpy                    1.7.2                    pypi_0    pypi
scikit-learn              0.24.2           py36hc89565f_1    conda-forge
scipy                     1.5.3            py36h81d768a_1    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                58.0.4           py36h5fab9bb_2    conda-forge
sinfo                     0.3.4                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0                    pypi_0    pypi
sqlite                    3.36.0               h9cd32fc_2    conda-forge
statsmodels               0.12.2           py36he33b4a0_0    conda-forge
stdlib-list               0.8.0                    pypi_0    pypi
suitesparse               5.10.1               hd8046ac_0    conda-forge
tbb                       2020.3               hfd86e86_0
tblib                     1.7.0                    pypi_0    pypi
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
toolz                     0.11.1                     py_0    anaconda
tornado                   6.1              py36h8f6f2f9_1    conda-forge
tqdm                      4.62.3                   pypi_0    pypi
typing-extensions         3.10.0.2                 pypi_0    pypi
umap-learn                0.5.1                    pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xlrd                      1.2.0                    pypi_0    pypi
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.6.3                    pypi_0    pypi
zict                      2.0.0                    pypi_0    pypi
zipp                      3.5.1                    pypi_0    pypi
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```

**Comment by mcsimenc** [comment]
I must have done something weird when exporting my loom file because I re-exported a loom and it works.

**Comment by chenc327** [comment]
how you solve this problem? it`s so strange...... Please
