### ISSUE TITLE
[BUG]AttributeError: 'numpy.ndarray' object has no attribute 'split'

### ISSUE THREAD

**Issue by vikon72** [aertslab/pySCENIC#368]
**Describe the bug**
when I run the command:pyscenic aucell, I got an error about export loom file.I had run it at aertslab-pyscenic-0.10.0.sif and aertslab-pyscenic-0.11.2.sif.It both got the error.

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```shell
singularity exec aertslab-pyscenic-0.11.2.sif pyscenic aucell raw.loom reg.csv --output pyscenic_output.loom --num_workers 20

2. Error encountered:
<!-- Please specify the **complete** error message (if applicable, otherwise delete this block): -->
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.7/site-packages/loompy/attribute_manager.py", line 129, in __setitem__
    return self.__setattr__(name, val)
  File "/opt/venv/lib/python3.7/site-packages/loompy/attribute_manager.py", line 149, in __setattr__
    values = loompy.normalize_attr_values(val, compare_loom_spec_version(self.ds._file, "3.0.0") >= 0)
  File "/opt/venv/lib/python3.7/site-packages/loompy/utils.py", line 27, in compare_loom_spec_version
    vf = int("".join(get_loom_spec_version(f).split(".")))
AttributeError: 'numpy.ndarray' object has no attribute 'split'

**Expected behavior**
A clear and concise description of what you expected to happen.

**Please complete the following information:**
- pySCENIC version: 0.11.2
- Installation method: Singularity
- Run environment: Shell
- OS: CentOS7.6
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:
<!-- Put your package version list in this code block (if applicable, else delete the block): -->
adjustText==0.7.3
aiohttp==3.7.4
anndata==0.7.5
ansiwrap==0.8.4
appdirs==1.4.4
arboreto==0.1.6
async-generator==1.10
async-timeout==3.0.1
attrs==20.3.0
backcall==0.2.0
black==20.8b1
bleach==3.3.0
bokeh==2.2.3
boltons==20.2.1
cached-property==1.5.2
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
ctxcore==0.1.1
cycler==0.10.0
Cython==0.29.21
cytoolz==0.11.0
dask==2021.2.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
distributed==2021.2.0
entrypoints==0.3
frozendict==1.2
fsspec==0.8.5
get-version==2.1
h5py==3.1.0
HeapDict==1.0.1
idna==2.10
importlib-metadata==3.4.0
interlap==0.2.7
ipykernel==5.4.3
ipython==7.20.0
ipython-genutils==0.2.0
jedi==0.18.0
Jinja2==2.11.3
joblib==1.0.1
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
kiwisolver==1.3.1
legacy-api-wrap==1.2
leidenalg==0.8.3
llvmlite==0.35.0
locket==0.2.1
loompy==3.0.6
louvain==0.7.0
MarkupSafe==1.1.1
matplotlib==3.3.4
mistune==0.8.4
msgpack==1.0.2
MulticoreTSNE==0.1
multidict==5.1.0
multiprocessing-on-dill==3.5.0a4
mypy-extensions==0.4.3
natsort==7.1.1
nbclient==0.5.2
nbconvert==6.0.7
nbformat==5.1.2
nbmerge==0.0.4
nest-asyncio==1.5.1
networkx==2.5
numba==0.52.0
numexpr==2.7.2
numpy==1.20.1
numpy-groupies==0.9.13
packaging==20.9
pandas==1.2.2
pandocfilters==1.4.3
papermill==2.3.2
parso==0.8.1
partd==1.1.0
pathspec==0.8.1
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.1
prompt-toolkit==3.0.15
psutil==5.8.0
ptyprocess==0.7.0
pyarrow==0.16.0
pycparser==2.20
Pygments==2.7.4
pynndescent==0.5.2
pyparsing==2.4.7
pyrsistent==0.17.3
pyscenic==0.11.2
python-dateutil==2.8.1
python-igraph==0.8.3
pytz==2021.1
PyYAML==5.4.1
pyzmq==22.0.2
regex==2020.11.13
requests==2.25.1
scanpy==1.7.2
scikit-learn==0.24.1
scipy==1.6.0
seaborn==0.11.1
sinfo==0.3.1
six==1.15.0
sklearn==0.0
sortedcontainers==2.3.0
statsmodels==0.12.2
stdlib-list==0.8.0
tables==3.6.1
tblib==1.7.0
tenacity==6.3.1
testpath==0.4.4
texttable==1.6.3
textwrap3==0.9.2
threadpoolctl==2.1.0
toml==0.10.2
toolz==0.11.1
tornado==6.1
tqdm==4.56.2
traitlets==5.0.5
typed-ast==1.4.2
typing-extensions==3.7.4.3
umap-learn==0.5.1
urllib3==1.26.4
wcwidth==0.2.5
webencodings==0.5.1
yarl==1.6.3
zict==2.0.0
zipp==3.4.0

**Comment by jokedeschildre** [comment]
Hello,

I have the same problem when running pySCENIC with Singularity.

Kind regards,
Joke

**Comment by vikon72** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vikon72** [comment]
Hi,
I solved this problem.It caused by lacking of mainly attrs name in the loom file such as : CellID,nGene,nUMI etc.
I use the follow code to create the loom file，then it's ok.

adata = sc.read_loom( input )
row_attrs = { 
    "Gene": np.array(adata.var.index) ,
}
col_attrs = { 
    "CellID":  np.array(adata.obs.index) ,
    "nGene": np.array( np.sum(adata.X.transpose()>0 , axis=0)).flatten() ,
    "nUMI": np.array( np.sum(adata.X.transpose() , axis=0)).flatten() ,
}

for key,values in adata.obs.items():
    col_attrs[key]=np.array(values)

lp.create( output, adata.X.transpose(), row_attrs, col_attrs )

**Comment by jokedeschildre** [comment]
Thank you, this solved the problem for me too.
