### ISSUE TITLE
[BUG] NameError: name 'gene_names' is not defined

### ISSUE THREAD

**Issue by parkjooyoung99** [aertslab/pySCENIC#396]
**Describe the bug**
when running command below 
I get **NameError: name 'gene_names' is not defined** error

https://github.com/aertslab/pySCENIC/blob/master/src/pyscenic/cli/arboreto_with_multiprocessing.py
following this script, my data is expression matrix with row=cellid, column=genes
<img width="917" alt="image" src="https://user-images.githubusercontent.com/77565848/172411358-30d69370-9539-4ce3-9ae9-0903514d6b92.png">

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```python

arboreto_with_multiprocessing.py 
downsampled.counts.csv allTFs_hg38.txt
--method genie3 
--output adj.tsv 
--num_workers 10 
--seed 777

```

2. Error encountered:

```pytb
"""
Traceback (most recent call last):
  File "C:\Users\pjy_r\miniconda3\envs\pyscenic\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\pjy_r\miniconda3\envs\pyscenic\Scripts\arboreto_with_multiprocessing.py", line 101, in run_infer_partial_network
    target_gene_name = gene_names[target_gene_index]
NameError: name 'gene_names' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pjy_r\miniconda3\envs\pyscenic\Scripts\arboreto_with_multiprocessing.py", line 150, in <module>
    total=len(gene_names),
  File "C:\Users\pjy_r\miniconda3\envs\pyscenic\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\pjy_r\miniconda3\envs\pyscenic\lib\multiprocessing\pool.py", line 748, in next
    raise value
  File "C:\Users\pjy_r\miniconda3\envs\pyscenic\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\pjy_r\miniconda3\envs\pyscenic\Scripts\arboreto_with_multiprocessing.py", line 101, in run_infer_partial_network
    target_gene_name = gene_names[target_gene_index]
NameError: name 'gene_names' is not defined
```

**Expected behavior**
Since i haven't specified  --sparse, 
**gene_names = ex_matrix.columns**
should have been applied.

**Please complete the following information:**
- pySCENIC version: 0.11.2
- Installation method: conda 
- Run environment:  CLI (windows cmd)
- OS: windows
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
# Name                    Version                   Build  Channel
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
anndata                   0.8.0                    pypi_0    pypi
arboreto                  0.1.6                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
blas                      1.0                         mkl
bokeh                     2.3.2                    pypi_0    pypi
boltons                   20.2.1                   pypi_0    pypi
ca-certificates           2022.4.26            haa95532_0    anaconda
cached-property           1.5.2                    pypi_0    pypi
certifi                   2020.6.20                pypi_0    pypi
cffi                      1.15.0                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0    anaconda
ctxcore                   0.1.1                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cytoolz                   0.11.0           py37he774522_0    anaconda
dask                      2021.4.1                 pypi_0    pypi
debugpy                   1.5.1            py37hd77b12b_0    anaconda
decorator                 4.4.2                    pypi_0    pypi
dill                      0.3.3                    pypi_0    pypi
distributed               2021.4.1                 pypi_0    pypi
entrypoints               0.4              py37haa95532_0    anaconda
fonttools                 4.33.3                   pypi_0    pypi
frozendict                2.0.2                    pypi_0    pypi
frozenlist                1.3.0                    pypi_0    pypi
fsspec                    2021.4.0                 pypi_0    pypi
h5py                      3.2.1                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        4.11.4                   pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
interlap                  0.2.7                    pypi_0    pypi
ipykernel                 6.9.1            py37haa95532_0    anaconda
ipython                   7.31.1           py37haa95532_0    anaconda
jedi                      0.18.1           py37haa95532_1    anaconda
jinja2                    2.11.3                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jupyter_client            7.2.2            py37haa95532_0    anaconda
jupyter_core              4.9.2            py37haa95532_0    anaconda
kiwisolver                1.4.2                    pypi_0    pypi
llvmlite                  0.36.0                   pypi_0    pypi
locket                    0.2.1                    pypi_0    pypi
loompy                    3.0.6                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd3eb1b0_2    anaconda
mkl                       2021.4.0           haa95532_640
mkl-fft                   1.3.0                    pypi_0    pypi
mkl-random                1.2.1                    pypi_0    pypi
mkl-service               2.3.0                    pypi_0    pypi
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
msgpack                   1.0.2                    pypi_0    pypi
multicoretsne             0.1                      pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
natsort                   8.1.0                    pypi_0    pypi
nest-asyncio              1.5.5            py37haa95532_0    anaconda
networkx                  2.5.1                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numpy                     1.20.1                   pypi_0    pypi
numpy-base                1.21.5           py37hca35cd5_3
numpy-groupies            0.9.13                   pypi_0    pypi
openssl                   1.1.1n               h2bbff1b_0    anaconda
packaging                 21.3                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0    anaconda
partd                     1.2.0                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pillow                    8.2.0                    pypi_0    pypi
pip                       21.0.1                   pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0    anaconda
psutil                    5.8.0                    pypi_0    pypi
pyarrow                   0.16.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
pynndescent               0.5.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyscenic                  0.11.2                   pypi_0    pypi
python                    3.7.13               h6244533_0
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pywin32                   302              py37h2bbff1b_2    anaconda
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.3.0           py37hd77b12b_2    anaconda
requests                  2.25.1                   pypi_0    pypi
scanpy                    1.9.1                    pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                52.0.0.post20210125          pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sortedcontainers          2.3.0                    pypi_0    pypi
sqlite                    3.38.3               h2bbff1b_0
statsmodels               0.13.2                   pypi_0    pypi
stdlib-list               0.8.0                    pypi_0    pypi
tblib                     1.7.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.1              py37h2bbff1b_0    anaconda
tqdm                      4.60.0                   pypi_0    pypi
traitlets                 5.1.1              pyhd3eb1b0_0    anaconda
typing-extensions         3.10.0.0                 pypi_0    pypi
umap-learn                0.5.1                    pypi_0    pypi
urllib3                   1.26.4                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
wheel                     0.36.2                   pypi_0    pypi
wincertstore              0.2              py37haa95532_2
yarl                      1.6.3                    pypi_0    pypi
zict                      2.0.0                    pypi_0    pypi
zipp                      3.8.0                    pypi_0    pypi

```

**Comment by parkjooyoung99** [comment]
https://github.com/aertslab/pySCENIC/issues/183

Not the same with issue above!
