### ISSUE TITLE
Pyscenic ctx Feather Error

### ISSUE THREAD

**Issue by Sayyam-Shah** [aertslab/pySCENIC#403]
For **questions** about using SCENIC, please use the Discussions: https://github.com/aertslab/SCENIC/discussions/

Create an issue only to report **bugs**.

> Mote that most *errors* are due to the input from the user, and therefore should be treated as questions in the Discussions. Please, only report them as bugs if you are quite certain that they are not behaving as expected.

Hello,

Thank you for making the amazing tool. I ran grn and got my adj.mtx file. However, I'm getting errors upon reading in the ranking dataset with ctx. I ran the below command.

pyscenic ctx adjfem70wi.csv \
    hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather\
    --annotations_fname motifs-v9-nr.hgnc-m0.001-o0.0.tbl \
    --expression_mtx_fname fem70exprmatrix.csv \
    --output regfem70.csv \
    --mask_dropouts \
    --num_workers 5

Traceback (most recent call last):
  File "/cluster/home/.local/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/cluster/home/.local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 677, in main
    args.func(args)
  File "/cluster/home/.local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 215, in prune_targets_command
    dbs = _load_dbs(args.database_fname)
  File "/cluster/home/.local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 176, in _load_dbs
    return [opendb(fname=fname.name, name=get_name(fname.name)) for fname in fnames]
  File "/cluster/home/.local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 176, in <listcomp>
    return [opendb(fname=fname.name, name=get_name(fname.name)) for fname in fnames]
  File "/cluster/home/.local/lib/python3.7/site-packages/ctxcore/rnkdb.py", line 180, in opendb
    return FeatherRankingDatabase(fname, name=name)
  File "/cluster/home/.local/lib/python3.7/site-packages/ctxcore/rnkdb.py", line 110, in __init__
    ct_db_filename=self._fname, engine="pyarrow"
  File "/cluster/home/.local/lib/python3.7/site-packages/ctxcore/ctdb.py", line 175, in init_ct_db
    f'"{ct_db_filename}" is a cisTarget Feather database in Feather v1 format, which is not supported '
ValueError: "hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather" is a cisTarget Feather database in Feather v1 format, which is not supported anymore. Convert them with "convert_cistarget_databases_v1_to_v2.py" (https://github.com/aertslab/create_cisTarget_databases/) to Feather v2 format.

I then converted the ranking database to feather v2 as suggested and got the below error.

Traceback (most recent call last):
  File "/cluster/home/.local/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/cluster/home/.local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 677, in main
    args.func(args)
  File "/cluster/home/.local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 215, in prune_targets_command
    dbs = _load_dbs(args.database_fname)
  File "/cluster/home/.local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 176, in _load_dbs
    return [opendb(fname=fname.name, name=get_name(fname.name)) for fname in fnames]
  File "/cluster/home/.local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 176, in <listcomp>
    return [opendb(fname=fname.name, name=get_name(fname.name)) for fname in fnames]
  File "/cluster/home/.local/lib/python3.7/site-packages/ctxcore/rnkdb.py", line 180, in opendb
    return FeatherRankingDatabase(fname, name=name)
  File "/cluster/home/.local/lib/python3.7/site-packages/ctxcore/rnkdb.py", line 110, in __init__
    ct_db_filename=self._fname, engine="pyarrow"
  File "/cluster/home/.local/lib/python3.7/site-packages/ctxcore/ctdb.py", line 293, in init_ct_db
    ) = get_ct_db_type_from_ct_db_filename(ct_db_filename)
  File "/cluster/home/.local/lib/python3.7/site-packages/ctxcore/ctdb.py", line 104, in get_ct_db_type_from_ct_db_filename
    f'cisTarget database filename "{ct_db_filename}" does not end with '
ValueError: cisTarget database filename "hg38__refseq-r80__500bp_up_and_100bp_down_tssv2.mc9nr.feather" does not end with ".((motifs|tracks)_vs_(regions|genes)|(regions|genes)_vs_(motifs|tracks)).(scores|rankings).feather".

How may I fix this? I got the dataset from the following link: https://resources.aertslab.org/cistarget/

Thank you!

**Comment by pillar-github** [comment]
i have the same problem!

**Comment by cbravo93** [comment]
Hi!

You can just rename the feather v2 databases from `hg38__refseq-r80__500bp_up_and_100bp_down_tssv2.mc9nr.feather` to `hg38__refseq-r80__500bp_up_and_100bp_down_tss.genes_vs_motifs.rankings.feather` and it will work. We will make make the databases compatible with the new pySCENIC/ctxcore versions shortly (feather v2 and ending in genes_vs_motifs.rankings.feather) in https://resources.aertslab.org/cistarget/ ; but this will work with your current dbs without issues.

Cheers!

Carmen

**Comment by zyb1984** [comment]
Does any other reference information need to be updated, such as the motifs.tbl and allTFs_hg38.txt, maybe in other words, how I can choose a suitable list (including *.feather, motif.tbl and TF_list.txt) for this analysis?

**Comment by JoGraesslin** [comment]
Hello.
I want to try out scenic in zebrafish, and I want to use the CIS-BP database file that has been recently used by Liu et al. 2022 https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000057/cisTarget/ as a reference. After updating I got the "does not end with ".((motifs|tracks)vs(regions|genes)|(regions|genes)vs(motifs|tracks)).(scores|rankings).feather"." error message, so I changed the file names accordingly. Now I get another error message: ValueError: cisTarget database "zebrafish_cisTarget/zebrafish_v2_tss.genes_vs_motifs.rankings.feather" claims to contain motifs based on the filename, but contains tracks.
Any idea what is going on? Help would be highly appreciated!
Best,
Jo

**Comment by pennell01** [comment]
> Hi!
> 
> You can just rename the feather v2 databases from `hg38__refseq-r80__500bp_up_and_100bp_down_tssv2.mc9nr.feather` to `hg38__refseq-r80__500bp_up_and_100bp_down_tss.genes_vs_motifs.rankings.feather` and it will work. We will make make the databases compatible with the new pySCENIC/ctxcore versions shortly (feather v2 and ending in genes_vs_motifs.rankings.feather) in https://resources.aertslab.org/cistarget/ ; but this will work with your current dbs without issues.
> 
> Cheers!
> 
> Carmen

Hello! My dear friend, Would you mind sharing your feather v2 databases to me as I had difficulties to convert the version, thanks a lot!

**Comment by CWYuan08** [comment]
@JoGraesslin Hi, I have the same issue, do you have any solution for this? Many thanks!!
