### ISSUE TITLE
[ERROR] GRN step quits with 

### ISSUE THREAD

**Issue by ishwarvh** [aertslab/pySCENIC#436]
I am trying to run GRN on a matrix of ~5000 cells with ~3000 genes per cell. The process ran for 200 hours on 8 workers with 64GB memory and quit without the following error message. 

I couldn't find any other issues with similar problems. Wondering if someone has seen this error and has found a workaround.

Thanks

1. Command run when the error occurred:

```python
!pyscenic grn {f_loom_path_scenic} {f_tfs} -o adj.csv --num_workers 8
...
```

2. Error encountered:

```python
2022-10-19 13:09:32,968 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2022-10-19 13:10:24,745 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
preparing dask client
parsing input
creating dask graph
8 partitions
computing dask graph
2022-10-21 10:18:26,968 - distributed.worker_memory - WARNING - Worker tcp://127.0.0.1:34305 (pid=57245) exceeded 95% memory budget. Restarting...
2022-10-21 10:18:28,402 - distributed.scheduler - ERROR - Couldn't gather keys {'finalize-13bb71709d6726f2f05bbdd881176d56': ['tcp://127.0.0.1:34305']} state: ['waiting'] workers: ['tcp://127.0.0.1:34305']
NoneType: None
2022-10-21 10:18:29,552 - distributed.scheduler - ERROR - Shut down workers that don't have promised key: ['tcp://127.0.0.1:34305'], finalize-13bb71709d6726f2f05bbdd881176d56
NoneType: None
2022-10-21 10:18:29,575 - distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-13bb71709d6726f2f05bbdd881176d56': ('tcp://127.0.0.1:34305',)}
2022-10-21 10:18:29,582 - distributed.nanny - WARNING - Restarting worker
2022-10-21 10:18:47,771 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2022-10-23 10:48:35,601 - distributed.worker_memory - WARNING - Worker tcp://127.0.0.1:42579 (pid=57237) exceeded 95% memory budget. Restarting...
2022-10-23 10:48:37,041 - distributed.scheduler - ERROR - Couldn't gather keys {'finalize-13bb71709d6726f2f05bbdd881176d56': ['tcp://127.0.0.1:42579']} state: ['waiting'] workers: ['tcp://127.0.0.1:42579']
NoneType: None
2022-10-23 10:48:37,834 - distributed.scheduler - ERROR - Shut down workers that don't have promised key: ['tcp://127.0.0.1:42579'], finalize-13bb71709d6726f2f05bbdd881176d56
NoneType: None
2022-10-23 10:48:38,199 - distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-13bb71709d6726f2f05bbdd881176d56': ('tcp://127.0.0.1:42579',)}
2022-10-23 10:48:38,202 - distributed.nanny - WARNING - Restarting worker
2022-10-25 09:58:43,185 - distributed.worker_memory - WARNING - Worker tcp://127.0.0.1:34361 (pid=57225) exceeded 95% memory budget. Restarting...
2022-10-25 09:58:45,254 - distributed.scheduler - ERROR - Couldn't gather keys {'finalize-13bb71709d6726f2f05bbdd881176d56': ['tcp://127.0.0.1:34361']} state: ['waiting'] workers: ['tcp://127.0.0.1:34361']
NoneType: None
2022-10-25 09:58:46,344 - distributed.scheduler - ERROR - Shut down workers that don't have promised key: ['tcp://127.0.0.1:34361'], finalize-13bb71709d6726f2f05bbdd881176d56
NoneType: None
2022-10-25 09:58:46,438 - distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-13bb71709d6726f2f05bbdd881176d56': ('tcp://127.0.0.1:34361',)}
2022-10-25 09:58:46,441 - distributed.nanny - WARNING - Restarting worker
2022-10-25 09:58:46,524 - distributed.worker_memory - WARNING - Worker tcp://127.0.0.1:34361 (pid=618572) exceeded 95% memory budget. Restarting...
2022-10-25 09:58:46,656 - distributed.nanny - WARNING - Restarting worker
2022-10-27 08:14:47,780 - distributed.worker_memory - WARNING - Worker tcp://127.0.0.1:34443 (pid=470867) exceeded 95% memory budget. Restarting...
2022-10-27 08:14:47,965 - distributed.scheduler - ERROR - Couldn't gather keys {'finalize-13bb71709d6726f2f05bbdd881176d56': ['tcp://127.0.0.1:34443']} state: ['memory'] workers: ['tcp://127.0.0.1:34443']
NoneType: None
2022-10-27 08:14:52,507 - distributed.scheduler - ERROR - Shut down workers that don't have promised key: ['tcp://127.0.0.1:34443'], finalize-13bb71709d6726f2f05bbdd881176d56
NoneType: None
2022-10-27 08:14:52,977 - distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-13bb71709d6726f2f05bbdd881176d56': ('tcp://127.0.0.1:34443',)}
2022-10-27 08:14:52,983 - distributed.nanny - WARNING - Restarting worker
not shutting down client, client was created externally
finished
2022-10-27 08:14:56,288 - distributed.nanny - WARNING - Worker process still alive after 3.1999981689453127 seconds, killing

Traceback (most recent call last):
  File "~/p8_scenic/venv_p8_scenic/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "~/p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/pyscenic/cli/pyscenic.py", line 677, in main
    args.func(args)
  File "~p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/pyscenic/cli/pyscenic.py", line 99, in find_adjacencies_command
    network = method(
  File "~p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/arboreto/algo.py", line 39, in grnboost2
    return diy(expression_data=expression_data, regressor_type='GBM', regressor_kwargs=SGBM_KWARGS,
  File "~/p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/arboreto/algo.py", line 134, in diy
    return client \
  File "~/p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/distributed/client.py", line 3272, in compute
    result = self.gather(futures)
  File "~/p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "~p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "~/p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "~/p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "~/p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "~/p8_scenic/venv_p8_scenic/lib/python3.8/site-packages/distributed/client.py", line 2090, in _gather
    raise exc
concurrent.futures._base.CancelledError: finalize-13bb71709d6726f2f05bbdd881176d56
...

```
I expected it to provide me with an adjacency matrix.

**Please complete the following information:**
- pySCENIC version: Single-CEll regulatory Network Inference and Clustering (0.12.0)
- Installation method: Python 
- Run environment: jupyterlab          3.4.3

-----
Python 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
Linux-5.4.0-128-generic-x86_64-with-glibc2.29
- OS: Ubuntu
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
anndata     0.8.0
scanpy      1.9.1
-----
PIL                 7.0.0
apport_python_hook  NA
asttokens           NA
backcall            0.2.0
beta_ufunc          NA
binom_ufunc         NA
cairo               1.16.2
cffi                1.15.0
colorama            0.4.3
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
debugpy             1.6.0
decorator           4.4.2
entrypoints         0.3
executing           0.8.3
h5py                3.7.0
hypergeom_ufunc     NA
igraph              0.9.11
ipykernel           6.13.1
ipython_genutils    0.2.0
jedi                0.18.1
joblib              1.1.0
jupyter_server      1.18.0
kiwisolver          1.4.2
llvmlite            0.38.1
loompy              3.0.7
louvain             0.7.1
matplotlib          3.5.2
mpl_toolkits        NA
natsort             8.1.0
nbinom_ufunc        NA
netifaces           0.10.4
numba               0.55.2
numpy               1.22.4
numpy_groupies      0.9.17
packaging           20.3
pandas              1.4.2
parso               0.8.3
pexpect             4.6.0
pickleshare         0.7.5
pkg_resources       NA
prompt_toolkit      3.0.29
psutil              5.5.1
ptyprocess          0.7.0
pure_eval           0.2.2
pycparser           2.21
pydev_ipython       NA
pydevconsole        NA
pydevd              2.8.0
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pygments            2.12.0
pyparsing           2.4.6
pytz                2022.1
ruamel              NA
scipy               1.8.1
session_info        1.0.0
sitecustomize       NA
six                 1.14.0
sklearn             1.1.1
stack_data          0.2.0
texttable           1.6.4
threadpoolctl       3.1.0
tornado             6.1
traitlets           5.2.2
typing_extensions   NA
wcwidth             NA
yaml                5.3.1
zmq                 23.1.0
-----
IPython             8.4.0
jupyter_client      7.3.4
jupyter_core        4.10.0
jupyterlab          3.4.3
notebook            6.4.12
...
```

**Comment by ghuls** [comment]
Looks like your worker processes get killed all the time. Try on a node with more RAM or less workers.

**Comment by SeppeDeWinter** [comment]
I will close this issue because inactivity. 

Feel free to reopen if you encounter more issues.

Best,

Seppe
