### ISSUE TITLE
Error in grn (about tornado.application)[BUG] [BUG]

### ISSUE THREAD

**Issue by Sa753** [aertslab/pySCENIC#442]
Dear team,

I am using pyscenic version 0.11.2 via CLI . python version 3.8.5 on a dataset of 3000 cells. I am running it on HPC. But I keep getting the error below after the command starts working. I use the following code.

pyscenic grn  file.loom  allTFs_hg38.txt  -o adj.csv --num_workers 20 --sparse 

preparing dask client
parsing input
creating dask graph
10 partitions
computing dask graph

tornado.application - ERROR - Exception in callback <function Worker.__init__.<locals>.<lambda> at 0x2b61524b0700>
Traceback (most recent call last):
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/worker.py", line 708, in <lambda>
    lambda: self.batched_stream.send({"op": "keep-alive"}), 60000
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/batched.py", line 136, in send
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.core - ERROR - 'tcp://127.0.0.1:44971'
Traceback (most recent call last):
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 4826, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://127.0.0.1:44971'
distributed.utils - ERROR - 'tcp://127.0.0.1:44971'
Traceback (most recent call last):
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 3840, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 4926, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 4826, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://127.0.0.1:44971'
distributed.core - ERROR - Exception while handling op register-worker
Traceback (most recent call last):
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 3840, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 4926, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 4826, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://127.0.0.1:44971'
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x2ab979863ee0>, <Task finished name='Task-728287' coro=<BaseTCPListener._handle_stream() done, defined at /data/home/hfx505/.local/lib/python3.8/site-packages/distributed/comm/tcp.py:473> exception=KeyError('tcp://127.0.0.1:44971')>)
Traceback (most recent call last):
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/comm/tcp.py", line 490, in _handle_stream
    await self.comm_handler(comm)
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 3840, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 4926, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 4826, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://127.0.0.1:44971'
tornado.application - ERROR - Exception in callback <function Worker.__init__.<locals>.<lambda> at 0x2b6f6f80a670>
Traceback (most recent call last):
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/worker.py", line 708, in <lambda>
    lambda: self.batched_stream.send({"op": "keep-alive"}), 60000
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/batched.py", line 136, in send
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.utils - ERROR - "('infer_partial_network-from-delayed-0bf9924a965aed3e8d48b9483a39dc68', 2184)"
Traceback (most recent call last):
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/utils.py", line 666, in log_errors
    yield
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 3794, in add_worker
    typename=types[key],
KeyError: "('infer_partial_network-from-delayed-0bf9924a965aed3e8d48b9483a39dc68', 2184)"
distributed.core - ERROR - Exception while handling op register-worker
Traceback (most recent call last):
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/data/home/hfx505/.local/lib/python3.8/site-packages/distributed/scheduler.py", line 3794, in add_worker
    typename=types[key],
KeyError: "('infer_partial_network-from-delayed-0bf9924a965aed3e8d48b9483a39dc68', 2184)"

**Comment by ghuls** [comment]
Can you try pySCENIC 0.12.1?

There are also pySCENIC docker images:
https://pyscenic.readthedocs.io/en/latest/installation.html#docker-podman

**Comment by zhongguodiyidao** [comment]
Hello,bros
Have you used Docker to solve the problem?
Looking forward to your early reply,Thaks!
