### ISSUE TITLE
pyscenic ctx terminates: pyarrow.lib.ArrowInvalid: Not a feather file

### ISSUE THREAD

**Issue by northNomad** [aertslab/pySCENIC#452]
Hi pySCENIC team,

I've downsampled my seurat object to 500 cells and created my loom file using ```SCopeLoomR```.
The ```pyscenic grn``` ran successfully. But when I run ```pyscenic ctx``` the command terminates in the ```calculating regulon``` step.

1. Command run when the error occurred:
```python
pyscenic ctx bm500_GRN_adjancies.csv \
mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings.feather \
 --annotations_fname motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl.txt \
--expression_mtx_fname bm500_test.loom \
 --output bm500_20221220_CTX_regulons.csv \
 --mask_dropouts \
--num_workers 8
```

2. Error encountered:

```pytb
2022-12-20 15:19:36,395 - pyscenic.cli.pyscenic - INFO - Creating modules.

2022-12-20 15:19:37,645 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2022-12-20 15:19:38,492 - pyscenic.utils - INFO - Calculating Pearson correlations.

2022-12-20 15:19:39,307 - pyscenic.utils - WARNING - Note on correlation calculation: the default behaviour for calculating the correlations has changed after pySCENIC verion 0.9.16. Previously, the default was to calculate the correlation between a TF and target gene using only cells with non-zero expression values (mask_dropouts=True). The current default is now to use all cells to match the behavior of the R verision of SCENIC. The original settings can be retained by setting 'rho_mask_dropouts=True' in the modules_from_adjacencies function, or '--mask_dropouts' from the CLI.
        Dropout masking is currently set to [True].

2022-12-20 15:19:52,555 - pyscenic.utils - INFO - Creating modules.

2022-12-20 15:22:09,398 - pyscenic.cli.pyscenic - INFO - Loading databases.

2022-12-20 15:22:09,401 - pyscenic.cli.pyscenic - INFO - Calculating regulons.
[                                        ] | 0% Completed | 21.6s
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\Scripts\pyscenic.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyscenic\cli\pyscenic.py", line 675, in main
    args.func(args)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyscenic\cli\pyscenic.py", line 230, in prune_targets_command
    num_workers=args.num_workers,
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyscenic\prune.py", line 410, in prune2df
    module_chunksize,
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyscenic\prune.py", line 334, in _distributed_calc
    scheduler='processes', num_workers=num_workers if num_workers else cpu_count()
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\base.py", line 283, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\base.py", line 565, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\multiprocessing.py", line 230, in get
    **kwargs
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\local.py", line 487, in get_async
    raise_exception(exc, tb)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc.with_traceback(tb)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyscenic\transform.py", line 301, in modules2df
    [module2df(db, module, motif_annotations, weighted_recovery, False, module2features_func) for module in modules]
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyscenic\transform.py", line 301, in <listcomp>
    [module2df(db, module, motif_annotations, weighted_recovery, False, module2features_func) for module in modules]
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyscenic\transform.py", line 231, in module2df
    db, module, motif_annotations, weighted_recovery=weighted_recovery
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyscenic\transform.py", line 152, in module2features_auc1st_impl
    df = db.load(module)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\ctxcore\rnkdb.py", line 318, in load
    gene_set = self.geneset.intersection(set(gs.genes))
  File "cytoolz\functoolz.pyx", line 475, in cytoolz.functoolz._memoize.__call__
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\ctxcore\rnkdb.py", line 98, in geneset
    return set(self.genes)
  File "cytoolz\functoolz.pyx", line 475, in cytoolz.functoolz._memoize.__call__
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\ctxcore\rnkdb.py", line 296, in genes
    reader = FeatherReader(self._fname)
  File "C:\Users\User\miniconda3\envs\scenic_protocol\lib\site-packages\pyarrow\feather.py", line 40, in __init__
    self.open(source)
  File "pyarrow\feather.pxi", line 83, in pyarrow.lib.FeatherReader.open
  File "pyarrow\error.pxi", line 84, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Not a feather file
```

I re-installed ```pyarrow``` but the issue persisted.

- pySCENIC version: 0.11.2
- Installation method: pip
- Run environment: miniconda3 powershell
- OS: windows
- Package versions: 
```
# packages in environment at C:\Users\User\miniconda3\envs\scenic_protocol:
#
# Name                    Version                   Build  Channel
aiohttp                   3.8.3                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
arboreto                  0.1.6                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
bokeh                     2.3.3                    pypi_0    pypi
boltons                   21.0.0                   pypi_0    pypi
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
certifi                   2021.5.30        py36ha15d459_0    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
colorama                  0.4.5                    pypi_0    pypi
contextvars               2.4                      pypi_0    pypi
ctxcore                   0.1.1                    pypi_0    pypi
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0                   pypi_0    pypi
dask                      2021.3.0                 pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
distributed               2021.3.0                 pypi_0    pypi
freetype                  2.12.1               h546665d_1    conda-forge
frozendict                2.3.4                    pypi_0    pypi
frozenlist                1.2.0                    pypi_0    pypi
fsspec                    2022.1.0                 pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.4                      pypi_0    pypi
idna-ssl                  1.1.0                    pypi_0    pypi
immutables                0.19                     pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
intel-openmp              2022.2.1         h57928b3_19741    conda-forge
interlap                  0.2.7                    pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.1                    pypi_0    pypi
jpeg                      9e                   h8ffe710_2    conda-forge
kiwisolver                1.3.1            py36he95197e_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  13.0.1          default_h81446c8_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libhwloc                  2.8.0                h039e092_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libtiff                   4.3.0                hc4061b1_4    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.36.0                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
loompy                    3.0.7                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.3.4            py36ha15d459_0    conda-forge
matplotlib-base           3.3.4            py36h1abdf75_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msgpack                   1.0.4                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 5.2.0                    pypi_0    pypi
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
networkx                  2.5.1                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numpy                     1.19.5           py36h4b40d73_2    conda-forge
numpy-groupies            0.9.20                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.5.0                hb211442_0    conda-forge
openssl                   1.1.1s               hcfcfb64_1    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.1.5            py36he38d939_0    conda-forge
partd                     1.2.0                    pypi_0    pypi
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pillow                    8.3.2            py36h10c25d6_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
psutil                    5.9.4                    pypi_0    pypi
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pyarrow                   0.16.0                   pypi_0    pypi
pynndescent               0.5.8                    pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py36ha15d459_7    conda-forge
pyqt-impl                 5.12.3           py36he2d232f_7    conda-forge
pyqt5-sip                 4.19.18          py36he2d232f_7    conda-forge
pyqtchart                 5.12             py36he2d232f_7    conda-forge
pyqtwebengine             5.12.1           py36he2d232f_7    conda-forge
pyscenic                  0.11.2                   pypi_0    pypi
python                    3.6.15          h39d44d4_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
qt                        5.12.9               h556501e_6    conda-forge
requests                  2.27.1                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.3            py36h27d303f_1    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                58.0.4           py36ha15d459_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0                    pypi_0    pypi
sqlite                    3.40.0               hcfcfb64_0    conda-forge
statsmodels               0.12.2           py36h14b15b0_0    conda-forge
tbb                       2021.7.0             h91493d7_1    conda-forge
tblib                     1.7.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.1              py36h68aa20f_1    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
umap-learn                0.5.3                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yarl                      1.7.2                    pypi_0    pypi
zict                      2.1.0                    pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge
```

Wondering if anyone has encountered similar issues.
Many thanks in advance -

**Comment by northNomad** [comment]
Seems to be a windows issue. Ran the same code on a linux system and saw no error.
