### ISSUE TITLE
Singularity container fails: "ModuleNotFoundError: No module named 'pandas.io.formats.csvs'"

### ISSUE THREAD

**Issue by tilofrei** [aertslab/pySCENIC#471]
Hello, I am running `pyscenic grn` from the _singularity_ container on a cluster system, but the execution always fails after the _writing results to file_ log message with the following errors (see further down for the detailed message):

2023-04-21 13:35:27,662 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
[..]
ModuleNotFoundError: No module named 'pandas.io.formats.csvs'

I prepared the singularity container as suggested with the commands:
```
docker pull aertslab/pyscenic:0.12.1
singularity build aertslab-pyscenic-0.12.1.sif docker://aertslab/pyscenic:0.12.1
```

Also I checked that peak memory usage of the process was only 60% according to the log file, when running on 1 node with 16 cores and 64gb memory.

Do you have any suggestions how to mitigate the error?

Many thanks
Tilo

**Steps to reproduce the behavior**
1. Command run when the error occurred:
```shell
singularity run -B /work/abc/pyscenic:/data aertslab-pyscenic-0.12.1.sif \
    pyscenic grn \
        --num_workers 16 \
        --transpose \
        -o /data/expr_mat.adjacencies.tsv \
        /data/for_pyscenic_counts.tsv \
        /data/allTFs_mm.txt
```

2. Error encountered:

```shell
RRZ: re-using existing module setup (RRZ_SW_INIT present)
module: unloaded env/system-gcc
module: loaded singularity/3.9.1
INFO:    Converting SIF file to temporary sandbox...

2023-04-20 22:35:08,077 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2023-04-20 22:43:02,307 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
2023-04-21 13:35:27,662 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-21 13:35:27,703 - distributed.nanny - WARNING - Worker process still alive after 3.199998474121094 seconds, killing
2023-04-21 13:35:27,724 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-04-21 13:35:27,725 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-21 13:35:27,725 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-21 13:35:27,726 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-21 13:35:27,726 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-21 13:35:27,727 - distributed.nanny - WARNING - Worker process still alive after 3.1999990844726565 seconds, killing
2023-04-21 13:35:27,728 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-21 13:35:27,728 - distributed.nanny - WARNING - Worker process still alive after 3.1999989318847657 seconds, killing
2023-04-21 13:35:27,729 - distributed.nanny - WARNING - Worker process still alive after 3.1999987792968754 seconds, killing
2023-04-21 13:35:27,730 - distributed.nanny - WARNING - Worker process still alive after 3.1999989318847657 seconds, killing
2023-04-21 13:35:27,730 - distributed.nanny - WARNING - Worker process still alive after 3.1999990844726565 seconds, killing
2023-04-21 13:35:27,731 - distributed.nanny - WARNING - Worker process still alive after 3.1999992370605472 seconds, killing
2023-04-21 13:35:27,732 - distributed.nanny - WARNING - Worker process still alive after 3.1999990844726565 seconds, killing
2023-04-21 13:35:27,734 - distributed.nanny - WARNING - Worker process still alive after 3.1999990844726565 seconds, killing

2023-04-21 13:35:27,989 - pyscenic.cli.pyscenic - INFO - Writing results to file.
preparing dask client
parsing input
creating dask graph
16 partitions
computing dask graph
not shutting down client, client was created externally
finished
Traceback (most recent call last):
  File "/opt/venv/bin/pyscenic", line 33, in <module>
  File "/opt/venv/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 713, in main
  File "/opt/venv/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 119, in find_adjacencies_command
  File "/opt/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
  File "/opt/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 3720, in to_csv
  File "/opt/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
  File "/opt/venv/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1162, in to_csv
ModuleNotFoundError: No module named 'pandas.io.formats.csvs'
INFO:    Cleaning up image...
```

Expected behavior:
I expect the output file `expr_mat.adjacencies.tsv` to be created, but it is empty after the failed run.

- pySCENIC version: 0.12.1
- Installation method: Singularity
- Run environment: HPC script, slurm
- OS: 4.14.295-1.0.41.el7.rrz.x86_64 GNU/Linux

**Comment by ghuls** [comment]
Could you try to remake the image from scratch? Make sure to delete your singularity/apptainer cache dirs.

It seems to work here fine:

Create pySCENIC singularity/apptainer container.
```bash
❯  apptainer build aertslab-pyscenic-0.12.1.sif docker://aertslab/pyscenic:0.12.1                                                                                                                                                                      
INFO:    Environment variable SINGULARITY_DOCKER_PASSWORD is set, but APPTAINER_DOCKER_PASSWORD is preferred                                                                                                                                           
INFO:    Environment variable SINGULARITY_DOCKER_USERNAME is set, but APPTAINER_DOCKER_USERNAME is preferred                                                                                                                                           
INFO:    Starting build...                                                                                                                                                                                                                             
Getting image source signatures                                                                                                                                                                                                                        
Copying blob bdf10448670a done                                                                                                                                                                                                                         
Copying blob 3950cece0b72 done                                                                                                                                                                                                                         
Copying blob a4cc5c9d5acb done                                                                                                                                                                                                                         
Copying blob 126aaa6587b8 done                                                                                                                                                                                                                         
Copying blob 1efc276f4ff9 done                                                                                                                                                                                                                         
Copying blob 0dd06b55ca68 done                                                                                                                                                                                                                         
Copying blob 6c5350e3d2c5 done                                                                                                                                                                                                                         
Copying config 4d37908908 done                                                                                                                                                                                                                         
Writing manifest to image destination                                                                                                                                                                                                                  
Storing signatures                                                                                                                                                                                                                                     
2023/06/13 13:52:49  info unpack layer: sha256:1efc276f4ff952c055dea726cfc96ec6a4fdb8b62d9eed816bd2b788f2860ad7                                                                                                                                        
2023/06/13 13:52:50  info unpack layer: sha256:126aaa6587b8608b62fa39019a891e98460e23bad2d04fb235c4dc8fae2adf3c                                                                                                                                        
2023/06/13 13:52:50  info unpack layer: sha256:0dd06b55ca686f29b26c8a7e051ce98ad571fd6cf22bba07f5cd17e98fd31e13                                                                                                                                        
2023/06/13 13:52:50  info unpack layer: sha256:3950cece0b727ab257c49317871d00f22d2abcb77bcce19ddf86aab5c4d88e21                                                                                                                                        
2023/06/13 13:52:50  info unpack layer: sha256:a4cc5c9d5acbb716756a9c98df6c3bfc698e9606cb2c472b5f18c80758f914d1                                                                                                                                        
2023/06/13 13:52:50  info unpack layer: sha256:bdf10448670abf97146d8665c7fce03af8e4a637babdababd475c8a480d609bb                                                                                                                                        
2023/06/13 13:52:51  info unpack layer: sha256:6c5350e3d2c5e559ecf3271d8fdbb3553a6965c96833cf653784c5f40307543b                                                                                                                                        
INFO:    Creating SIF file...                                                                                                                                                                                                                          
INFO:    Build complete: aertslab-pyscenic-0.12.1.sif  
```

Start python inside container and try to import pandas.io.formats.csvs, which fails for you.

```python
❯  apptainer run aertslab-pyscenic-0.12.1.sif python3
INFO:    Environment variable SINGULARITY_DOCKER_PASSWORD is set, but APPTAINER_DOCKER_PASSWORD is preferred
INFO:    Environment variable SINGULARITY_DOCKER_USERNAME is set, but APPTAINER_DOCKER_USERNAME is preferred
Python 3.10.6 (main, Aug  3 2022, 10:24:07) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas.io.formats.csvs
>>>
```

Another issue could be that your singularity version is old and buggy. Ask your cluster administrators to install newer version of apptainer/singularity. In the past we had issues with outdated singularity binaries on CentOS7 on our HPC cluster. Nowadays the adminstrators keep up with recent versions of apptainer.

```bash
❯  singularity --version
apptainer version 1.1.8-1.el8
```

**Comment by tilofrei** [comment]
Hi, thanks for your further details, I meanwhile used _venv_ to run _pyscenic_ on the cluster and that works great!

```
module load python/3.9.12
python -m venv pyscenic_env/
mkdir $WORK/pyscenic_env
source $WORK/pyscenic_env/bin/activate
pip install pyscenic
```

**Comment by tilofrei** [comment]
PS: Updating singularity to the latest (apptainer) version might also help comparing the release dates:

Apptainer v1.1.8: 04/25/2023
Singularity v3.9.1: 01/18/2022
