### ISSUE TITLE
error when running grnboost2(ex_matrix, tf_names=tf_names, verbose=True)

### ISSUE THREAD

**Issue by sunnyyakima** [aertslab/pySCENIC#48]
Hi

I used my own data, it crashed when running grnboost2(ex_matrix, tf_names=tf_names, verbose=True):
The expression matrix is TPM, not counts.

here are error message:
'infer_data failed for target DUX4' Retry (1/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (2/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (3/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (4/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (5/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (6/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (7/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (8/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (9/10). Failure caused by AssertionError().
'infer_data failed for target DUX4' Retry (10/10). Failure caused by AssertionError().
distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (None, Empty DataFrame
Columns: [TF, target, importance]
Index: [], 'from_delayed')
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nExpected partition of type `DataFrame` but got `NoneType`',)

distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (None, Empty DataFrame
Columns: [TF, target, importance]
Index: [], 'from_delayed')
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nExpected partition of type `DataFrame` but got `NoneType`',)

/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
shutting down client and local cluster
finished
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/arboreto/algo.py", line 135, in diy
    .compute(graph, sync=True) \
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/distributed/client.py", line 2504, in compute
    result = self.gather(futures)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/distributed/client.py", line 1655, in gather
    asynchronous=asynchronous)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/distributed/client.py", line 675, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/distributed/client.py", line 1496, in _gather
    traceback)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/dask/dataframe/utils.py", line 498, in check_meta
    errmsg))
ValueError: Metadata mismatch found in `from_delayed`.

Expected partition of type `DataFrame` but got `NoneType`
>>> /home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process 130230 was killed by unknown signal
distributed.nanny - WARNING - Worker process 130194 was killed by unknown signal
distributed.nanny - WARNING - Worker process 130199 was killed by unknown signal
distributed.nanny - WARNING - Worker process 130207 was killed by unknown signal
distributed.nanny - WARNING - Worker process 130191 was killed by unknown signal
distributed.nanny - WARNING - Worker process 130219 was killed by unknown signal
distributed.nanny - WARNING - Worker process 130213 was killed by unknown signal

**Comment by sunnyyakima** [comment]
It turns out that there are two rows with this gene_id in the expression matrix.
