### ISSUE TITLE
[BUG]pyscenic ctx question！

### ISSUE THREAD

**Issue by zhongguodiyidao** [aertslab/pySCENIC#480]
Dear author,
![image](https://github.com/aertslab/pySCENIC/assets/44579368/acca66f2-df2c-4ea1-8fea-06f61f868642)

Traceback (most recent call last):
  File "/work/home/acp0wc9bsx/miniconda3/envs/pyscenic3.7/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/work/home/acp0wc9bsx/miniconda3/envs/pyscenic3.7/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 713, in main
    args.func(args)
  File "/work/home/acp0wc9bsx/miniconda3/envs/pyscenic3.7/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 254, in prune_targets_command
    save_enriched_motifs(df_motifs, args.output.name)
  File "/work/home/acp0wc9bsx/miniconda3/envs/pyscenic3.7/lib/python3.7/site-packages/pyscenic/cli/utils.py", line 244, in save_enriched_motifs
    regulons = df2regulons(df)
  File "/work/home/acp0wc9bsx/miniconda3/envs/pyscenic3.7/lib/python3.7/site-packages/pyscenic/transform.py", line 503, in df2regulons
    assert not df.empty, "Signatures dataframe is empty!"
AssertionError: Signatures dataframe is empty!

When I execute pyscenic ctx,no result output, and then an error is reported stating that the Signatures dataframe is empty,Is this because of the problem with the feature file I created earlier? The motifToTF file replaces human genes with homologous genes from turtles, and transcription factors are also replaced with homologous genes.

Or, Is it because the number of cells is too small that there is no result? I used the subset function (Seurat) to randomly select 7000 cells from 80000 cells.

Looking forward to your reply!

**Comment by ghuls** [comment]
Do your gene names used in the feather file match the ones from the tsv file and loom file?

**Comment by Fugwaaaa** [comment]
Hello, I also met the same problem as you. How did you sovle it?
