### ISSUE TITLE
Usage cannot be printed after successful installation of pySCENIC

### ISSUE THREAD

**Issue by YangLi-Bio** [aertslab/pySCENIC#496]
**Describe the bug**
I have succeeded to install pySCENIC. However, when I type `pyscenic -h`, error occurrs.

> Mote that most *errors* are due to the input from the user, and therefore should be treated as questions in the Discussions. Please, only report them as bugs if you are quite certain that they are not behaving as expected.

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```pyscenic -h
```

2. Error encountered:

```(scglue) bash-4.2$ pyscenic -h
Traceback (most recent call last):
  File "/users/PAS1475/liyang/.conda/envs/scglue/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/site-packages/pyscenic/cli/pyscenic.py", line 19, in <module>
    from arboreto.algo import genie3, grnboost2
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/site-packages/arboreto/algo.py", line 6, in <module>
    from distributed import Client, LocalCluster
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/site-packages/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/site-packages/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/site-packages/distributed/worker_memory.py", line 55, in <module>
    WorkerDataParameter: TypeAlias = Union[
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/users/PAS1475/liyang/.conda/envs/scglue/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'
```

**Expected behavior**
Usage should be reported.

**Please complete the following information:**
- pySCENIC version: [0.12.1]
- Installation method: [Pip]
- Run environment: [Shell console in conda virtual environment]
- OS: [e.g. Red Hat]
```

**Comment by bbergsneider** [comment]
I'm getting the same error when I run `pyscenic -h` and `pyscenic grn`

My error message is the same as above:
`Traceback (most recent call last):
  File "/home/users/bbergs/.local/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/home/users/bbergs/.local/lib/python3.9/site-packages/pyscenic/cli/pyscenic.py", line 19, in <module>
    from arboreto.algo import genie3, grnboost2
  File "/home/users/bbergs/.local/lib/python3.9/site-packages/arboreto/algo.py", line 6, in <module>
    from distributed import Client, LocalCluster
  File "/home/users/bbergs/.local/lib/python3.9/site-packages/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/home/users/bbergs/.local/lib/python3.9/site-packages/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/home/users/bbergs/.local/lib/python3.9/site-packages/distributed/worker_memory.py", line 55, in <module>
    WorkerDataParameter: TypeAlias = Union[
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'`

Any help on solving this so that I can run pyscenic would be appreciated. Thanks so much!

**Comment by clg12** [comment]
Has there been any progress on this issue? 
Now I'm having the same issue as well. But before a few months, my code was working.

`Traceback (most recent call last):
  File "/home/lyt/anaconda3/envs/pyscenic/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/site-packages/pyscenic/cli/pyscenic.py", line 19, in <module>
    from arboreto.algo import genie3, grnboost2
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/site-packages/arboreto/algo.py", line 6, in <module>
    from distributed import Client, LocalCluster
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/site-packages/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/site-packages/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/site-packages/distributed/client.py", line 118, in <module>
    from distributed.worker import get_client, get_worker, secede
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/site-packages/distributed/worker.py", line 120, in <module>
    from distributed.worker_memory import (
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/site-packages/distributed/worker_memory.py", line 56, in <module>
    WorkerDataParameter: TypeAlias = Union[
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/home/lyt/anaconda3/envs/pyscenic/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'`

Thanks for your answer!
