### ISSUE TITLE
error when running df = prune2df(dbs, modules, MOTIF_ANNOTATIONS_FNAME)

### ISSUE THREAD

**Issue by sunnyyakima** [aertslab/pySCENIC#50]
Here is error message:
Less than 80% of the genes in ZNF606 could be mapped to hg19-tss-centered-10kb-10species. Skipping this module.
Traceback (most recent call last):
  File "run_scenic.py", line 68, in <module>
    df = prune2df(dbs, modules, MOTIF_ANNOTATIONS_FNAME)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/pyscenic/prune.py", line 351, in prune2df
    num_workers, module_chunksize)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/pyscenic/prune.py", line 300, in _distributed_calc
    return create_graph().compute(scheduler='processes', num_workers=num_workers if num_workers else cpu_count())
  File "/home/yu_liu/.local/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/dask/multiprocessing.py", line 192, in get
    raise_exception=reraise, **kwargs)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/dask/local.py", line 459, in get_async
    raise_exception(exc, tb)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/dask/compatibility.py", line 111, in reraise
    raise exc.with_traceback(tb)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/dask/dataframe/utils.py", line 587, in check_meta
    errmsg))
ValueError: Metadata mismatch found in `from_delayed`.

The columns in the computed data do not match the columns in the provided metadata.
 MultiIndex(levels=[['Enrichment'], ['AUC', 'Annotation', 'Context', 'MotifSimilarityQvalue', 'NES', 'OrthologousIdentity', 'RankAtMax', 'TargetGenes']],
           codes=[[0, 0, 0, 0, 0, 0, 0, 0], [0, 4, 3, 5, 1, 2, 7, 6]])
  :MultiIndex(levels=[['Enrichment'], ['AUC', 'Annotation', 'Context', 'MotifSimilarityQvalue', 'NES', 'OrthologousIdentity', 'RankAtMax', 'TargetGenes']],
           codes=[[0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 2, 3, 4, 5, 6, 7]],
           sortorder=0)

**Comment by bramvds** [comment]
Thank you for reporting this. This issue is similar to https://github.com/aertslab/pySCENIC/issues/45 and the following solution was proposed: This seems to be related to the most recent version of dask (v1.1.0), since when I downgrade dask to version 1.0.0 this step works again with no error.

**Comment by grimwoo** [comment]
@bramvds Thanks for your suggestion. but when I downgraded dask to version 1.0.0, I encounter ed "ImportError: cannot import name 'format_bytes'".
Interestingly, I could ```from dask.utils import ensure_dict, format_bytes, funcname```. Could you please help me?

the code:
```
!pyscenic ctx adj.csv \
    {f_db_names} \
    --annotations_fname {f_motif_path} \
    --expression_mtx_fname {f_loom_path_scenic} \
    --output reg.csv \
    --mask_dropouts \
    --num_workers 6
```
the error info:
```
/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Traceback (most recent call last):
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/bin/pyscenic", line 7, in <module>
    from pyscenic.cli.pyscenic import main
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 16, in <module>
    from arboreto.algo import grnboost2, genie3
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/arboreto/algo.py", line 6, in <module>
    from distributed import Client, LocalCluster
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/distributed/__init__.py", line 3, in <module>
    from .actor import Actor, ActorFuture
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/distributed/actor.py", line 7, in <module>
    from .client import Future, default_client
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/distributed/client.py", line 30, in <module>
    from dask.utils import ensure_dict, format_bytes, funcname
ImportError: cannot import name 'format_bytes'
```
