### ISSUE TITLE
[BUG] Installation error

### ISSUE THREAD

**Issue by as7a5** [aertslab/pySCENIC#518]
**Describe the bug**
pyscenic -h errors out after fresh installation via conda.
Seems numpy new version does not include np.object. Only object is there:  
Following steps of installation on anaconda3 (2022.10):

(pyscenic) [root@gn-0012 site-packages]$ pyscenic -h
/gpfs/share/apps/anaconda3/gpu/2022.10/envs/pyscenic/lib/python3.10/site-packages/pyscenic/transform.py:42: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
Traceback (most recent call last):
  File "/gpfs/share/apps/anaconda3/gpu/2022.10/envs/pyscenic/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/gpfs/share/apps/anaconda3/gpu/2022.10/envs/pyscenic/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 26, in <module>
    from pyscenic.prune import _prepare_client, find_features, prune2df
  File "/gpfs/share/apps/anaconda3/gpu/2022.10/envs/pyscenic/lib/python3.10/site-packages/pyscenic/prune.py", line 27, in <module>
    from .transform import (
  File "/gpfs/share/apps/anaconda3/gpu/2022.10/envs/pyscenic/lib/python3.10/site-packages/pyscenic/transform.py", line 42, in <module>
    ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
  File "/gpfs/share/apps/anaconda3/gpu/2022.10/envs/pyscenic/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?
 
**Steps to reproduce the behavior**
1. Command run when the error occurred:

```python
...
```

2. Error encountered:

```pytb
...
```

**Expected behavior**

**Please complete the following information:**
- pySCENIC version: [e.g. 0.10.0, use `pyscenic -h` at the command line]
- Installation method: [e.g. Conda, Pip, Docker, Singularity]
- Run environment: [e.g. Jupyter notebook, CLI, Nextflow, HPC script]
- OS: [e.g. Ubuntu]
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
...
```

**Comment by ghuls** [comment]
Install an older version of numpy: `pip install 'numpy<1.24'`
Or use the latest git version. It has this patched: https://github.com/aertslab/pySCENIC/commit/eaf23eb1fdcaae79b273de56b374b71aa8afde5a

Or use the prebuild Docker/Podman/Singularity/Apptainer images: https://pyscenic.readthedocs.io/en/latest/installation.html#docker-podman

**Comment by liuyifang** [comment]
`pip install git+https://github.com/aertslab/pySCENIC@eaf23eb1fdcaae79b273de56b374b71aa8afde5a`
works for me

**Comment by yuanyuan1206** [comment]
> Install an older version of numpy: `pip install 'numpy<1.24'` Or use the latest git version. It has this patched: [eaf23eb](https://github.com/aertslab/pySCENIC/commit/eaf23eb1fdcaae79b273de56b374b71aa8afde5a)
> 
> Or use the prebuild Docker/Podman/Singularity/Apptainer images: https://pyscenic.readthedocs.io/en/latest/installation.html#docker-podman

it works for me
