### ISSUE TITLE
Unable to run scenic aucell - Nonetype object has no attribute split

### ISSUE THREAD

**Issue by maaraujo10** [aertslab/pySCENIC#526]
1. Command run when the error occurred:
```
pyscenic aucell screen_filtered_scenic.loom  reg.csv --output pyscenic_output.loom --num_workers 12
```

2. Error encountered:
```
File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f5b610f76a0>
Traceback (most recent call last):
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f5b610f76a0>
Traceback (most recent call last):
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f5b610f58a0>
Traceback (most recent call last):
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f5b610f58a0>
Traceback (most recent call last):
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pyscenic/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
...
```

Conda env package versions:
```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alsa-lib                  1.2.10               hd590300_0    conda-forge
anndata                   0.10.4             pyhd8ed1ab_0    conda-forge
anyio                     4.2.0                    pypi_0    pypi
arboreto                  0.1.6                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arpack                    3.8.0           nompi_h0baa96a_101    conda-forge
array-api-compat          1.4.1              pyhd8ed1ab_0    conda-forge
arrow                     1.3.0                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.2.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blas                      1.0                    openblas  
bleach                    6.1.0                    pypi_0    pypi
blosc                     1.21.3               h6a678d5_0  
bokeh                     3.3.3                    pypi_0    pypi
boltons                   23.1.1                   pypi_0    pypi
bottleneck                1.3.5           py311hbed6279_0  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.25.0               hd590300_0    conda-forge
c-blosc2                  2.12.0               h80c7b02_0  
ca-certificates           2023.12.12           h06a4308_0  
cairo                     1.18.0               h3faef2a_0    conda-forge
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0          py311h5eee18b_0  
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
contourpy                 1.2.0           py311hdb19cb5_0  
ctxcore                   0.2.0                    pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
cytoolz                   0.12.2          py311h5eee18b_0  
dask                      2024.1.0                 pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
distributed               2024.1.0                 pypi_0    pypi
exceptiongroup            1.0.4           py311h06a4308_0  
expat                     2.5.0                h6a678d5_0  
fastjsonschema            2.19.1                   pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0  
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                hd3eb1b0_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-anaconda            1                    h8fa9717_0  
fonts-conda-ecosystem     1                    hd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frozendict                2.4.0                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.12.2                pypi_0    pypi
get-annotations           0.1.2              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.78.3               hfc55251_0    conda-forge
glib-tools                2.78.3               hfc55251_0    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
graphite2                 1.3.14               h295c915_1  
gst-plugins-base          1.22.8               h8e1006c_1    conda-forge
gstreamer                 1.22.8               h98fc4e7_1    conda-forge
h5py                      3.10.0                   pypi_0    pypi
harfbuzz                  8.3.0                h3d44ed6_0    conda-forge
hdf5                      1.12.1               h2b7332f_3  
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                      pypi_0    pypi
igraph                    0.10.8               h52253d4_1    conda-forge
importlib-metadata        7.0.1                    pypi_0    pypi
interlap                  0.2.7                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.2.0           py311h06a4308_0  
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-events            0.9.0                    pypi_0    pypi
jupyter-lsp               2.2.2                    pypi_0    pypi
jupyter-server            2.12.5                   pypi_0    pypi
jupyter-server-terminals  0.5.2                    pypi_0    pypi
jupyterlab                4.0.11                   pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.25.2                   pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4           py311h6a678d5_0  
krb5                      1.21.2               h659d440_0    conda-forge
lame                      3.100                h7b6447c_0  
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
leidenalg                 0.10.2                   pypi_0    pypi
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libcap                    2.69                 h0f662aa_0    conda-forge
libclang                  15.0.7          default_hb11cfb5_4    conda-forge
libclang13                15.0.7          default_ha2b6cf4_4    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               hdbd6064_1  
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.4                h6a678d5_0  
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgcrypt                 1.10.3               hd590300_0    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libglib                   2.78.3               h783c2da_0    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libgpg-error              1.47                 h71f35ed_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libllvm14                 14.0.6               hdb19cb5_3  
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.5                h27cfd23_1  
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
libpq                     16.1                 h33b98f1_7    conda-forge
libsndfile                1.2.2                hc60ed4a_1    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libsystemd0               255                  h3516f8a_0    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h7b6447c_0  
libwebp-base              1.3.2                h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.6.0                hd429924_1    conda-forge
libxml2                   2.12.4               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.41.1          py311ha6695c7_0    conda-forge
locket                    1.0.0                    pypi_0    pypi
loompy                    3.0.7                    pypi_0    pypi
louvain                   0.8.1           py311hb755f60_1    conda-forge
lz4                       4.3.3                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
lzo                       2.10                 h7b6447c_2  
markupsafe                2.1.4                    pypi_0    pypi
matplotlib                3.8.0           py311h06a4308_0  
matplotlib-base           3.8.0           py311ha02d727_0  
mistune                   3.0.2                    pypi_0    pypi
mpg123                    1.32.4               h59595ed_0    conda-forge
msgpack                   1.0.7                    pypi_0    pypi
multicore-tsne            0.1_d4ff4aab    py311h92ebd52_5    conda-forge
multidict                 6.0.4                    pypi_0    pypi
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
munkres                   1.1.4                      py_0  
mysql-common              8.0.33               hf1915f5_6    conda-forge
mysql-libs                8.0.33               hca2cd23_6    conda-forge
natsort                   7.1.1              pyhd3eb1b0_0  
nbclient                  0.9.0                    pypi_0    pypi
nbconvert                 7.14.2                   pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1             py311h06a4308_0  
notebook                  7.0.7                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
nspr                      4.35                 h6a678d5_0  
nss                       3.97                 h1d7d5a4_0    conda-forge
numba                     0.58.1          py311h96b013e_0    conda-forge
numexpr                   2.8.7           py311h812550d_0  
numpy                     1.23.5                   pypi_0    pypi
numpy-groupies            0.10.2                   pypi_0    pypi
openjpeg                  2.5.0                h488ebb8_3    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
overrides                 7.6.0                    pypi_0    pypi
packaging                 23.1            py311h06a4308_0  
pandas                    2.1.4           py311ha02d727_0  
pandocfilters             1.5.1                    pypi_0    pypi
partd                     1.4.1                    pypi_0    pypi
patsy                     0.5.3           py311h06a4308_0  
pcre2                     10.42                hebb0a14_0  
pillow                    10.2.0          py311ha6c5da5_0    conda-forge
pip                       23.3.1          py311h06a4308_0  
pixman                    0.43.0               h59595ed_0    conda-forge
ply                       3.11            py311h06a4308_0  
prometheus-client         0.19.0                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pulseaudio-client         16.1                 hb77b528_5    conda-forge
py-cpuinfo                9.0.0           py311h06a4308_0  
pyarrow                   15.0.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pynndescent               0.5.10          py311h06a4308_0  
pyparsing                 3.0.9           py311h06a4308_0  
pyqt                      5.15.10         py311h6a678d5_0  
pyqt5-sip                 12.13.0         py311h5eee18b_0  
pyscenic                  0.12.1+6.g31d51a1          pypi_0    pypi
pytables                  3.9.2           py311h9d13977_0  
python                    3.11.7          hab00c5b_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-igraph             0.11.3          py311h8290d24_1    conda-forge
python-json-logger        2.0.7                    pypi_0    pypi
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1    py311h06a4308_0  
pyyaml                    6.0.1                    pypi_0    pypi
qt-main                   5.15.8              h450f30e_18    conda-forge
readline                  8.2                  h5eee18b_0  
referencing               0.32.1                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rpds-py                   0.17.1                   pypi_0    pypi
scanpy                    1.9.6              pyhd8ed1ab_1    conda-forge
scikit-learn              1.2.2           py311h6a678d5_1  
scipy                     1.11.4          py311h24aa872_0  
seaborn                   0.12.2          py311h06a4308_0  
send2trash                1.8.2                    pypi_0    pypi
session-info              1.0.0              pyhd8ed1ab_0    conda-forge
setuptools                68.2.2          py311h06a4308_0  
sip                       6.7.12          py311h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
statsmodels               0.14.0          py311hf4808d0_0  
stdlib-list               0.8.0           py311h06a4308_0  
tblib                     3.0.0                    pypi_0    pypi
terminado                 0.18.0                   pypi_0    pypi
texttable                 1.6.4              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toolz                     0.12.0          py311h06a4308_0  
tornado                   6.3.3           py311h5eee18b_0  
tqdm                      4.65.0          py311h92b7b1e_0  
types-python-dateutil     2.8.19.20240106          pypi_0    pypi
tzdata                    2023d                h04d1e81_0  
umap-learn                0.5.3           py311h06a4308_0  
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.7.0                    pypi_0    pypi
wheel                     0.41.2          py311h06a4308_0  
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xkeyboard-config          2.40                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007  
xyzservices               2023.10.1                pypi_0    pypi
xz                        5.4.5                h5eee18b_0  
yarl                      1.9.4                    pypi_0    pypi
zict                      3.0.0                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               hd590300_5    conda-forge
zlib-ng                   2.0.7                h5eee18b_0  
zstd                      1.5.5                hc292b87_0  
```

**Comment by xiepu969** [comment]
Could you please tell me how you solved this problem as I had the same situation.

**Comment by JamesHowie14** [comment]
@maaraujo10, how did you resolve ..
