### ISSUE TITLE
[BUG] Empty adjacent.tsv file generated: troubleshooting pyscenic grn analysis via Docker

### ISSUE THREAD

**Issue by amberqiong** [aertslab/pySCENIC#529]
Hello,

Thanks for developing this great tool. I am trying to use pySCENIC to analyze the data from a Seurat object via docker. I initially tested with a subset of data (32802genes X 4045cells ).  However, when running  **"pyscenic grn"**, which took over 18h, it resulted in a empty **"adjacent.tsv"** file without any reported error. I would appreciate any suggestions to resolve this issue. 

**Steps to reproduce the behavior**
1. Obtain the count matrix (.tsv) from Seurat object

```
library(Seurat)
lipo=readRDS("/Users/liguo/Desktop/lipoglucotoxicity/all_samples/lipoglucotoxicity.integrated.120823.rds")
lipo_subset=subset(lipo,idents="alpha")
rm(lipo)
lipo_subset_ctrl=subset(lipo_subset,subset = condition=="Ctrl"&sex=="male")
lipo_count_matrix=lipo_subset_ctrl@assays$RNA$counts

lipo_count_matrix=as.matrix(lipo_count_matrix)
transposed_counts_matrix <- t(lipo_count_matrix)
cell.id=rownames(transposed_counts_matrix)
transposed_counts_matrix_1=as.data.frame(transposed_counts_matrix)
transposed_counts_matrix_1=data.frame(cell.id=cell.id,transposed_counts_matrix_1)
row.names(transposed_counts_matrix_1)=NULL

write.table(transposed_counts_matrix_1, file = "alpha_male.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```

The alpha_male.tsv structure is showed below.

```
(pyscenic) liguo@wc-dhcp11d031 DATA % head -n 10 alpha_male.tsv| cut -f 1-10
cell.id	AL627309.1	AL627309.3	AL627309.5	AP006222.2	AC114498.1	LINC01409	FAM87B	LINC01128	LINC00115
CITH107_Ctrl_AAACGAAAGATGGCAC-1	0	0	0	0	0	0	0	1	0
CITH107_Ctrl_AAAGAACGTTGGTAGG-1	0	0	0	0	0	0	0	0	0
CITH107_Ctrl_AAAGAACTCCACATAG-1	0	0	0	0	0	0	0	0	0
CITH107_Ctrl_AAAGGATCAATGTCTG-1	0	0	0	0	0	0	0	0	0
CITH107_Ctrl_AAAGGATGTACCTTCC-1	0	0	0	0	0	0	0	0	0
CITH107_Ctrl_AAAGGGCCAACTACGT-1	0	0	0	0	0	0	0	0	0
CITH107_Ctrl_AACAACCGTGTAGTGG-1	0	0	0	0	0	0	0	0	0
CITH107_Ctrl_AACAAGACACCGTGAC-1	0	0	0	0	0	0	0	0	0
CITH107_Ctrl_AACAAGATCACTCCGT-1	0	0	0	0	0	0	0	0	0
```

2. Run docker pySCENIC on this matrix:

```
(pyscenic) liguo@wc-dhcp11d031 DATA % docker run -it --rm \
    -v /Users/liguo/Desktop/lipoglucotoxicity/all_samples/SCENIC/DATA:/data \ 
    aertslab/pyscenic:0.12.1 pyscenic grn \
        --num_workers 6 \
        -o /data/alpha_male_mat.adj.tsv \
        /data/alpha_male.tsv \
        /data/allTFs_hg38.txt
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

2024-02-16 20:55:44,433 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
2024-02-16 20:56:20,280 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
preparing dask client
parsing input
creating dask graph
6 partitions
computing dask graph
```
The process stopped after 18h, but alpha_male_mat.adj.tsv is empty.

```
(pyscenic) liguo@wc-dhcp11d031 DATA % docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED        STATUS        PORTS      NAMES
4591ea6cbdbc   aertslab/pyscenic:0.12.1   "pyscenic grn --num_…"   17 hours ago   Up 17 hours   8787/tcp   thirsty_neumann
```
**The Enviroment details are:**
- pySCENIC version: 0.12.1
- Installation method: Docker
- OS: mac-OS

```
(pyscenic) liguo@wc-dhcp11d031 DATA % docker run -it --rm aertslab/pyscenic:0.12.1 pyscenic -h 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
usage: pyscenic [-h] {grn,add_cor,ctx,aucell} ...

Single-Cell rEgulatory Network Inference and Clustering (0.12.1+0.gce41b61.dirty)

positional arguments:
  {grn,add_cor,ctx,aucell}
                        sub-command help
    grn                 Derive co-expression modules from expression matrix.
    add_cor             [Optional] Add Pearson correlations based on TF-gene expression to the network adjacencies output from the GRN step, and output these to a new adjacencies file.
                        This will normally be done during the "ctx" step.
    ctx                 Find enriched motifs for a gene signature and optionally prune targets from this signature based on cis-regulatory cues.
    aucell              Quantify activity of gene signatures across single cells.

options:
  -h, --help            show this help message and exit

Arguments can be read from file using a @args.txt construct. For more information on loom file format see http://loompy.org . For more information on gmt file format see
https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Data_formats .
```

**Comment by ghuls** [comment]
You need to transpose: `alpha_male.tsv`

Or add `--transpose`:
```bash
docker run -it --rm \
    -v /Users/liguo/Desktop/lipoglucotoxicity/all_samples/SCENIC/DATA:/data \ 
    aertslab/pyscenic:0.12.1 pyscenic grn \
        --num_workers 6 \
        --transpose \
        -o /data/alpha_male_mat.adj.tsv \
        /data/alpha_male.tsv \
        /data/allTFs_hg38.txt
```

**Comment by amberqiong** [comment]
@ghuls Thanks for your reply, however, I got the error when `--transpose` was added:

```
(pyscenic) liguo@wc-dhcp32d127 DATA % docker run -it --rm \
-v /Users/liguo/Desktop/lipoglucotoxicity/all_samples/SCENIC/DATA:/data \
aertslab/pyscenic:0.12.1 pyscenic grn \
--num_worker 6 \
--transpose \
-o /data/alpha_male.adj.tsv \
/data/alpha_male.tsv \
> /data/allTFs_hg38.txt
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

2024-02-22 19:24:35,815 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2024-02-22 19:25:11,950 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
preparing dask client
parsing input
not shutting down client, client was created externally
finished
Traceback (most recent call last):
  File "/opt/venv/bin/pyscenic", line 33, in <module>
    sys.exit(load_entry_point('pyscenic==0.12.1+0.gce41b61.dirty', 'console_scripts', 'pyscenic')())
  File "/opt/venv/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 713, in main
    args.func(args)
  File "/opt/venv/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 106, in find_adjacencies_command
    network = method(
  File "/opt/venv/lib/python3.10/site-packages/arboreto/algo.py", line 39, in grnboost2
    return diy(expression_data=expression_data, regressor_type='GBM', regressor_kwargs=SGBM_KWARGS,
  File "/opt/venv/lib/python3.10/site-packages/arboreto/algo.py", line 115, in diy
    expression_matrix, gene_names, tf_names = _prepare_input(expression_data, gene_names, tf_names)
  File "/opt/venv/lib/python3.10/site-packages/arboreto/algo.py", line 229, in _prepare_input
    raise ValueError('Intersection of gene_names and tf_names is empty.')
ValueError: Intersection of gene_names and tf_names is empty.
```

**Comment by ghuls** [comment]
Do you have any overlap between your TFs and genes in your expression matrix?
```
head -n 1 /data/alpha_male.tsv | cut -f 2- | tr '\t' '\n' > gene_list.txt

grep -w -f /data/allTFs_hg38.txt gene_list.txt 
```

**Comment by amberqiong** [comment]
@ghuls Yes, it has 1797 overlaps.

```
(base) liguo@wc-dhcp32d127 DATA % head -n 1 alpha_male.tsv | cut -f 2- | tr '\t' '\n' > gene_list.txt
(base) liguo@wc-dhcp32d127 DATA % comm -12 <(sort gene_list.txt) <(sort allTFs_hg38.txt) | head -n 10
A1CF
ABCF2
ABL1
ACAA1
ACO1
ADARB1
ADNP
ADNP2
AEBP2
AFF4
```

**Comment by ghuls** [comment]
In that case the first command (without `--transpose`) should have been fine.

You are also trying to run the linux/amd64 docker image on a Mac with an ARM CPU and it might be that the emulation causes some issues:
https://dev.to/docker/run-x86-containers-on-apple-mac-m1-with-rosetta-2-417a

It would be good to try on a real Linux machine.

**Comment by amberqiong** [comment]
Thank you, I tried to convert the seurat object to loom by 
`lipo_subset_500.loom=as.loom(lipo_subset_500,filename = "liponew_1.loom",verbose = FALSE)`
`lipo_subset_500.loom$close_all()`

And run the output loom in apptainer, it works. Hope this is useful for others.
`apptainer run aertslab-pyscenic-0.12.1.sif \
    pyscenic grn \
        --num_workers 25 \
        -o /gpfs/home/lg23w/lipoglucotoxicity/SCENIC/lipo_subset_500.loom.adj.tsv \
        /gpfs/home/lg23w/lipoglucotoxicity/SCENIC/lipo_subset_500.loom.loom \
        /gpfs/home/lg23w/lipoglucotoxicity/SCENIC/allTFs_hg38.txt`

**Comment by LynnChan99** [comment]
> You need to transpose: `alpha_male.tsv`
> 
> Or add `--transpose`:
> 
> docker run -it --rm \
>     -v /Users/liguo/Desktop/lipoglucotoxicity/all_samples/SCENIC/DATA:/data \ 
>     aertslab/pyscenic:0.12.1 pyscenic grn \
>         --num_workers 6 \
>         --transpose \
>         -o /data/alpha_male_mat.adj.tsv \
>         /data/alpha_male.tsv \
>         /data/allTFs_hg38.txt

Hi, I have transposed the t(as.matrix(counts) file into loom file by using x.X.transpose() in python, but still generated empty adjacent csv. file.
