### ISSUE TITLE
ValueError: Usecols do not match columns, columns expected but not found: ['motif_similarity_qvalue', '#motif_id', 'orthologous_identity', 'gene_name', 'description']

### ISSUE THREAD

**Issue by jnmaciuch** [aertslab/pySCENIC#533]
Hello,

I keep running into the following error when I try to run the ctx command after completing the GRNboost step. 

Most recently I encountered this issue using the following two files as f_db_names:
`'/projects/p31982/Reference_files/pySCENIC/mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings.feather /projects/p31982/Reference_files/pySCENIC/mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings.feather'`

and 'mm_mgi_tfs.txt' as MM_TFS_FNAME created from https://resources.aertslab.org/cistarget/motif2tf/motifs-v9-nr.mgi-m0.001-o0.0.tbl. However, I have encountered the same error no matter which versions of the mouse data bases and motif names I use. I have tried the .feather files located at /mm10/refseq_r80/mc9nr/ and /mm9/refseq_r45/mc9nr/ on your resources page.

**Steps to reproduce the behavior**
Command run when the error occurred:

```python
!pyscenic ctx adj.csv \
    {f_db_names} \
    --annotations_fname {MM_TFS_FNAME} \
    --expression_mtx_fname {converted_seurat_object.h5ad} \
    --output reg.csv \
    --mask_dropouts \
    --num_workers 6
```

Error encountered:
```python
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

2024-03-18 18:06:57,153 - pyscenic.cli.pyscenic - INFO - Creating modules.

2024-03-18 18:06:58,572 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2024-03-18 18:07:00,138 - pyscenic.utils - INFO - Calculating Pearson correlations.

2024-03-18 18:07:00,608 - pyscenic.utils - WARNING - Note on correlation calculation: the default behaviour for calculating the correlations has changed after pySCENIC verion 0.9.16. Previously, the default was to calculate the correlation between a TF and target gene using only cells with non-zero expression values (mask_dropouts=True). The current default is now to use all cells to match the behavior of the R verision of SCENIC. The original settings can be retained by setting 'rho_mask_dropouts=True' in the modules_from_adjacencies function, or '--mask_dropouts' from the CLI.
	Dropout masking is currently set to [True].

2024-03-18 18:07:29,476 - pyscenic.utils - INFO - Creating modules.

2024-03-18 18:08:27,860 - pyscenic.cli.pyscenic - INFO - Loading databases.

2024-03-18 18:08:28,295 - pyscenic.cli.pyscenic - INFO - Calculating regulons.

2024-03-18 18:08:28,295 - pyscenic.prune - INFO - Using 6 workers.

2024-03-18 18:08:28,295 - pyscenic.prune - INFO - Using 6 workers.

2024-03-18 18:08:29,684 - pyscenic.prune - INFO - Worker mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(2): database loaded in memory.

2024-03-18 18:08:29,684 - pyscenic.prune - INFO - Worker mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(2): database loaded in memory.
Process mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(2):

2024-03-18 18:08:29,762 - pyscenic.prune - INFO - Worker mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(3): database loaded in memory.

2024-03-18 18:08:29,762 - pyscenic.prune - INFO - Worker mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(3): database loaded in memory.
Traceback (most recent call last):
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/multiprocessing_on_dill/process.py", line 254, in _bootstrap
    self.run()
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/prune.py", line 131, in run
    orthologous_identity_threshold=self.orthologuous_identity_threshold,
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/utils.py", line 57, in load_motif_annotations
    df = pd.read_csv(fname, sep="\t", index_col=[1, 0], usecols=column_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 867, in _validate_usecols_names
    f"Usecols do not match columns, columns expected but not found: "
ValueError: Usecols do not match columns, columns expected but not found: ['motif_similarity_qvalue', '#motif_id', 'orthologous_identity', 'gene_name', 'description']
Process mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(3):
Traceback (most recent call last):
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/multiprocessing_on_dill/process.py", line 254, in _bootstrap
    self.run()
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/prune.py", line 131, in run
    orthologous_identity_threshold=self.orthologuous_identity_threshold,
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/utils.py", line 57, in load_motif_annotations
    df = pd.read_csv(fname, sep="\t", index_col=[1, 0], usecols=column_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 867, in _validate_usecols_names
    f"Usecols do not match columns, columns expected but not found: "
ValueError: Usecols do not match columns, columns expected but not found: ['motif_similarity_qvalue', '#motif_id', 'orthologous_identity', 'gene_name', 'description']

2024-03-18 18:08:29,803 - pyscenic.prune - INFO - Worker mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(1): database loaded in memory.

2024-03-18 18:08:29,803 - pyscenic.prune - INFO - Worker mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(1): database loaded in memory.
Process mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings(1):
Traceback (most recent call last):
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/multiprocessing_on_dill/process.py", line 254, in _bootstrap
    self.run()
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/prune.py", line 131, in run
    orthologous_identity_threshold=self.orthologuous_identity_threshold,
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/utils.py", line 57, in load_motif_annotations
    df = pd.read_csv(fname, sep="\t", index_col=[1, 0], usecols=column_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]

  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 867, in _validate_usecols_names
    f"Usecols do not match columns, columns expected but not found: "
ValueError: Usecols do not match columns, columns expected but not found: ['motif_similarity_qvalue', '#motif_id', 'orthologous_identity', 'gene_name', 'description']

2024-03-18 18:08:30,093 - pyscenic.prune - INFO - Worker mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(2): database loaded in memory.

2024-03-18 18:08:30,093 - pyscenic.prune - INFO - Worker mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(2): database loaded in memory.
Process mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(2):
Traceback (most recent call last):
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/multiprocessing_on_dill/process.py", line 254, in _bootstrap
    self.run()
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/prune.py", line 131, in run
    orthologous_identity_threshold=self.orthologuous_identity_threshold,
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/utils.py", line 57, in load_motif_annotations
    df = pd.read_csv(fname, sep="\t", index_col=[1, 0], usecols=column_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 867, in _validate_usecols_names
    f"Usecols do not match columns, columns expected but not found: "
ValueError: Usecols do not match columns, columns expected but not found: ['motif_similarity_qvalue', '#motif_id', 'orthologous_identity', 'gene_name', 'description']

2024-03-18 18:08:30,276 - pyscenic.prune - INFO - Worker mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(1): database loaded in memory.

2024-03-18 18:08:30,276 - pyscenic.prune - INFO - Worker mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(1): database loaded in memory.
Process mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(1):
Traceback (most recent call last):
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/multiprocessing_on_dill/process.py", line 254, in _bootstrap
    self.run()
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/prune.py", line 131, in run
    orthologous_identity_threshold=self.orthologuous_identity_threshold,
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/utils.py", line 57, in load_motif_annotations
    df = pd.read_csv(fname, sep="\t", index_col=[1, 0], usecols=column_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 867, in _validate_usecols_names
    f"Usecols do not match columns, columns expected but not found: "
ValueError: Usecols do not match columns, columns expected but not found: ['motif_similarity_qvalue', '#motif_id', 'orthologous_identity', 'gene_name', 'description']

2024-03-18 18:08:30,385 - pyscenic.prune - INFO - Worker mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(3): database loaded in memory.

2024-03-18 18:08:30,385 - pyscenic.prune - INFO - Worker mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(3): database loaded in memory.
Process mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings(3):
Traceback (most recent call last):
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/multiprocessing_on_dill/process.py", line 254, in _bootstrap
    self.run()
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/prune.py", line 131, in run
    orthologous_identity_threshold=self.orthologuous_identity_threshold,
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pyscenic/utils.py", line 57, in load_motif_annotations
    df = pd.read_csv(fname, sep="\t", index_col=[1, 0], usecols=column_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "/projects/p31982/Mac_paper/CD11b+_scRNA/pyscenic/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 867, in _validate_usecols_names
    f"Usecols do not match columns, columns expected but not found: "
ValueError: Usecols do not match columns, columns expected but not found: ['motif_similarity_qvalue', '#motif_id', 'orthologous_identity', 'gene_name', 'description']
```

The output above is always repeated for every filepath in f_db_names. Any help would be greatly appreciated!

**Please complete the following information:**
- pySCENIC version: 0.12.1
- Installation method: pypi
- Run environment: Jupyter notebook
- OS: GNU/Linux
- Package versions: 
```# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
aiohttp                   3.8.6                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anndata                   0.8.0                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
arboreto                  0.1.6                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    6.0.0                    pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
boltons                   23.1.1                   pypi_0    pypi
ca-certificates           2023.12.12           h06a4308_0  
certifi                   2022.12.7        py37h06a4308_0  
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
comm                      0.1.4                    pypi_0    pypi
ctxcore                   0.2.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cytoolz                   0.12.3                   pypi_0    pypi
dask                      2022.2.0                 pypi_0    pypi
debugpy                   1.7.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
distributed               2022.2.0                 pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
fastjsonschema            2.19.1                   pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
frozendict                2.4.0                    pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.1.0                 pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
idna                      3.6                      pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
interlap                  0.2.7                    pypi_0    pypi
ipykernel                 6.16.2                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.1.2                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.4.9                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              4.12.0                   pypi_0    pypi
jupyter-server            1.24.0                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.10                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
llvmlite                  0.39.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
loompy                    3.0.7                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
msgpack                   1.0.5                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
nbclassic                 1.0.0                    pypi_0    pypi
nbclient                  0.7.4                    pypi_0    pypi
nbconvert                 7.6.0                    pypi_0    pypi
nbformat                  5.8.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
notebook                  6.5.6                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numexpr                   2.8.6                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.19.5           py37h622ebfc_4  
numpy-groupies            0.9.22                   pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0  
packaging                 24.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.4.1                    pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pyarrow                   12.0.1                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pynndescent               0.5.11                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pyscenic                  0.12.1                   pypi_0    pypi
python                    3.7.16               h7a1cb2a_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qtconsole                 5.4.4                    pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
scanpy                    1.9.3                    pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.12.2                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                65.6.3           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
statsmodels               0.13.5                   pypi_0    pypi
stdlib-list               0.10.0                   pypi_0    pypi
tblib                     2.0.0                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
toolz                     0.12.1                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.66.2                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
umap-learn                0.5.5                    pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.1                    pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0  
widgetsnbextension        4.0.10                   pypi_0    pypi
xz                        5.4.6                h5eee18b_0  
yarl                      1.9.4                    pypi_0    pypi
zict                      2.2.0                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
```

EDIT: Changed issue title to fix incorrect error message, as previous error message was generated using motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl instead of motifs-v9-nr.mgi-m0.001-o0.0.tbl. Variations on this error still occur regardless of which motifs file are used.

**Comment by jnmaciuch** [comment]
Updated title to fix incorrect error message that dud
