### ISSUE TITLE
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.

### ISSUE THREAD

**Issue by xiaodiYan** [aertslab/pySCENIC#549]
Hosting the HTTP server on port 37975 instead
  warnings.warn(
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
/home/YanXiaoDi/miniconda3/envs/python39/lib/python3.9/site-packages/loompy/bus_file.py:68: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def twobit_to_dna(twobit: int, size: int) -> str:
/home/YanXiaoDi/miniconda3/envs/python39/lib/python3.9/site-packages/loompy/bus_file.py:85: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def dna_to_twobit(dna: str) -> int:
creating dask graph
not shutting down client, client was created externally
finished
Traceback (most recent call last):
  File "/home/YanXiaoDi/miniconda3/envs/python39/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/home/YanXiaoDi/miniconda3/envs/python39/lib/python3.9/site-packages/pyscenic/cli/pyscenic.py", line 713, in main
    args.func(args)
  File "/home/YanXiaoDi/miniconda3/envs/python39/lib/python3.9/site-packages/pyscenic/cli/pyscenic.py", line 97, in find_adjacencies_command
    network = method(
  File "/home/YanXiaoDi/miniconda3/envs/python39/lib/python3.9/site-packages/arboreto/algo.py", line 39, in grnboost2
    return diy(expression_data=expression_data, regressor_type='GBM', regressor_kwargs=SGBM_KWARGS,
  File "/home/YanXiaoDi/miniconda3/envs/python39/lib/python3.9/site-packages/arboreto/algo.py", line 120, in diy
    graph = create_graph(expression_matrix,
  File "/home/YanXiaoDi/miniconda3/envs/python39/lib/python3.9/site-packages/arboreto/core.py", line 450, in create_graph
    all_meta_df = from_delayed(delayed_meta_dfs, meta=_META_SCHEMA)
  File "/home/YanXiaoDi/miniconda3/envs/python39/lib/python3.9/site-packages/dask_expr/io/_delayed.py", line 101, in from_delayed
    raise TypeError("Must supply at least one delayed object")

**Comment by ghuls** [comment]
Can you with try with the Docker/Podman/Singularity/Apptainer images instead?
https://pyscenic.readthedocs.io/en/latest/installation.html#docker-podman-and-singularity-apptainer-images
