### ISSUE TITLE
[ERROR] in running Pyscenic GRN grnboost2

### ISSUE THREAD

**Issue by husain223** [aertslab/pySCENIC#557]
**Describe the bug**
I am trying to run Pyscenic GRN but its giving me error and i am unable to solve the issue.

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```python
pyscenic grn dm6_filtered_scenic.loom allTFs_dmel.txt -o adjw.csv --method grnboost2

```

2. Error encountered:

```pytb
2024-06-24 11:50:18,063 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pyscenic/bin/pyscenic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/pyscenic/cli/pyscenic.py", line 713, in main
    args.func(args)
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/pyscenic/cli/pyscenic.py", line 59, in find_adjacencies_command
    ex_mtx = load_exp_matrix(
             ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/pyscenic/cli/utils.py", line 134, in load_exp_matrix
    return load_exp_matrix_as_loom(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/pyscenic/cli/utils.py", line 82, in load_exp_matrix_as_loom
    with lp.connect(fname, mode="r", validate=False) as ds:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/loompy/loompy.py", line 1515, in connect
    return LoomConnection(filename, mode, validate=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/loompy/loompy.py", line 98, in __init__
    self.attrs = loompy.GlobalAttributeManager(self._file)  #: Global attributes
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/loompy/global_attribute_manager.py", line 23, in __init__
    materialized = loompy.materialize_attr_values(val[()])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/loompy/normalize.py", line 91, in materialize_attr_values
    if np.issubdtype(a.dtype, np.string_) or np.issubdtype(a.dtype, np.object_):
                              ^^^^^^^^^^
  File "/opt/miniconda3/envs/pyscenic/lib/python3.12/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.. Did you mean: 'strings'?


```

**Please complete the following information:**
- pySCENIC version: Single-Cell rEgulatory Network Inference and Clustering (0.12.1+2.geaf23eb)
- Installation method: conda
- Run environment: bash
- OS: mac
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:
- System config: M2 Chip,24 GB RAM,1.5 TB free space.

**Comment by ghuls** [comment]
Install an older version of numpy.

**Comment by ghuls** [comment]
Or use the Docker/Podman/Singularity/Apptainer images:
https://pyscenic.readthedocs.io/en/latest/installation.html#docker-podman-and-singularity-apptainer-images

**Comment by sd68515** [comment]
conda create -y -n pyscenic python=3.10
conda activate pyscenic
pip install pyscenic
pip install git+https://github.com/aertslab/pySCENIC.git
# git clone https://github.com/aertslab/pySCENIC.git
# cd pySCENIC/
# pip install .
pip install numpy==1.23.5

that is all
