### ISSUE TITLE
[BUG] pyscenic grn and type error

### ISSUE THREAD

**Issue by tutu256** [aertslab/pySCENIC#567]
hi. I try to run through the pySCENIC protocol: PBMC10k on my windows 10 .
when i run the SCENIC steps 1, error happened.
this is my code.
!pyscenic grn E:/python/pbmc10k_filtered_scenic.loom D:/scenic/input/allTFs_hg38.txt -o adj.csv --num_workers 20
errors:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\anaconda3\Scripts\pyscenic.exe\__main__.py", line 4, in <module>
  File "d:\anaconda3\Lib\site-packages\pyscenic\cli\pyscenic.py", line 19, in <module>
    from arboreto.algo import genie3, grnboost2
  File "d:\anaconda3\Lib\site-packages\arboreto\algo.py", line 7, in <module>
    from arboreto.core import create_graph, SGBM_KWARGS, RF_KWARGS, EARLY_STOP_WINDOW_LENGTH
  File "d:\anaconda3\Lib\site-packages\arboreto\core.py", line 12, in <module>
    from dask.dataframe import from_delayed
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\__init__.py", line 6, in <module>
    from dask.dataframe import backends, dispatch, rolling
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\backends.py", line 15, in <module>
    from dask.dataframe.core import DataFrame, Index, Scalar, Series, _Frame
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\core.py", line 36, in <module>
    from dask.dataframe import methods
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\methods.py", line 34, in <module>
    from dask.dataframe.utils import is_dataframe_like, is_index_like, is_series_like
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\utils.py", line 20, in <module>
    from dask.dataframe import (  # noqa: F401 register pandas extension types
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\_dtypes.py", line 9, in <module>
    from dask.dataframe.extensions import make_array_nonempty, make_scalar
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\extensions.py", line 8, in <module>
    from dask.dataframe.accessor import (
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\accessor.py", line 126, in <module>
    class DatetimeAccessor(Accessor):
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\accessor.py", line 81, in __init_subclass__
    _bind_property(cls, pd_cls, attr, min_version)
  File "d:\anaconda3\Lib\site-packages\dask\dataframe\accessor.py", line 35, in _bind_property
    setattr(cls, attr, property(derived_from(pd_cls, version=min_version)(func)))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\site-packages\dask\utils.py", line 856, in wrapper
    method.__doc__ = _derived_from(
                     ^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\site-packages\dask\utils.py", line 809, in _derived_from
    method_args = get_named_args(method)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\site-packages\dask\utils.py", line 570, in get_named_args
    s = inspect.signature(func)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\inspect.py", line 3263, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\inspect.py", line 3011, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\inspect.py", line 2599, in _signature_from_callable
    call = _descriptor_get(call, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\inspect.py", line 2432, in _descriptor_get
    return get(descriptor, obj, type(obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor '__call__' for 'type' objects doesn't apply to a 'property' object.

how to fix it?

**Comment by 123zelia** [comment]
Hi, I am also having the same issue. Have you resolved it?
