### ISSUE TITLE
[BUG]pyscenic error with numpy has no attribute 'object'

### ISSUE THREAD

**Issue by anyang-kevin** [aertslab/pySCENIC#579]
`pyscenic grn
/public/home/anyang/tool/conda/miniconda3/envs/scanpy/lib/python3.11/site-packages/pyscenic/transform.py:42: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
Traceback (most recent call last):
  File "/public/home/anyang/tool/conda/miniconda3/envs/scanpy/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/public/home/anyang/tool/conda/miniconda3/envs/scanpy/lib/python3.11/site-packages/pyscenic/cli/pyscenic.py", line 26, in <module>
    from pyscenic.prune import _prepare_client, find_features, prune2df
  File "/public/home/anyang/tool/conda/miniconda3/envs/scanpy/lib/python3.11/site-packages/pyscenic/prune.py", line 27, in <module>
    from .transform import (
  File "/public/home/anyang/tool/conda/miniconda3/envs/scanpy/lib/python3.11/site-packages/pyscenic/transform.py", line 42, in <module>
    ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
                                            ^^^^^^^^^
  File "/public/home/anyang/tool/conda/miniconda3/envs/scanpy/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?
`
Here is my error when i use pyscenic. My numpy version is 1.24.3. How do I fix it?

**Comment by anyang-kevin** [comment]
Numpy deleted np.object in 1.20. The only way right now is change the code in pyscenic/transform.py. Change all np.object to object can call out the help page.

**Comment by ghuls** [comment]
Use the git version of pySCENIC: https://github.com/aertslab/pySCENIC/commit/eaf23eb1fdcaae79b273de56b374b71aa8afde5a

Or use the existing container images of pySCENIC.

**Comment by aowenson-imm** [comment]
What is preventing a new PIP release?
