### ISSUE TITLE
error when runing adjacencies = grnboost2(ex_matrix, tf_names=tf_names, verbose=True) 

### ISSUE THREAD

**Issue by yuliusema4** [aertslab/pySCENIC#58]
Hi

I successfully run a handful datasets. But got error for the last dataset, here are the message:

>>> adjacencies = grnboost2(ex_matrix, tf_names=tf_names, verbose=True) 
preparing dask client
parsing input
/home/yu_liu/.local/lib/python3.6/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
creating dask graph
8 partitions
computing dask graph
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:40722 remote=tcp://127.0.0.1:33713>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:40724 remote=tcp://127.0.0.1:33713>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:40726 remote=tcp://127.0.0.1:33713>
distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (           TF  target  importance
587      PDX1     NaN    4.557409
43      IKZF2     NaN    1.383575
541      EMX1     NaN    1.264551
650    ZNF300     NaN    1.249224
1023   STAT5B     NaN    1.134848
1019    INSM1     NaN    1.116987
920    ZBTB43     NaN    1.111201
299      HES1     NaN    1.086385
285    ZBTB24     NaN    1.067774
1529      SP9     NaN    1.051621
298     TFDP2     NaN    1.042101
1294     MTF1     NaN    0.993883
853     MYRFL     NaN    0.990080
1076     IRX5     NaN    0.980175
1322   ZNF836     NaN    0.951067
327      ETV3     NaN    0.924852
987     NHLH1     NaN    0.874245
1509   ZNF726     NaN    0.873340
170      ADNP     NaN    0.849130
1438     ZXDB     NaN    0.641062
1251     NKRF     NaN    0.138088
59      PRDM1     NaN    0.125185
25       NME2     NaN    0.122399
711   TGIF2LX     NaN    0.119234
4        SOX8     NaN    0.117549
551      TBR1     NaN    0.061086
1205  FOXD4L1     NaN    0.059487
616    ZNF787     NaN    0.041974
855     ZMAT1
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nPartition type: `DataFrame`\n+--------+---------+----------+\n| Column | Found   | Expected |\n+--------+---------+----------+\n| target | float64 | object   |\n+--------+---------+----------+',)

distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (            TF  target  importance
182       KLF5     NaN    1.796901
1400   ZNF780A     NaN    1.255619
113      SRCAP     NaN    1.044298
1529       SP9     NaN    1.014616
1551       JRK     NaN    0.969606
94      SREBF1     NaN    0.959533
497     ZNF141     NaN    0.903381
722       BATF     NaN    0.891596
363     SOHLH2     NaN    0.848746
1432    ZNF813     NaN    0.833871
415      RUNX2     NaN    0.828340
966      HSFX2     NaN    0.792233
960      FOXN2     NaN    0.778318
106      NFKB2     NaN    0.763673
127       REST     NaN    0.758959
534      DMTF1     NaN    0.735569
266      PRDM4     NaN    0.719243
170       ADNP     NaN    0.696940
327       ETV3     NaN    0.677151
416       GCM2     NaN    0.620082
795     ANKZF1     NaN    0.582343
11    GTF2IRD1     NaN    0.567201
85       MEF2A     NaN    0.508835
1071     KCMF1     NaN    0.501975
51      ZNF800     NaN    0.498035
338     PLAGL1     NaN    0.403004
256      FOXN1     NaN    0.276789
405      SNAI1     
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nPartition type: `DataFrame`\n+--------+---------+----------+\n| Column | Found   | Expected |\n+--------+---------+----------+\n| target | float64 | object   |\n+--------+---------+----------+',)

distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (           TF  target  importance
1315   ZNF250     NaN    1.250947
1228      SP1     NaN    1.181255
299      HES1     NaN    1.159840
1141   ZNF816     NaN    1.137491
1183   ZNF721     NaN    1.126200
694    POU4F1     NaN    1.118718
753    ZBTB8A     NaN    1.084263
249    CAMTA2     NaN    1.061497
1122   ZNF664     NaN    1.051428
76      FOXJ2     NaN    0.943101
1495  ONECUT3     NaN    0.903678
316    NFE2L2     NaN    0.773948
455      PIN1     NaN    0.647856
1501     MXD3     NaN    0.642214
502    RHOXF2     NaN    0.621273
357      MXI1     NaN    0.596881
312      ATF2     NaN    0.563965
106     NFKB2     NaN    0.550881
1538   ZNF469     NaN    0.536368
1254    MYT1L     NaN    0.535402
957      ATF7     NaN    0.534378
984      BPTF     NaN    0.530043
600      IRF8     NaN    0.525196
415     RUNX2     NaN    0.518664
350    ZBTB45     NaN    0.505183
1600   ZNF850     NaN    0.495175
168    NFATC2     NaN    0.455970
1245    ZBTB6     NaN    0.447891
1401   ZNF461
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nPartition type: `DataFrame`\n+--------+---------+----------+\n| Column | Found   | Expected |\n+--------+---------+----------+\n| target | float64 | object   |\n+--------+---------+----------+',)

distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (           TF  target  importance
662    HMBOX1     NaN    1.177350
442      IRF3     NaN    1.169355
1589   ZNF878     NaN    1.115477
283      SIM1     NaN    1.113157
407     HIF3A     NaN    1.086393
1123    GATA2     NaN    1.055013
1396   ZNF595     NaN    1.046055
363    SOHLH2     NaN    1.022817
1292    SKOR1     NaN    1.020794
776     GMEB1     NaN    1.018376
169     SALL4     NaN    0.963850
837    PKNOX2     NaN    0.943171
1286     HES4     NaN    0.917107
1138    TSHZ1     NaN    0.906140
996     KLF11     NaN    0.887013
1408   ZNF823     NaN    0.870434
410    TRERF1     NaN    0.861682
29     ZBTB32     NaN    0.827065
1221    ZNF74     NaN    0.816359
243      LHX3     NaN    0.771538
1555    ZBED5     NaN    0.731618
90        MNT     NaN    0.722224
1477     DPRX     NaN    0.719250
287      TFEB     NaN    0.624701
942       FOS     NaN    0.588143
1576   HOXA10     NaN    0.326919
275       VDR     NaN    0.320166
227    HOXA13     NaN    0.311231
1049      ISX
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nPartition type: `DataFrame`\n+--------+---------+----------+\n| Column | Found   | Expected |\n+--------+---------+----------+\n| target | float64 | object   |\n+--------+---------+----------+',)

distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (           TF  target  importance
559       XPA     NaN    1.430642
1335   ZNF124     NaN    0.973843
1047   ZNF519     NaN    0.922602
721   ZKSCAN2     NaN    0.779462
652      RBAK     NaN    0.715117
1290     HMX3     NaN    0.712181
591      ESR2     NaN    0.653312
1512    MEF2B     NaN    0.626067
242     CREB3     NaN    0.625131
473     SOX15     NaN    0.613608
288       TBP     NaN    0.605124
1469     PBX2     NaN    0.596615
297      BCL6     NaN    0.559075
778     MYSM1     NaN    0.550524
135    ZNF343     NaN    0.546342
1360  ZNF705A     NaN    0.528863
61       MXD1     NaN    0.491887
221      TFEC     NaN    0.474558
137     KDM2B     NaN    0.465349
1285   ZNF383     NaN    0.463501
1491     DPF3     NaN    0.450312
127      REST     NaN    0.448734
1559   ZNF709     NaN    0.442962
763    ZBTB7B     NaN    0.438281
363    SOHLH2     NaN    0.434157
348     NR4A3     NaN    0.433643
1246   ZNF749     NaN    0.431052
613    PRDM15     NaN    0.424422
1045    DDIT3
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nPartition type: `DataFrame`\n+--------+---------+----------+\n| Column | Found   | Expected |\n+--------+---------+----------+\n| target | float64 | object   |\n+--------+---------+----------+',)

distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (           TF  target    importance
785      ATF3     NaN  4.439906e+00
41      TBPL1     NaN  2.159733e+00
589     MBNL2     NaN  9.670047e-01
764    ZNF394     NaN  9.517704e-01
145     ZFHX4     NaN  8.575002e-01
1607   ZBTB8B     NaN  8.268765e-01
1435    ZNF69     NaN  8.237028e-01
209      KLF1     NaN  8.105438e-01
237      GLI3     NaN  7.734310e-01
984      BPTF     NaN  7.378804e-01
963    ZNF415     NaN  7.123150e-01
895     BATF2     NaN  5.479090e-01
1305   ZNF33A     NaN  5.248561e-01
686     THYN1     NaN  5.120804e-01
1132    TIGD5     NaN  5.018900e-01
801     KLF15     NaN  4.725726e-01
293     NR3C1     NaN  4.360651e-01
1048    PROP1     NaN  4.342129e-01
812   FAM170A     NaN  4.338765e-01
646    CSRNP1     NaN  4.311894e-01
538     TFCP2     NaN  4.105137e-01
1379   ZNF165     NaN  3.725640e-01
967    ZNF672     NaN  3.703189e-01
82       ZFAT     NaN  3.629495e-01
1486   ZNF783     NaN  3.089804e-01
251     HNF1B     NaN  2.606121e-01
305     CENPA     NaN  2.33
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nPartition type: `DataFrame`\n+--------+---------+----------+\n| Column | Found   | Expected |\n+--------+---------+----------+\n| target | float64 | object   |\n+--------+---------+----------+',)

distributed.worker - WARNING -  Compute Failed
Function:  check_meta
args:      (           TF  target  importance
662    HMBOX1     NaN    1.177350
442      IRF3     NaN    1.169355
1589   ZNF878     NaN    1.115477
283      SIM1     NaN    1.113157
407     HIF3A     NaN    1.086393
1123    GATA2     NaN    1.055013
1396   ZNF595     NaN    1.046055
363    SOHLH2     NaN    1.022817
1292    SKOR1     NaN    1.020794
776     GMEB1     NaN    1.018376
169     SALL4     NaN    0.963850
837    PKNOX2     NaN    0.943171
1286     HES4     NaN    0.917107
1138    TSHZ1     NaN    0.906140
996     KLF11     NaN    0.887013
1408   ZNF823     NaN    0.870434
410    TRERF1     NaN    0.861682
29     ZBTB32     NaN    0.827065
1221    ZNF74     NaN    0.816359
243      LHX3     NaN    0.771538
1555    ZBED5     NaN    0.731618
90        MNT     NaN    0.722224
1477     DPRX     NaN    0.719250
287      TFEB     NaN    0.624701
942       FOS     NaN    0.588143
1576   HOXA10     NaN    0.326919
275       VDR     NaN    0.320166
227    HOXA13     NaN    0.311231
1049      ISX
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nPartition type: `DataFrame`\n+--------+---------+----------+\n| Column | Found   | Expected |\n+--------+---------+----------+\n| target | float64 | object   |\n+--------+---------+----------+',)

shutting down client and local cluster
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()
finished
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yu_liu/.local/lib/python3.6/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/arboreto/algo.py", line 135, in diy
    .compute(graph, sync=True) \
  File "/home/yu_liu/.local/lib/python3.6/site-packages/distributed/client.py", line 2504, in compute
    result = self.gather(futures)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/distributed/client.py", line 1655, in gather
    asynchronous=asynchronous)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/distributed/client.py", line 675, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/yu_liu/.local/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/yu_liu/.local/lib/python3.6/site-packages/distributed/client.py", line 1496, in _gather
    traceback)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/dask/dataframe/utils.py", line 498, in check_meta
    errmsg))
ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `DataFrame`
+--------+---------+----------+
| Column | Found   | Expected |
+--------+---------+----------+
| target | float64 | object   |
+--------+---------+----------+
>>>

**Comment by yuliusema4** [comment]
file format problem
