### ISSUE TITLE
[BUG]TypeError: _bootstrap() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by chenfengQAQ** [aertslab/pySCENIC#593]
I try to run chip_tracks with pyscenic.But I encounter some problems, I expect getting help! Thanks!
My code is follow:
pyscenic ctx control_adj.tsv D:/SCENIC_database/encode_20190621__ChIP_seq_transcription_factor.hg38__refseq-r80__500bp_up_and_100bp_down_tss.max.genes_vs_tracks.rankings.feather --annotations_fname D:/SCENIC_database/encode_project_20190621__ChIP-seq_transcription_factor.homo_sapiens.hg38.bigwig_signal_pvalue.track_to_tf_in_motif_to_tf_format.tsv --expression_mtx_fname control_pyscenic.loom --output control_500bp_reg_tracks.csv --num_workers 6

The error is follow:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Miniconda3-2024\envs\pyscenic\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Miniconda3-2024\envs\pyscenic\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
TypeError: _bootstrap() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Miniconda3-2024\envs\pyscenic\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Miniconda3-2024\envs\pyscenic\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
TypeError: _bootstrap() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Miniconda3-2024\envs\pyscenic\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Miniconda3-2024\envs\pyscenic\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
TypeError: _bootstrap() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Miniconda3-2024\envs\pyscenic\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Miniconda3-2024\envs\pyscenic\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
TypeError: _bootstrap() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\Miniconda3-2024\envs\pyscenic\lib\site-packages\multiprocessing_on_dill\connection.py", line 301, in _recv_bytes
    ov, err = _winapi.ReadFile(self._handle, bsize,
BrokenPipeError: [WinError 109] 管道已结束。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Miniconda3-2024\envs\pyscenic\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Miniconda3-2024\envs\pyscenic\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Miniconda3-2024\envs\pyscenic\Scripts\pyscenic.exe\__main__.py", line 7, in <module>
  File "D:\Miniconda3-2024\envs\pyscenic\lib\site-packages\pyscenic\cli\pyscenic.py", line 713, in main
    args.func(args)
  File "D:\Miniconda3-2024\envs\pyscenic\lib\site-packages\pyscenic\cli\pyscenic.py", line 236, in prune_targets_command
    df_motifs = calc_func(
  File "D:\Miniconda3-2024\envs\pyscenic\lib\site-packages\pyscenic\prune.py", line 424, in prune2df
    return _distributed_calc(
  File "D:\Miniconda3-2024\envs\pyscenic\lib\site-packages\pyscenic\prune.py", line 247, in _distributed_calc
    fnames = [recv.recv() for recv in receivers]
  File "D:\Miniconda3-2024\envs\pyscenic\lib\site-packages\pyscenic\prune.py", line 247, in <listcomp>
    fnames = [recv.recv() for recv in receivers]
  File "D:\Miniconda3-2024\envs\pyscenic\lib\site-packages\multiprocessing_on_dill\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "D:\Miniconda3-2024\envs\pyscenic\lib\site-packages\multiprocessing_on_dill\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

**Comment by Sophielsn** [comment]
I have the same issue. Did you solve it?
