### ISSUE TITLE
error when running binarize(auc_mtx)

### ISSUE THREAD

**Issue by yuliusema4** [aertslab/pySCENIC#61]
Hi
Here is error message:
>>> from pyscenic.binarization import binarize
>>> bin_mtx, thresholds = binarize(auc_mtx)

/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:971: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.
  return_n_iter=True)
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:971: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.
  return_n_iter=True)
/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/sklearn/cluster/k_means_.py:971: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.
  return_n_iter=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yu_liu/.local/lib/python3.6/site-packages/pyscenic/binarization.py", line 45, in binarize
    return (auc_mtx > thresholds).astype(int), thresholds
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/ops.py", line 2103, in f
    level=None)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/ops.py", line 1930, in _combine_series_frame
    return self._combine_match_columns(other, func, level=level)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/frame.py", line 5116, in _combine_match_columns
    return ops.dispatch_to_series(left, right, func, axis="columns")
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/ops.py", line 1157, in dispatch_to_series
    new_data = expressions.evaluate(column_op, str_rep, left, right)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/ops.py", line 1144, in column_op
    for i in range(len(a.columns))}
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/ops.py", line 1144, in <dictcomp>
    for i in range(len(a.columns))}
  File "/home/yu_liu/miniconda3/envs/pyscenic2/lib/python3.6/site-packages/pandas/core/ops.py", line 1745, in wrapper
    raise ValueError('Lengths must match to compare')
ValueError: Lengths must match to compare

**Comment by bramvds** [comment]
Hi Yu,

This was already reported: https://github.com/aertslab/pySCENIC/issues/51 . As a temporary workaround: using pandas version 0.23.4, this step completes with no problems.

Kindest regards,
Bram
