### ISSUE TITLE
CLI - grn - error

### ISSUE THREAD

**Issue by ltosti** [aertslab/pySCENIC#64]
Hi there,

Have been trying to run the following command:

```
pyscenic grn -o pyscenic_out.loom --num_workers 40 matrix_input_pyscenic.loom int/1.2_inputTFs.txt
```
But I keep getting this error:

```
2019-03-23 18:12:46,744 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
2019-03-23 18:12:49,729 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
distributed.utils - ERROR - cannot get address of non-running Server
Traceback (most recent call last):
  File "[...]/.local/lib/python3.6/site-packages/distributed/utils.py", line 648, in log_errors
    yield
  File "[...]/.local/lib/python3.6/site-packages/distributed/worker.py", line 488, in _close
    logger.info("Stopping worker at %s", self.address)
  File "[...]/.local/lib/python3.6/site-packages/distributed/core.py", line 228, in address
    raise ValueError("cannot get address of non-running Server")
ValueError: cannot get address of non-running Server
distributed.utils - ERROR - cannot get address of non-running Server
Traceback (most recent call last):
  File "[...]/.local/lib/python3.6/site-packages/distributed/utils.py", line 648, in log_errors
    yield
  File "[...]/.local/lib/python3.6/site-packages/distributed/worker.py", line 488, in _close
    logger.info("Stopping worker at %s", self.address)
  File "[...]/.local/lib/python3.6/site-packages/distributed/core.py", line 228, in address
    raise ValueError("cannot get address of non-running Server")
ValueError: cannot get address of non-running Server
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/bin/pyscenic", line 10, in <module>
    sys.exit(main())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 402, in main
    args.func(args)
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 64, in find_adjacencies_command
    client, shutdown_callback = _prepare_client(args.client_or_address, num_workers=args.num_workers)
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/pyscenic/prune.py", line 63, in _prepare_client
    threads_per_worker=1)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 141, in __init__
    self.start(ip=ip, n_workers=n_workers)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 171, in start
    self.sync(self._start, **kwargs)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 164, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "[...]/.local/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "[...]/.local/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 191, in _start
    yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "[...]/.local/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
```
Any idea about how to fix this? I checked on different forums, but I don't think this is something I can do without knowing the pyscenic code. 
I'm using ```pyscenic 0.9.7```.

Thank you for your attention!

**Comment by cflerin** [comment]
Hi, this looks like a dask/tornado error. Can you provide the output of `pip freeze`?  

We've seen issues with versions of dask beyond 1.0.0 (although not this particular error), so if yours is a later version, you could try downgrading.

**Comment by ltosti** [comment]
Hi,

this is my ```pip freeze```:

```
arboreto==0.1.5
attrs==18.2.0
boltons==18.0.1
certifi==2019.3.9
Click==7.0
cloudpickle==0.6.1
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.0.0
decorator==4.3.0
dill==0.2.8.2
distributed==1.24.0
frozendict==1.2
h5py==2.8.0
HeapDict==1.0.0
icc-rt==2019.0
intel-numpy==1.15.1
intel-openmp==2019.0
interlap==0.2.6
kiwisolver==1.0.1
llvmlite==0.25.0
loompy==2.0.2
matplotlib==3.0.2
mkl==2019.0
mkl-fft==1.0.0.17
mkl-random==1.0.1
msgpack==0.5.6
multiprocessing-on-dill==3.5.0a4
networkx==2.2
numba==0.40.1
numpy==1.15.4
pandas==0.23.4
psutil==5.4.8
pyarrow==0.11.1
pyparsing==2.3.0
pyscenic==0.9.7
python-dateutil==2.8.0
pytz==2018.9
PyYAML==3.13
scikit-learn==0.20.3
scipy==1.1.0
six==1.12.0
sortedcontainers==2.0.5
tbb==2019.0
tbb4py==2019.0
tblib==1.3.2
toolz==0.9.0
tornado==6.0.2
tqdm==4.28.1
typing==3.6.6
umap-learn==0.3.6
zict==0.1.3
```

It is true that dask is 1.0.0 but when I tried to downgrade it I got the same error. I don't know if it is useful, but when I tried to run 

```adjacencies = grnboost2(ex_matrix, tf_names=tf_names, verbose=True)``` 

in a python script it seems to work (or at least I get a .tsv file as output that seems to be as expected).

stdout: 

```
preparing dask client
parsing input
creating dask graph
80 partitions
computing dask graph
shutting down client and local cluster
finished
```

stderr:
```
[...]/.local/lib/python3.6/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
tornado.application - ERROR - Exception in Future <Future cancelled> after timeout
Traceback (most recent call last):
  File "[...]/miniconda3/envs/pyscenic/lib/python3.6/site-packages/tornado/gen.py", line 589, in error_callback
    future.result()
concurrent.futures._base.CancelledError
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:43198 remote=tcp://127.0.0.1:34952>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:43666 remote=tcp://127.0.0.1:34952>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:43668 remote=tcp://127.0.0.1:34952>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:43670 remote=tcp://127.0.0.1:34952>
```

**Comment by cflerin** [comment]
Hi,

Strange that you are getting this error.  I don't see anything obvious in your pipfreeze that would cause problems.  However, if you are getting an output file from GRNBoost2, then I think you should be able to use that file going forward without any issues.  Also, not sure if you saw this note in the readme for running grnboost from a script:

"If you run this from a python script instead of a Jupyter notebook, please enclose the code in a `if __name__ == '__main__':` construct."

this might help you work around the second set of errors you posted.  Closing for now since you seem to have an output file, but feel free to reopen if there are further issues.

Chris
